### ISSUE TITLE
Small bug in TimerQueue

### ISSUE THREAD

**Issue by EatonZ** [microsoft/dotnet#1015]
https://github.com/Microsoft/referencesource/blob/08b84d13e81cfdbd769a557b368539aac6a9cb30/mscorlib/system/threading/timer.cs#L90

Shouldn't `GetLastWin32Error` be `GetHRForLastWin32Error`? `GetExceptionForHR` is meant to be used on an HRESULT, not a Win32 error code.

**Comment by MarkSFrancis** [comment]
This is also happening in [dotnet core](https://source.dot.net/#System.Private.CoreLib/shared/System/Threading/TimerQueue.Windows.cs,25)

**Comment by jamshedd** [comment]
@danmosemsft, can you help redirect to the right owner?

**Comment by danmosemsft** [comment]
@EatonZ, I'm posting a bit late, but https://developercommunity.visualstudio.com/spaces/61/index.html is the right place to send .NET Framework bugs.

For this bug in .NET Core, I opened https://github.com/dotnet/coreclr/issues/26081. Thanks!
