### ISSUE TITLE
Static constuctor is not called if method was referenced for delegating

### ISSUE THREAD

**Issue by jinek** [microsoft/dotnet#1034]
According to documentation https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors static constructor 

> is called automatically before the first instance is created or any static members are referenced. 

But if method was used to subscribe to event static constructor is not called.

Example to reproduce:

```
    internal class Program
    {
        public static void Main(string[] args)
        {
            act += StaticClass.Method1;
            Debug.WriteLine("Subscribed");
            act();
        }

        public static event Action act;
    }

    internal static class StaticClass
    {
        static StaticClass()
        {
            Debug.WriteLine("Static constructor");
        }

        public static void Method1()
        {
            Debug.WriteLine("Method itself");
        }
    }
```
Result is:
_Subscribed
Static constructor
Method itself_

**Comment by rpetrusha** [comment]
Currently, the documentation reads as follows:
![image](https://user-images.githubusercontent.com/10886961/57552375-8d670f00-7320-11e9-9985-bf22875c950d.png)
Are you proposing that the documentation be modified to note that the documentation be modified to note that the constructor is not invoked for a type with a static method that is used to subscribe to an event until the event is fired? If so, would you like to open a PR in the dotnet/docs repo, @jinek?

**Comment by jinek** [comment]
Honestly, I'm not sure. As for me, it's obvious that constructor must be invoked in such an access, I was sure about that last 18 years, but almost everybody I speak to don't agree. What is your opinion?

**Comment by rpetrusha** [comment]
I think that it may be worth noting, @jinek.

**Comment by jinek** [comment]
Up to you then, I think the behavior is wrong, because that is an exception from rule. But probably it can't be changed. Up to you, I'm fine to close the issue

**Comment by rpetrusha** [comment]
Given that it is an exception (and that changing the behavior would be a breaking change), I think that it is worth noting in the documentation, @jinek. I'll close this issue and open a PR in dotnet/docs. I'll //cc you when I open it.
