### ISSUE TITLE
dotnet publish NuGet.targets(499,5): error

### ISSUE THREAD

**Issue by gggggeorge** [microsoft/dotnet#1037]
If I do:

`dotnet publish`

I always get (no matter what arguments I do/don't pass to dotnet publish):

```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.2.106\NuGet.targets(499,5): error : Value cannot be null. [C:\PROJECTS\MISC\20190513_DotNetCode_TEST\VB_NET\ConsoleApp1\ConsoleApp1.vbproj]
C:\Program Files\dotnet\sdk\2.2.106\NuGet.targets(499,5): error : Parameter name: path1 [C:\PROJECTS\MISC\20190513_DotNetCode_TEST\VB_NET\ConsoleApp1\ConsoleApp1.vbproj]
```

Here is my ConsoleApp1.vbproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp1</RootNamespace>
    <TargetFrameworks>netcoreapp2.2;net462</TargetFrameworks>
  </PropertyGroup>

</Project>
```
----
If I do a publish within the Visual Studio 2017 GUI, I can publish/target either framework, and they publish just fine, but when I do it from the DOS prompt, I get the errors.

Any ideas on what I might be doing wrong?

Thanks,
George Hynes
05/13/2019 5:30pm ET

**Comment by dasMulli** [comment]
Publishing is only supported for a single target framework, so you need to call

```
> dotnet publish -f neetcoreapp2.2
```

However, a pure `dotnet publish` should show an error like this:

> C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CrossTargeting.targets(31,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published 
application. [C:\repos\testcons\testcons.vbproj]

(downloading 2.2.106 now to check for regressions).

Are there any build customisations in your project / solution? E.g. a `Directory.Build.props` or similar?

**Comment by gggggeorge** [comment]
Hi dasMulli,

thanks for taking a look -I don't have any "funky" build customizations, but I did notice I had four .Net Core versions installed:

SDK:
2.2.106 x86
2.2.106 x64
2.2.2x x86
2.2.2x x64

I'm using Visual Studio 2017, so I had to use 2.2.106 (I didn't realize this before I posted, yesterday).

I uninstalled both 2.2.2x, and did a reboot, and now my build works, as per:

```
C:\PROJECTS\MISC\20190514_DotNetCode_TEST\ConsoleAppTESTCORE>dotnet publish -f netcoreapp2.2
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 31.55 ms for C:\PROJECTS\MISC\20190514_DotNetCode_TEST\ConsoleAppTESTCORE\ConsoleAppTESTCORE.vbproj.
  ConsoleAppTESTCORE -> C:\PROJECTS\MISC\20190514_DotNetCode_TEST\ConsoleAppTESTCORE\bin\Debug\netcoreapp2.2\ConsoleAppTESTCORE.dll
  ConsoleAppTESTCORE -> C:\PROJECTS\MISC\20190514_DotNetCode_TEST\ConsoleAppTESTCORE\bin\Debug\netcoreapp2.2\publish\

C:\PROJECTS\MISC\20190514_DotNetCode_TEST\ConsoleAppTESTCORE>
```

Thanks,
George Hynes
04/15/2019 5:03pm ET

**Comment by dasMulli** [comment]
@livarcocc fyi, hopefully this is a one-off with some bad paths..
