### ISSUE TITLE
System.IO classes no longer ignore extra backslashes before network paths (since .NET 4.6.2)

### ISSUE THREAD

**Issue by yoni-rapoport** [microsoft/dotnet#1085]
The following line of code used to return 'true' if the file existed on the network host (.NET 4.6.1 and below) and started returning 'false' with .NET 4.6.2 and above.

System.IO.File.Exists(@"\\\\\\NetworkHost\Folder\FileName")

Obviously there are too many backslashes before the network host name in this path. However, this change in behavior is causing troubling run-time issues when such paths with extra backslashes are coming from various external sources (config files, database, etc...).

**Comment by danmosemsft** [comment]
Thanks @JeremyKuhne . @yoni-rapoport does this answer your question?

@jamshedd fyi.

**Comment by yoni-rapoport** [comment]
Yes it does.

Thanks!
