### ISSUE TITLE
Project structure and naming guidelines

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [microsoft/dotnet#1093]
# Project Structure And Naming Guidelines

I am not sure, if there is a documentation already available from Microsoft for this. Watch the below video to understand the issue better.

[Video](https://youtu.be/KM5o9M4cuQA) 

I mean we can have, project structure and naming guidelines. So that it is easier to create and scale projects. I recently faced problems in naming and structuring my own projects.

**Comment by sujayvsarma** [comment]
What exactly are you asking for?

**Comment by PradeepSinghMakwana** [comment]
I am asking for a documentation. Or in whatever way you can help. What do you think is possible from my wording?

**Comment by sujayvsarma** [comment]
How you structure and name your projects and files is your preference. Other than "magic names and folders", there is no such guidance from Microsoft. It is left to you and your organization's Software Architect to determine.

**Comment by PradeepSinghMakwana** [comment]
@sujayvsarma Oh! You misunderstood. I mean how a Software Architect know how to structure projects without going through a wave of rigorous hit and try and failures. I want the video to be translated into words and included in microsoft documentation. So that people like me don't have to face the working environment-dependent problems ( which of course could be resolved ) and could instead consider doing the actual architects role. If it's needed we can also think of creating some new templates ( but that's a feature-like part ).

**Comment by sujayvsarma** [comment]
Again, I don't think Microsoft should do such a thing. It is none of Microsoft's business or concern how a project tree is structured. Also, given that Microsoft's tools today support a huge and growing number of languages, and each has their own structuring requirements, it would be something they should NOT get into. 

Like I said before, structuring projects is an intensely personal choice. It will even vary from architect to architect. For example, I don't agree with half the things in that video, that is simply not how or why I would do something.

**Comment by PradeepSinghMakwana** [comment]
> Also, given that Microsoft's tools today support a huge and growing number of languages, and each has their own structuring requirements

So should we create a structuring guidelines for most of the huge number of tools and languages. Leave the word huge and consider thinking about it. We have a large community support too.

> 
> Like I said before, structuring projects is an intensely personal choice. It will even vary from architect to architect. For example, I don't agree with half the things in that video, that is simply not how or why I would do something.

For this I would say, I want to learn from you, so that a combined and better solution could be proposed. I would like to know how, why and in what way you would structure your own project. I want to know how can I learn from you.

**Comment by sujayvsarma** [comment]
This is not the place for it.

And what you are asking for is not Microsoft's charter. The team has far more important things to attend to. Creating documentation is a very costly (time, effort) exercise. I would prefer the folks at Microsoft concentrate their time and effort on improving documentation for existing frameworks, languages, APIs, etc rather than do this sort of thing.

**Comment by PradeepSinghMakwana** [comment]
@sajayvsarma

As this repo is opensource, not completely proprietary. I would leave this issue opened. But from business point of view currently, it's not good to expect microsoft to do such a thing. I think this issue should not be in microsoft/dotnet but in an independent dotnet (that simply doesn't exist till now).

**Comment by sujayvsarma** [comment]
"proprietary" has nothing to do with being "open source". Open source simply means the source code is open for people to see and so on. You can still have proprietary content in something that is open source. For example, all of .NET's source is proprietary to Microsoft -- if you attempt to copy it all, build your own libraries and attempt to pass it off as your own, you will find out.

Leaving this item opened or closed is up to you and who ever has the authority to close items here.


---------------------------------------------------

Sujay Sarma



________________________________
