### ISSUE TITLE
Ubuntu 18.04 repo is not working as expected

### ISSUE THREAD

**Issue by lord-kyron** [microsoft/dotnet#1099]
I am trying to install dotnet-runtume latest for Ubuntu 18.04 as described on the official page, but I am getting this error after adding the repo:

`E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 13.74.252.37 443]
   Hashes of expected file:
    - Filesize:66619 [weak]
    - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
    - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
    - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
    - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000`

Can you please, check and fix the repo?

**Comment by miguelnge** [comment]
Similar problem here with pkg 'dotnet-sdk-2.2'. InRelease checksums doesn't seem to match the Packages files ones.
