### ISSUE TITLE
Desktop APP crashes with .NET 4.8

### ISSUE THREAD

**Issue by jitterbuffer** [microsoft/dotnet#1108]
I have updated my windows to Windows 10, version 1903 and .net framework 4.8. After upgrade when I run my wpf application on my machine, it gets crashed.
**My machine is 64 bit and the wpf application is 32 bit.**
It is a WPF based application built using .NET 4.5 and it consumes a C++ based library also. The app is working fine with .NET 4.7 framework but gives issue with .NET 4.8 only.

Below is the event viewer logs which we got after our application got crashed "XYZ.exe"

=== Application Error (9/6/2019 10:00:01 AM)
Faulting application name: xyz.exe, version: 7.3.0.402, time stamp: 0x5bf3fdf0
Faulting module name: clr.dll, version: 4.8.3801.0, time stamp: 0x5cabfed2
Exception code: 0xc0000005
Fault offset: 0x000e58e5
Faulting process id: 0x275c
Faulting application start time: 0x01d564ad949b47c3
Faulting application path: C:\Program Files (x86) \xyz.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll

Report Id: 860f2394-15f2-44af-a7ed-af02c4593dca
Faulting package full name: 
Faulting package-relative application ID: 
=== .NET Runtime (9/6/2019 10:00:01 AM)
Application: xyz.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 708A58E5 (707C0000) with exit code 80131506.
=== Application Error (9/3/2019 8:21:45 AM)
Faulting application name: xyz.exe, version: 7.3.0.402, time stamp: 0x5bf3fdf0
Faulting module name: msvcrt.dll, version: 7.0.17763.475, time stamp: 0xba51b082
Exception code: 0xc0000005
Fault offset: 0x0008c0d4
Faulting process id: 0x3574
Faulting application start time: 0x01d56253d57367a6
Faulting application path: C:\Program Files (x86)\ xyz.exe
Faulting module path: C:\Windows\System32\msvcrt.dll
Report Id: 9b8ae8af-ed7a-4b1c-83f4-a75e017a1058
Faulting package full name: 
Faulting package-relative application ID: 
=== .NET Runtime (9/3/2019 8:21:44 AM)
Application: xyz.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 76A5C0D4
**Appreciate if someone can share optimal solutions.**

**Comment by jitterbuffer** [comment]
We can try to provide the crash dump files but will that help in identifying the issue ?
please load crash dump files at google drive location: 
https://drive.google.com/open?id=1KSUaMm7dGbzt_4SZG0h13DDWZ92cHHMk

**Comment by bertasoft** [comment]
Same problem with a windows service.

**Comment by vivmishra** [comment]
@jeffschwMSFT @NKarnam15

**Comment by jeffschwMSFT** [comment]
@jitterbuffer thanks for reporting this.  If possible, can we move this .NET Framework issue to VS Feedback?  That way we can transfer files (perhaps privately).

To help make this actionable we need a dump at the point of the crash.  Can you follow these stesp?

o	Download procdump from: https://download.sysinternals.com/files/Procdump.zip
o	Install procdump as the just-in-time debugger:
	mkdir c:\dumps (or wherever you want dumps to go)
	procdump -ma -i c:\dumps
o	Run the app, observe the crashing behavior, and verify that a dump has been written to c:\dumps
o	Uninstall procdump as the JIT debugger:
	procdump -u

Thanks

**Comment by jitterbuffer** [comment]
Hi @jeffschwMSFT ,

To create a full dump of the crash, we have already asked users to create following registry entries on their machine.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\xyz.exe]
"DumpCount"=dword:00000005
"DumpFolder"=hex(2):25,00,4c,00,4f,00,43,00,41,00,4c,00,41,00,50,00,50,00,44,\
  00,41,00,54,00,41,00,25,00,5c,00,43,00,72,00,61,00,73,00,68,00,44,00,75,00,\
  6d,00,70,00,73,00,00,00
"DumpType"=dword:00000002

I believe, this is equivalent to you what you are suggesting to achieve through crash dump. However, it looks easier to follow procdump steps suggested by you. So I am going to suggest these also to the users.

**Comment by jitterbuffer** [comment]
Hi @jeffschwMSFT ,

Posted issue on visual studio feedback, please see below url
https://developercommunity.visualstudio.com/content/problem/753983/desktop-app-crashes-with-net-48.html

**Comment by jeffschwMSFT** [comment]
Thanks @jitterbuffer, I can see the issue internally and is in the right place.  I am going to close this issue and track it via that item.
