### ISSUE TITLE
dotnet site

### ISSUE THREAD

**Issue by patricka2** [microsoft/dotnet#1120]
What is problem?
![66252864-6c8ad480-e76d-11e9-930e-01deb794ba2a](https://user-images.githubusercontent.com/46094177/66253423-02762d80-e775-11e9-8b9a-f9ef82e93ab1.png)

**Comment by patricka2** [comment]
cc: @richlander

**Comment by vivmishra** [comment]
@rowanmiller

**Comment by patricka2** [comment]
why? @rowanmiller

**Comment by rowanmiller** [comment]
I referenced this issue in the commit to fix the character, so GitHub automatically closes when the change is merged. It's running through the CI/CD pipeline, so it'll be live in ~10min.

**Comment by patricka2** [comment]
Thanks @rowanmiller

**Comment by patricka2** [comment]
I find 2 same problem in this page https://dotnet.microsoft.com/platform/free in "No licensing costs" and ".NET is open-source" paragraphs

**Comment by patricka2** [comment]
I find 2 same problem in this page https://dotnet.microsoft.com/platform/free in "No licensing costs" and ".NET is open-source" paragraphs @rowanmiller

**Comment by patricka2** [comment]
And I think it's  necessary to place a space before "GitHub" in this paragraph @rowanmiller 
![Untitled](https://user-images.githubusercontent.com/46094177/66426815-86534280-ea1f-11e9-888e-ff627bcc0757.png)

**Comment by patricka2** [comment]
And i see an additional "?" charterer in this paragraph @rowanmiller 
![Untitled](https://user-images.githubusercontent.com/46094177/66427005-fd88d680-ea1f-11e9-9091-8faf02623489.png)

**Comment by rowanmiller** [comment]
@patricka2 many thanks for pointing these out. I ran a search and found a couple of others too. Not sure how they got in, but should be all gone now.

**Comment by mairaw** [comment]
Thanks @patricka2. I've opened a PR for @rowanmiller to review that includes these and a few others I found.

**Comment by rowanmiller** [comment]
Thanks @mairaw! 

> Why did this happen? i think it's very mysterious.

I think this must have happened when we recently converted the site to ASP.NET Core Razor Pages (from MVC). I have no idea how or why that would have happened, but we moved a bunch of files around and I'm guessing something happened as part of that.

**Comment by mairaw** [comment]
That's what I've noticed too by looking at the history of the files. That's when the issue got introduced at least. Thanks for letting us know @patricka2!

**Comment by patricka2** [comment]
@rowanmiller I see 1 or 2 or 3 pixel between menu and menu border
![bordermenu](https://user-images.githubusercontent.com/46094177/68497182-34dde380-0269-11ea-9525-c081d784e454.png)

**Comment by rowanmiller** [comment]
@patricka2 thanks. I've opened an issue for us to fix it.

**Comment by patricka2** [comment]
This problem is still exist.

**Comment by patricka2** [comment]
This problem is still exist. @rowanmiller

**Comment by hawkmoth8** [comment]
@patricka2 
We have an open issue tracking this, you can see the details [here](https://github.com/dotnet/website/issues/1621). We will fix it when we get there.

**Comment by patricka2** [comment]
It's look repo that you mention is not public @hawkmoth8

**Comment by patricka2** [comment]
It looks mentioned repo is not public @hawkmoth8

**Comment by mairaw** [comment]
You're right @patricka2. That's a private repo.

**Comment by hawkmoth8** [comment]
@patricka2 yes.. sorry I forget it's a private repo... Anyway, we have an open issue there, I'll keep you posted for any updates.

**Comment by hawkmoth8** [comment]
@patricka2 the gap has been removed.
