### ISSUE TITLE
.NET Native 5.0 for UWP

### ISSUE THREAD

**Issue by hez2010** [microsoft/dotnet#1160]
.NET Core 2.2 has EOL for a while, however, there's still no .NET Native 5.0 for UWP.
What's wrong with UWP? I hope that .NET Native 5.0 for UWP can be supported as soon as possible.

If you are abandoning UWP just like what you did for Silverlight, please feel free to let us know, and we will switch to use other tech immediately, but you will let developers down again and they maybe no longer use any other Microsoft's in future.

**Comment by Noemata** [comment]
The non-answer is the new way of answering such questions, apparently.  No Microsoft staffer has rushed to defend any notion related to UWP being dead, so the answer is, UWP is dead.  At least the C# .Net Native compiler side of things and large portions of its current UI stack.

That might no play so well with U.S. DOD initiatives that are investing in the HoloLens 2, though I suppose that might work out if it's all C++ work.  For DOD folks that are reading this, you'd best stick to C++ if you want to get anything working on the HoloLens 2.

**Comment by HppZ** [comment]
@karelz

**Comment by karelz** [comment]
@HppZ I am not involved with UWP directly anymore -- perhaps @tommcdon can help here with official answer?

**Comment by HppZ** [comment]
support .NET 5.0 please @tommcdon

**Comment by HppZ** [comment]
> @HppZ I am not involved with UWP directly anymore -- perhaps @tommcdon can help here with official answer?

thanks

**Comment by jcbeppler** [comment]
@hez2010 CoreRT is dead and was replaced by an experimental project called NativeAOT. It is not official, no roadmaps and so on... 
Native compilation is definitely dead. As the only reason to use UWP is gone, I believe UWP is almost there too.
I recently tried programming with GTK, Glade (for UI in XML) and Vala (very similar to C#). A little bit hard in the beginning to understand the tools, but works quite well and compile to Native.

**Comment by themerror** [comment]
Now NativeAOT has finished its experiment, and it will be a part of .Net 7, so does Microsoft have plans to upgrade UAP Runtime?

**Comment by tommcdon** [comment]
The .NET library code that ships with the .NET native toolchain is regularly updated, including updates for security. If you are interested in tracking our .NET Native releases, please see - https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native2.2/README.md. 

We're also working with the Windows App SDK team. Windows App SDK is a set of libraries, frameworks, components, and tools that you can use in your apps to access powerful Windows platform functionality from all kinds of apps on many versions of Windows. It has support for both UWP and .NET 6. You may want to consider it if you have need or want to use the latest .NET APIs.
