### ISSUE TITLE
CPU fan distributes warm air throughout my room

### ISSUE THREAD

**Issue by Legends** [microsoft/dotnet#1161]
The following process appears and disappears constantly  and keeps my CPU spinning and therefore also my fan, which keeps me warm in these cold winter days.

Btw. I have a heating system where I live, so I don't need the cpu fan for distributing warm air throughout my room.

I didn't use VS the last 4 weeks.

![image](https://user-images.githubusercontent.com/966368/72683532-84962200-3ad8-11ea-9d59-eff4bf7e0b47.png)

**Comment by teo-tsirpanis** [comment]
The inconsistent casing suggests something fishy. Can you tell us the path of the process in question? You can do it by right-clicking and selecting "Properties" or "Open File Path".

**Comment by Legends** [comment]
I must admit, it is not constantly like this, but at the time I opened the issue, the scenario described above lasted for half an hour.

I will give an update next time it occurs...

**Comment by pharring** [comment]
I think that's the ngen service that typically runs after a .NET framework update. It's a background operation that, once it's finished, shouldn't run again. There should also be evidence in the Windows Event log.

**Comment by Legends** [comment]
I remember, that I looked up the execution path, but wan't sure of the name, but as you mention it, yes it is the `ngen` service.
This service takes a lot of time, it was at least 20min running my CPU on ~50%.
I don't like it, but if it is inevitable....

**Comment by Legends** [comment]
@teo-tsirpanis  `C:\Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe`

**Comment by teo-tsirpanis** [comment]
That's `ngen`. It compiles .NET assemblies to native code ahead of time. It usually runs after an update or the installation or first execution of a .NET program. Unfortunately AOT compilation is a computationally intensive process, but it should normally run only once per program.

Does it run all the time in your case i.e. every time your computer starts?
