### ISSUE TITLE
Issue with ActivatableClassId discovery

### ISSUE THREAD

**Issue by hez2010** [microsoft/dotnet#1166]
I followed the doc https://docs.microsoft.com/en-us/windows/uwp/networking/network-communications-in-the-background?redirectedfrom=MSDN#controlchanneltrigger-with-websockets and tried to write a background task using websocket communication, however, once I added Windows.Networking.Sockets.WebSocketKeepAlive as a background task entry point, it won’t build anymore.

```xml
<Extensions>
  <Extension Category="windows.backgroundTasks"
       Executable="$targetnametoken$.exe"
       EntryPoint="Windows.Networking.Sockets.WebSocketKeepAlive">
    <BackgroundTasks>
      <Task Type="controlChannel" />
    </BackgroundTasks>
  </Extension>
</Extensions>
```
Compile error:
```
error APPX0501: Validation error. error 80080204: App manifest validation error: Line 32, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="Windows.Networking.Sockets.WebSocketKeepAlive" without ActivatableClassId in windows.activatableClass.inProcessServer.
```

The compiler doesn’t recognize the built-in class Windows.Networking.Sockets.WebSocketKeepAlive(though it has been marked as Activatable in SDK) so that anyone who wanted to use websocket for background networking communication won’t get it work as expected.

An available workaround is to set the minimal target version to 10.0.15063.0, however, plenty of packages such as Windows Community Toolkit and all .NET Standard 2.0 packages have requirements of minimal target version 10.0.16299.0. Therefore, this workaround is not applicable.

Affected minimal target versions: 10.0.16299.0 – 10.0.18362.0.

Hope that it can be fixed soon.

A minimal repro:
[BugRepro.zip](https://github.com/microsoft/dotnet/files/4126392/BugRepro.zip)

**Comment by PierreVanvolsem** [comment]
Hi,
Is there any existing solution for this problem ?
I am also using .NET Standard 2.0 

Thanks for any advice !

**Comment by hez2010** [comment]
@PierreVanvolsem Hello, this issue has been fixed in the latest Windows 10 insider SDK.

**Comment by PierreVanvolsem** [comment]
@hez2010 Hi, 
Thank you for your response. What should I do to solve this problem?
I just installed the latest Windows 10 insider SDK. 

Thanks for any advice !

**Comment by hez2010** [comment]
You need to change the minimal SDK version to the latest one in your project property.
