### ISSUE TITLE
Bug in C# 8.0 compiler or .NET Core 3 run-time

### ISSUE THREAD

**Issue by wimvangool** [microsoft/dotnet#1186]
I've bumped into a strange issue that when I..

- Implement a generic interface with at least one generic type parameter, and...
- Add two generic overloads to that interface, where the type parameter constraint on the method's generic type parameter references the parent interface's generic type parameter, and...
- One of the overloads provides a default implementation...

...then when I try to call the interface's overload that provides the default implementation with a type parameter that satisfies all constraint, the compiler thinks it's fine, but the run-time throws a System.Security.VerificationException at the point of invoking the interface method.

For more explanation and a way to reproduce this error, [see my question on StackOverflow](https://stackoverflow.com/questions/60934443/bug-in-c-sharp-8-0-compiler-or-net-core-3-run-time).

**Comment by scalablecory** [comment]
It looks like Jon Skeet answered this question on StackOverflow, so I'm going to close this here. If you'd still like feedback or believe he was incorrect, please file an issue on the [dotnet/roslyn](https://github.com/dotnet/roslyn/) or [dotnet/runtime](https://github.com/dotnet/runtime/) repos.
