### ISSUE TITLE
System.Net.Http.HttpClient add virtual to SendAsync overloads to allow performant and testable code

### ISSUE THREAD

**Issue by lennybacon** [microsoft/dotnet#1187]
The `HttpClient` supports performance optimizations due to its overload of `SendAsync` with the `HttpCompletionOption` argument.

If I want to write testable code I inject a mock or dummy deriving from `HttpClient`. The base class (`HttpMessageInvoker`) defines `SendAsync(HttpRequestMessage, CancellationToken)` as virtual, so it can be overridden in the mock or dummy.  

The overloads of the `SendAsync` method in `HttpClient` are not specified as virtual, so currently one has to decide: Write testable **or** performant code.

It would be great if the overloads of the `SendAsync`  woyuld be declared `virtual`.

**Comment by scalablecory** [comment]
Mocking the invoker should generally be sufficient.

The `HttpCompletionOption` overloads are a very thin wrapper around the message invoker. They only specify if, after calling `HttpMessageInvoker.SendAsync()`, it should also call `HttpContent.LoadIntoBufferAsync()`.

This has already been discussed at length in https://github.com/dotnet/runtime/issues/14535, with the decision being to not make these virtual. If you believe there's more to add to that conversation, please open a new issue there on the [dotnet/runtime repo](https://github.com/dotnet/runtime/).
