### ISSUE TITLE
dotnet publish -c release, Memory too high

### ISSUE THREAD

**Issue by tanyo520** [microsoft/dotnet#1192]
dotnet publish  Memory too high, up to 100%,How can I analyze what causes.
![image](https://user-images.githubusercontent.com/5094034/78769587-2171a880-79c0-11ea-8f83-96f83d36765a.png)

**Comment by hs115488** [comment]
dotnet itself requires a high memory due to the graphics

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
