### ISSUE TITLE
Microsoft.NETFramework.ReferenceAssemblies: System.Configuration assembly has incorrect casing on disk

### ISSUE THREAD

**Issue by fluffynuts** [microsoft/dotnet#1194]
Whilst attempting to build a project against net20 on a Linux host, I found errors like this:

```
The type or namespace name 'ConfigurationManager' does not exist in the namespace 'System.Configuration'
```

Turns out the files unpacked at `microsoft.netframework.referenceassemblies.net20/1.0.0/build/.NETFramework/v2.0` include a `System.configuration.dll` instead of `System.Configuration.dll`. Changing the case on this file resolved my build issue.

I would have contributed a PR to fix this (it's a very minor change), but I'm not sure where as this repo (linked from https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/ as the project site) doesn't seem to contain any of the source required.

**Comment by leecow** [comment]
If you're still looking for this, check the dotnet/runtime repo. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
