### ISSUE TITLE
dotnet nuget push times out when nuget push doesn't

### ISSUE THREAD

**Issue by fluffynuts** [microsoft/dotnet#1199]
Not sure if this is the right place to report this, or if there's a more nuget-specific place, but I've recently moved tooling over from msbuild/nuget to just `dotnet` for my project at https://github.com/fluffynuts/PeanutButter

Part of that project's automation is to build and push all new packages to nuget.org. I noticed that the 30 second timeout I was giving wasn't working out so well, especially for larger packages, like `PeanutButter.TempDb.Runner`. `dotnet nuget push` timed out several times -- and, watching a bandwidth monitor, appeared to be using a lot less bandwidth to push than when I tried with nuget.exe, and had my package pushed in short order.

I'm happy to help trying to track this down -- please let me know if I can provide more info.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
