### ISSUE TITLE
Bug: dotnet build unable to load gzip index.json

### ISSUE THREAD

**Issue by summatix** [microsoft/dotnet#1200]
I'm running a NuGet server on S3 that gzips all content by default. In Visual Studio there are no problems. However, when I try to run `dotnet build` I'm receiving the error:

    error : Unable to load the service index for source
    The content at '...' is not a valid JSON object
    Unexpected character encountered while parsing value: . Path '', line 0, position 0.

It seems nuget is unable to understand how to uncompress the data. The headers for `index.json` are:

    $ curl -I https://.../index.json
    HTTP/2 200
    server: nginx
    content-type: application/json
    content-length: 473
    accept-ranges: bytes
    cache-control: no-cache
    content-encoding: gzip, aws-chunked

Since the headers being sent include `gzip`, I expect nuget to be able to understand how to uncompress the data.

**Comment by summatix** [comment]
I've confirmed that it is the gzip compression that's the culprit because when I put a proxy in front of S3 that decompresses the content the command works

**Comment by leecow** [comment]
Looks like this is resolved. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
