### ISSUE TITLE
WinForms and WPF links in data grid cells become practically invisible when their containing row is highlighted

### ISSUE THREAD

**Issue by guybark** [microsoft/dotnet#1202]
Create a WinForms DataGridView with a DataGridViewLinkColumn, or a WPF DataGrid with a DataGridHyperlinkColumn, using .NET Framework 4.8. Define the UI such that you can arrow to a row in the grid, the whole row becomes highlighted. Notice that when a row is highlighted, cells containing static text show light-on-dark text, and that text still has a high contrast against its background. The text in the link cell remains blue and is practically invisible against its now-blue highlighted background. 

Perhaps the link text and its underline could become the same color as the static text when the row is highlighted? The link text would be differentiated from the static text due to the underline. (When a Windows high contrast theme is active, some color from that theme would need to be used for the link text, and that's a little more challenging given that there's no "selected link background" in the theme.)

The images below show the blue link text on a blue background for the WPF and WinForms data grids.

![WinFormsLink](https://user-images.githubusercontent.com/14315611/81740632-20fe7e80-9452-11ea-8da9-87fa831e823a.jpg)
![WPFLink](https://user-images.githubusercontent.com/14315611/81740634-21971500-9452-11ea-9b7b-21bd3a1f7f9e.jpg)

**Comment by merriemcgaw** [comment]
Was this issue Framework or Core (or likely both)?

**Comment by guybark** [comment]
I was using .NET Framework 4.8 for both the WinForms and WPF apps.

**Comment by Vino-Wang** [comment]
Have filed a Winforms runtime GitHub issue https://github.com/dotnet/winforms/issues/3626 and a VS bug for 4.8 servicing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1160349/?triage=true to track this problem.

**Comment by merriemcgaw** [comment]
@jamshedd I'm closing this issue since it's been copied into the correct locations. We've now got it on our backlog.
