### ISSUE TITLE
dotnet publish fails because dll is being used by another process

### ISSUE THREAD

**Issue by camerontbelt** [microsoft/dotnet#1205]
I understand this may be intended, but this is really messing up my release pipeline. Its hit or miss on whether it will publish or just fail because my web project dll is being used by IIS. Ive tried stopping the site in IIS and this does not work. 

A possible solution I see is to have a flag that just forces dotnet to copy regardless of a file being used by another process (internally I could see it finding and killing said process, but you guys figure that out). If you already have a flag or work around to this problem please let me know.

**Comment by PieterjanDeClippel** [comment]
I'm occasionally having the same issue when publishing to my Plesk using Web Deploy. I think in my case this only happens when switching from pc.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
