### ISSUE TITLE
`dotnet pack` with nuspec file: package layout is different between Linux and Windows

### ISSUE THREAD

**Issue by ranjak** [microsoft/dotnet#1208]
Hi,

We have a csproj that we are packing with a nuspec file.

We have files in a "content" folder that we want to copy into the package's own "content" folder, so we have the following in the nuspec file:
```
  <files>
    <file src="content/**/*.*" target="content" />
  </files>
```
We expect the resulting package to have the files from our source "content" folder directly under its own "content" folder, like so: `<package root>/content/<files under src content>`.

We use `dotnet pack` to create the package.
However, we have noted there is a different behavior when running `nuget pack` under Windows vs. under Linux (Ubuntu) in our case:

- On Linux, the files inside the source content folder are copied directly into the content folder of the package: `<package root>/content/<our files are here>`
- On Windows, a second "content" folder is created under the root content folder: `<package root>/content/content/<our files are here>`.

If we remove the "target" attribute in the nuspec "file" element, like so:
```
  <files>
    <file src="content/**/*.*" />
  </files>
```
We observe the following package structure:

- Linux: `<package root>/<our files are here>`
- Windows: `<package root>/content/<our files are here>`

We expected the package to have the same layout between Linux and Windows, but as you can see it is not the case. Is this behavior expected? Can we work around it to have the same behavior on both platforms?

Thanks in advance.

**Comment by ranjak** [comment]
It turns out the issue stems from using `/` instead of `\` in the `file` element.
With the following:
```
  <files>
    <file src="content\**" target="content" />
  </files>
```
Everything works as expected on both platforms.

Am I right in thinking that `/` should not be used at all in nuspec files? Is this a bug?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
