### ISSUE TITLE
Developer Certificates not functional in `5.0.100-preview.4.20258.7`

### ISSUE THREAD

**Issue by danielcrenna** [microsoft/dotnet#1212]
I'm no longer able to successfully create a new ASP.NET Core Web Application, or run any existing one, due to the dev-cert being missing. 

Every attempt, I'm prompted to install the developer certificate, and each time after I accept the certificate, I receive an `InvalidOperationException`: `Unable to configure HTTPS endpoint`.

I tracked this down to a failure of the `dev-certs` dotnet global tool:

![image](https://user-images.githubusercontent.com/129610/83786482-bb706d00-a660-11ea-9e81-e80a8a704b52.png)

There are no certificates installed in Personal, or Trusted Root Certification Authorities, named localhost or otherwise being related to ASP.NET Core:

![image](https://user-images.githubusercontent.com/129610/83787221-76006f80-a661-11ea-8cc3-46d92b5eedf3.png)

- I have tried running with elevated privileges.

**Comment by danielcrenna** [comment]
Here is the same computer after uninstalling `5.0.100-preview.4.20258.7` and using the previously installed `3.1.400-preview-015151`

![image](https://user-images.githubusercontent.com/129610/83788177-ccba7900-a662-11ea-9a34-10a49a257cc3.png)

**Comment by danielcrenna** [comment]
- I uninstalled the preview release, rolled back to the previous SDK, and cleaned/re-issued the localhost certificate.
- I reinstalled the preview release.
- Running localhost apps now will show the untrusted certificate error warnings in the browser.

![image](https://user-images.githubusercontent.com/129610/83789141-4e5ed680-a664-11ea-8aec-b644f46e0c90.png)

This makes sense if the keys change between SDKs, but there is no way for me to generate a certificate based on the preview SDK, per the error above.

**Comment by leecow** [comment]
5.0 GA shipped so this may no longer be an issue. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275).
