### ISSUE TITLE
FileStream always locks a file

### ISSUE THREAD

**Issue by HalfLegend** [microsoft/dotnet#1216]
I am writing a Log Analyzer with C# on Mac.
The log file is writing by another software and I am trying to use my Log Analyzer to read the same file at the mean time.
The file could be opened by VS Code, and I can also open it by C++ code.
But I cannot open it by C# code,
``` C#
            using FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
```
I tried FileShare.ReadWrite, FileShare.Delete, FileShare.Read, FileShare.None, they all doesn't work.
Finnally I find out the reason:
``` C#
// in FileStream.Unix.cs
        private void Init(FileMode mode, FileShare share, string originalPath)
        {
            _fileHandle.IsAsync = _useAsyncIO;

            // Lock the file if requested via FileShare.  This is only advisory locking. FileShare.None implies an exclusive 
            // lock on the file and all other modes use a shared lock.  While this is not as granular as Windows, not mandatory, 
            // and not atomic with file opening, it's better than nothing.
            Interop.Sys.LockOperations lockOperation = (share == FileShare.None) ? Interop.Sys.LockOperations.LOCK_EX : Interop.Sys.LockOperations.LOCK_SH;
            if (Interop.Sys.FLock(_fileHandle, lockOperation | Interop.Sys.LockOperations.LOCK_NB) < 0)
            {
                // The only error we care about is EWOULDBLOCK, which indicates that the file is currently locked by someone
                // else and we would block trying to access it.  Other errors, such as ENOTSUP (locking isn't supported) or
                // EACCES (the file system doesn't allow us to lock), will only hamper FileStream's usage without providing value,
                // given again that this is only advisory / best-effort.
                Interop.ErrorInfo errorInfo = Interop.Sys.GetLastErrorInfo();
                if (errorInfo.Error == Interop.Error.EWOULDBLOCK)
                {
                    throw Interop.GetExceptionForIoErrno(errorInfo, _path, isDirectory: false);
                }
            }

```
A lock is always there, no matter what FileShare is. 
The only difference is a exclusive lock or a shared one.
But I don't really need the lock. 
This blocks me a lot.

I cannot even write a log file tracker on Mac by C# using dot.net
I cannot even tail -f a file by C#....
This could be done easily by C++ or even by js code...
I cannot even believe that...

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
