### ISSUE TITLE
Could you please rename master branch and remove problematic words?

### ISSUE THREAD

**Issue by ghost** [microsoft/dotnet#1217]
Many projects have done the same in an effort to make black people feel more comfortable in tech.
Words such as master, slave, blacklist, whitelist etc are not precise and have a deep racist history associated with them.

Would you please remove them from the projects?

I don't know who to contact at MS to tell them about doing this for every project. Hopefully someone does this.

PS - Historical context for main - https://www.nakasendoway.com/the-japanese-family-system/

Please consider alternatives such as canary, develop or edge.

**Comment by RTSTALER** [comment]
@blacklivesmatterplease  Bullshit, stop doing this. You look funny

**Comment by leecow** [comment]
Thanks @ghost. We have efforts underway to do exactly this (I believe 'main' will generally be the replacement). We're working with GitHub on the effort but I don't have an exact target for when the work is expected to be complete.
