### ISSUE TITLE
.NET Core fails to convert System.Uri to Windows.Foundation.Uri

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/dotnet#1219]
Not sure if this is the right place where to report this issue, but it's kinda nice:
The following is a completely valid URI in .NET but it seems to crash when implicitly getting converted to the WinRT counterpart (when being passed to some UI component, by example):
`file:///C:\Users\Fela\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState\0\animations\}%008$1K7{Q}YCA}0{OKSYH.gif.mp4`

The attempt results in a `InvalidArgumentException`.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
