### ISSUE TITLE
Unable to publish/deploy the azure function solutions

### ISSUE THREAD

**Issue by bojjaiah** [microsoft/dotnet#1231]
We have a **Azure Function** which is built in **.Net Framework 4.6** and recently we have updated the **Azure Functions** with **.Net Framework 4.8** which works good in locally. So we tried to publish this to Live by going to select the existing **Azure Function**

![Publish](https://user-images.githubusercontent.com/10813738/87388018-8c370f00-c5c1-11ea-8c03-74aa48a144ac.PNG)

But we are unable to publish due to below error (**Publish has encountered an error**).

![Publish-Error](https://user-images.githubusercontent.com/10813738/87388046-9fe27580-c5c1-11ea-81b8-0b9e057f4fe3.PNG)

Can you please suggest me If I missed any **settings/configuration**.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
