### ISSUE TITLE
Add SameSite and MaxAge properties System.Net.Cookie

### ISSUE THREAD

**Issue by tmenier** [microsoft/dotnet#1232]
`System.Net.Cookie` contains [properties](https://docs.microsoft.com/en-us/dotnet/api/system.net.cookie?view=net-5.0#properties) that correspond one-to-one with attributes of the `Set-Cookie` header, per the latest spec, with exception of 2:

- `Max-Age`
- `SameSite`

Why would you want these in a client context? Hopefully completeness is a good enough reason; these are all that's missing from a 100% complete strongly-typed representation of a `Set-Cookie` header. Another possible use case is (re)hydrating a `CookieContainer` based on values saved from raw response headers.

(Not to be confused with #593 - a few comments down it's clear that refers to a different set of APIs.)

**Comment by okarpov** [comment]
so how to set/get SameSite property?

**Comment by Const24** [comment]
I need this (

**Comment by danmoseley** [comment]
Thanks for the ask. This is a request for the dotnet/runtime repo.
