### ISSUE TITLE
Latest .Netframework version in app service console is still 4.7.2 when it will update to 4.8?

### ISSUE THREAD

**Issue by DkAmarnath** [microsoft/dotnet#1233]
Please let us know what date we will get 4.8 in app service console.

**Comment by kanebarton** [comment]
Unfortunately the Azure team will not be able to provide an exact date for your App Service. The general guidance is somewhere between July 14, 2020 and by September 15, 2020. For sovereign clouds the update will start on August 11, 2020 completing by October 15, 2020.

**Comment by DkAmarnath** [comment]
Thanks for the update.
