### ISSUE TITLE
error with objects

### ISSUE THREAD

**Issue by resinate** [microsoft/dotnet#1238]
this is precompiled outside of pc, tool worked before windows 2004 update.

https://pastebin.com/qgiTR14i

this is line src 
bool firstRun = Program.ConfigurationManager.ApplicationSettings.FirstRun;

says lib returns null.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
