### ISSUE TITLE
`dotnet new ...` hangs up for a minute after completing local work

### ISSUE THREAD

**Issue by fluffynuts** [microsoft/dotnet#1239]
I've notices this with `dotnet new console` and `dotnet new sln`: after all local files appear to have been created, dotnet.exe hangs about for a while before exiting -- a minute or more. Here's a screenshot of Process Explorer process details from the last time I ran `dotnet new sln`:

![image](https://user-images.githubusercontent.com/4669340/88483757-4fc4c500-cf6a-11ea-9553-aad27cf07132.png)

Of concern is the amount of network traffic for creating a single, small, .sln file -- dotnet received over a mb of data... for what?

For reference, I have set `$env:DOTNET_CLI_TELEMETRY_OPTOUT=1` before this last run, so one would hope that there's nothing telemetry-related in there (and even if there were, it wouldn't explain a mb of _download_ during .sln creation).

When I created a new console project, the same kind of hang-up occurred, with the dotnet process sitting there for a while after claiming to have completed package restore. So, what gives? These operations used to be lightening fast, though admittedly the last time I did a `dotnet new ...` was a while a go (read: months)

Operating system: windows 10 (version 2004) x64
dotnet version: 3.1.302

**Comment by sdrik** [comment]
I'm experiencing the exact same issue since a few days.

**Comment by sdrik** [comment]
Maybe related to https://github.com/dotnet/templating/pull/2341 ?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
