### ISSUE TITLE
Text output to more freezes console

### ISSUE THREAD

**Issue by perjahn** [microsoft/dotnet#1241]
This simple .net application freezes the host console, when using bash (term) in ubuntu 20.04, dotnet core 3.1.302, and running with:

dotnet run | more

(running the application binary, piped to more, doesn't cause any problem)

```
using System;
namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 10000; i++)
            {
                Console.WriteLine("Hello World!");
            }
        }
    }
}
```

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
