### ISSUE TITLE
Cannot Have Nullable Return of Async Generic Method

### ISSUE THREAD

**Issue by mysteryx93** [microsoft/dotnet#1249]
With C# 8 Nullables, you can define a nullable generic like this

    [return: MaybeNull]
    public T Get<T>() => default;

However, I'm running into a problem with a Generic Async method.

    [return: MaybeNull]
    public async Task<T> GetAsync<T>() => default;

This would tell that Task is nullable, not T.

The only solution for now would be to add ! after default, but then the IDE will wrongly indicate to the users that the type is not null when it can be. This can work for private use (and can easily lead to errors), but not for a public API.

Is there any other solution?

Actually what I'd really need is a generic constraint "where T : nullable" because I need to document to pass in nullable types.

Currently, the only way of doing so is to have 2 copies, one with "where T : class" and one with "where T : struct", and using T? where ? is interpreted differently in each copy (Nullable<T> vs nullable attribute). That can lead to doubling a lot of code.

**Comment by mysteryx93** [comment]
Since there has been no response, here's my take on this.

The .NET team could fix it in 2 ways.

1. Add a "nullable" constraint

2. Tweaking MaybeNull attribute to work in the above case


_On a different topic_, a 3rd suggestion to help working with Generics

    if (typeof(T) == typeof(JsonElement))
    {
        return (T)(object)doc.RootElement;
    }

This works but has unnecessary boxing/unboxing.

The compiler should recognize this as valid IMO

    if (typeof(T) == typeof(JsonElement))
    {
        return (T)doc.RootElement;
    }

**Comment by kalaskarsanket** [comment]
This issue was moved to dotnet/csharplang#4231
