### ISSUE TITLE
Publish "dotnet-install.ps1" into the PowerShell Gallery

### ISSUE THREAD

**Issue by KirkMunro** [microsoft/dotnet#1252]
Have you considered publishing your dotnet-install.ps1 script into the PowerShell Gallery? The PowerShell Gallery supports scripts as well as modules, with support for versioning and updating installed scripts as well. I think having that PowerShell script published in the PowerShell Gallery would be a much better way to distribute it to PowerShell systems where it is needed, especially since PowerShellGet is included by default in PowerShell and Windows PowerShell.

**Comment by mairaw** [comment]
@bozturkMSFT can you take a look at this feedback?

**Comment by kalaskarsanket** [comment]
This issue was moved to dotnet/core#5715
