### ISSUE TITLE
How to run NET5 App on Android ?

### ISSUE THREAD

**Issue by SasukeK93** [microsoft/dotnet#1253]
I compiled a Hello App using Net SDK 5.0.100-rc.1 targeting Android-ARM 👍 

dotnet publish --configuration Release --runtime android-arm

But how to run my app on my phone ?
There's any NET Runtime for Android-ARM yet ?

**Comment by mairaw** [comment]
@davidortinau @jamesmontemagno can you help with this question?

**Comment by davidortinau** [comment]
Hi @SasukeK93, until .NET 6 you'll want to continue using .NET Framework/Mono to target Android. .NET 5 may "work" by virtue of work we have done in preparation for .NET 6, but it doesn't have support for AOT, linker, crypto, and other features needed for most mobile applications. That work is coming in .NET 6.
