### ISSUE TITLE
Memory leak on UWP with target versions 10.0.17763.0, 10.0.18362.0 and 10.0.19041.0 

### ISSUE THREAD

**Issue by DanieleScipioni** [microsoft/dotnet#1254]
In an UWP application when I set TargetPlatformVersion and TargetPlatformMinVersion to 10.0.17763.0, 10.0.18362.0 or 10.0.19041.0 (I keep them always aligned) I found that pages are not released from memory causing serious issues, as the application memory usage quickly grows up. 

This GitHub repo contains the code that reproduce the problem https://github.com/DanieleScipioni/MemoryLeak, this a basic application with 2 pages. You can just go from the first page to the second, the second page contains a ListView of ListViews with an ItemClick event handler.

```
<Page x:Class="MemoryLeak.Views.ListsPage">
    <Grid>
        <ListView IsItemClickEnabled="True"
                  CanReorderItems="False"
                  ItemsSource="{x:Bind _secondPageViewModel.List, Mode=OneWay}">
            <ListView.ItemsPanel>
                <ItemsPanelTemplate>
                    <ItemsStackPanel Orientation="Horizontal" />
                </ItemsPanelTemplate>
            </ListView.ItemsPanel>
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="local:StringList">
                    <ListView ItemsSource="{x:Bind}"
                              ItemClick="ListView_OnItemClick"
                              IsItemClickEnabled="True"/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </Grid>
</Page>
```

To see the memory leak is enough to go forward and back from the 2 pages, and see memory increasing on the Task Managed, anyway I used Visual Studio Diagnostic Tool. 

With Visual Studio Diagnostic Tool I execute this test: open app, go to next page, go back and take a snapshot, again go to next page, go back and take a another snapshot, then stop data collection and compare the 2 snapshots. GC is started several time before of each snapshot.

With TargetPlatformVersion 10.0.19041.0, there are 205 more objects in the second snapshot

![2004_with_eventhandler_overview](https://user-images.githubusercontent.com/28003116/94539249-48a98400-0245-11eb-9c74-83f37780ab11.png)

and looking at count diff and at paths to root I see this

![2004_with_eventhandler_paths_to_root](https://user-images.githubusercontent.com/28003116/94539498-9625f100-0245-11eb-9b24-7f58648180e7.png)

So at the end ListsPage is not released from memory.

The behavior must be that both count and count diff is 0, meaning that ListsPage is released from memory.

**Comment by kalaskarsanket** [comment]
@DanieleScipioni kindly send all the UWP issues to dotnetnative@microsoft.com as we have changed the issue monitoring mechanism.
