### ISSUE TITLE
.Net 5 self-contained single file no working.

### ISSUE THREAD

**Issue by kyuranger** [microsoft/dotnet#1256]
The Visual Studio version I am using is Version 16.8.0 Preview 3.2.

The SDK version I am using is 5.0.100-rc.1.20452.10 .

I create a brand new .Net 5 WPF project and don't add or modify any code, just a brand new default project.

Now I publish it with single file and self-contained by Visual Studio.

However, after I published it and run the program, there is nothing(either not render any window or report any error).

What's wrong with it? I don't know how to debug or catch this problem.

**Comment by leecow** [comment]
Please give it a try with the final release available at https://dotnet.microsoft.com/download. If you're still having an issue. Please open a new issue at [dotnet/runtime](https://github.com/dotnet/runtime/issues).
