### ISSUE TITLE
.NET 5.0 RC2 - self-contained build on Linux - version missing in generated file

### ISSUE THREAD

**Issue by rasmk** [microsoft/dotnet#1258]
When I build a self-contained app on Linux (in a Docker container), targeted to win-64, the generated exe file misses version, copyright, and other information. When built on Windows, the information is built into the exe file as expected.

See screenshot: left side is macOS build, right - Windows build.
![image](https://user-images.githubusercontent.com/12119107/95966797-da9bba00-0e0b-11eb-8274-fcdd147ef6b5.png)

My build task in VS Code is

```json
        {
            "label": "publish - windows, self-contained",
            "command": "dotnet",
            "type": "process",
            "args": [
                "publish",
                "-c",
                "release",
                "-r",
                "win-x64",
                "-p:PublishSingleFile=true",
                "-p:UseAppHost=true",
                "--self-contained",
                "true"
            ],
            "options": {
                "cwd": "${workspaceFolder}/MessageBroker",
            },
            "problemMatcher": "$msCompile"
        },
```

**Comment by kalaskarsanket** [comment]
Since this issue was with RC2, closing it for now. If you experience the same issue with .NET 5.0 GA kindly raise the issue with [dotnet/runtime ](https://github.com/dotnet/runtime/issues).
