### ISSUE TITLE
HashAlgorithm.ComputeHash method is much slower in .NET Framework environment than .NET Core environment

### ISSUE THREAD

**Issue by sonupmandal** [microsoft/dotnet#1259]
When i run the below sample code in both .NET framework and .NET core environment, I can see ComputeHash method is consuming almost 7 to 10 times more time in .NET framework than .NET core.

Time Taken by  **.NET Framework 4.6.1 sample app** = 00:00:06.3603452

Time Taken by **.NET Core 2.2 sample app** = 00:00:00.6868439

Sample Code is below.

```
using System;
using System.Security.Cryptography;
using System.Text;
using System.Diagnostics;

namespace Conn
{
    class Perf
    {
      static void Main(string[] args)
       {

        HMAC m_algorithm = new HMACSHA512(Encoding.UTF8.GetBytes("Hello_World"));
        byte[] inputBuffer = { 0, 0, 0, 1 };
        byte[] input = Encoding.UTF8.GetBytes("Debugging_Performance_Issue");

        m_algorithm.TransformBlock(input, 0, input.Length, input, 0);
        m_algorithm.TransformFinalBlock(inputBuffer, 0, inputBuffer.Length);
        m_algorithm.Initialize();

        byte[] hashValue = m_algorithm.Hash;

        // Start the timer
      Stopwatch sWatch = new Stopwatch();
      sWatch.Start();

        // Loop for the number of iterations required.
        for (int i = 2; i <= 409600; i++)
        {
          // Get hash value for next iteration.
          hashValue = m_algorithm.ComputeHash(hashValue);
        }

        // Stop the timer
      sWatch.Stop();
      TimeSpan ts = sWatch.Elapsed;

      Console.WriteLine("Time Taken = " + ts);
      }
    }
  `}`

```

**Comment by pharring** [comment]
Nit: Please change your sample code to use `System.Diagnostics.Stopwatch`  for timing instead of `DateTime.Now`? (Just to eliminate it from the future discussion)

**Comment by sonupmandal** [comment]
code changed.

**Comment by kalaskarsanket** [comment]
While we are continuing to support .NET Framework we are not looking at performance improvements now. Did you also try with newer version of .NET Framework ? 

We are also changing how issues get reported, for any issues kindly follow repository instructions as mentioned [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
