### ISSUE TITLE
Add Task.WaitAll(IList<Task>)

### ISSUE THREAD

**Issue by briangru** [microsoft/dotnet#1262]
Help me avoid an extra allocation.  Why do I need to call .ToArray on a list of tasks when calling WaitAll?  Here's a common pattern:

            List<Task> insertItems = new List<Task>();
            try
            {
                foreach(var carState in carStates)
                {
                  var insert = ...
                  Task task = _azureTable.ExecuteAsync(insert);
                  insertItems.Add(task);
                }

                Task.WaitAll(insertItems.ToArray());

Sometimes I need to do this operation under a lock, making this pattern more of a perf problem.
Hopefully Stephen and company can come through with a minor API change quickly.  Other devs came up with this worse approach.

                Task.WhenAll(insertItems).ConfigureAwait(false).GetAwaiter().GetResult();

or a more elegant reading but more complicated approach:

                await Task.WhenAll(allTasks);

I can't imagine the latter two being as cheap as a properly implemented WaitAll.

**Comment by kalaskarsanket** [comment]
@briangru is the issue still reproducible ? If so, is this .NET Framework or .NET Core ?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
