### ISSUE TITLE
.NET 5 WPF application single file publishing error

### ISSUE THREAD

**Issue by HenJigg** [microsoft/dotnet#1267]
![image](https://user-images.githubusercontent.com/42528522/98894719-5ad33f00-24e0-11eb-9c5f-2b96c819919a.png)

Use Visual Studio to debug normally, and Debug also runs normally. I want to confirm what caused this exception. Where can I view it?

When creating a blank WPF application and publishing it, everything runs normally. It is most likely due to the nuget package in the project, or some aspect of the code. What I want to be sure is, if I find where the problem is?

**Comment by kalaskarsanket** [comment]
This issue was moved to dotnet/wpf#3886
