### ISSUE TITLE
Officially Rename .NET brand to dotnet

### ISSUE THREAD

**Issue by OnurGumus** [microsoft/dotnet#1269]
Recently **dotnet** is more and more used interchangeably with  .NET. But this causes some confusion since all the tooling and command line using the word **dotnet**. 

I purpose officially renaming .NET brand to dotnet. This conversion would also mitigate the problem with search engines as dotnet is really specific about programming whereas.NET also refers to a top-level domain name.

**Comment by Jaiganeshkumaran** [comment]
Please don't.

**Comment by leecow** [comment]
Thanks for your thoughts, @OnurGumus. Names can be tricky and we're far enough along with the current product and ecosystem that a change would be extremely disruptive.

**Comment by JaiganeshKumaran** [comment]
> Please don't.

Actually do. Writing .NET as the first word of a new sentence following a full stop is extremely ugly.
