### ISSUE TITLE
System.Diagnostics.Process.WorkingSet64 is static value in .Net Core 3.1

### ISSUE THREAD

**Issue by ChristianKern97** [microsoft/dotnet#1277]
I'm using the WorkingSet64 endpoint to measure the RAM usage of multiple processes with my application, this worked fine, but for some reason it stopped working as it should and it only returns a static value, which is different for different processes but it is not updating. 
I only get this issue on Windows 10 with the newest updates. On my Windows Server 2019 everything works just fine. I tried using a PerformanceCounter instead but it had the same behaviour.
Another thing i tried is using .NET 5.0 but the same behaviour there.

My best guess is it has something to do with a recent Windows 10 update, but i have no clue.

**Comment by kalaskarsanket** [comment]
This issue was moved to dotnet/runtime#46050
