### ISSUE TITLE
Converge on one concept and set of APIs for "stuff packed with dlls"

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/dotnet#1278]
In the spirit of https://themesof.net/ it would be nice if the resource story in .net converged on one idea. 

 - I'm always unsure as to which is the right one to pick and official docs don't clearly spell out which to use.
 - I'm not sure which APIs for accessing the embedded resources are the right to use or what kind of lifecycle and caveats I must observe

---

An internet search will result in this question popping up over the years.  [Here's one](https://stackoverflow.com/questions/1934826/whats-the-difference-between-a-resource-and-an-embedded-resource-in-a-c-sharp-a) and you can see that the answers have a difficult time being direct.  Just references to MS docs which don't really offer clear direction.

**Comment by kalaskarsanket** [comment]
This issue was moved to dotnet/runtime#46049
