### ISSUE TITLE
Build behaves diffrent in Visual Studio and dotnet cli on missing References to Projects missing in Solutions

### ISSUE THREAD

**Issue by lippinio** [microsoft/dotnet#1280]
Use the following structure to reproduce the issue or download the zip file.

C:.
│   A.sln
│   AB.sln
│
├───A
│       A.cs
│       A.csproj
│
└───B
        B.cs
        B.csproj

AB.sln
`
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "B", "B\B.csproj", "{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "A", "A\A.csproj", "{4897A731-C11F-4F0D-8D54-131CD74D27B5}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{3C50BE2E-9F33-4B3A-AB0E-17E8B5DDE678}.Release|Any CPU.Build.0 = Release|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4897A731-C11F-4F0D-8D54-131CD74D27B5}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
`

A.sln
`
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "A", ".\A\A.csproj", "{E00D4674-C975-4774-BA72-CB15A30A657E}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{E00D4674-C975-4774-BA72-CB15A30A657E}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
`

A.csproj
`
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\B\B.csproj" />
    </ItemGroup>
</Project>
`

B.csproj
`
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
</Project>
`
A.cs
`
namespace A
{
    public class A {B.B b = new B.B(); }
}`

B.cs

`
namespace B
{
    public class B   { }
}`
Or download Code from zip

[AB.zip](https://github.com/microsoft/dotnet/files/5715896/AB.zip)

If you try to build A.sln in Visual Studio it fails with: `CSC : error CS0006: Metadata file 'C:\development\referencefail\B\bin\Debug\net5.0\ref\B.dll' could not be found`
 If you use dotnet build a.sln it succeeds.

The problem with this differentce is developes can break sub solutions from other developmentteams if they add references but forget to add the project in the full solution and it passes CI Builds. 

It sould either fail in both cases or suceed in both cases.

**Comment by leecow** [comment]
This issue was moved to dotnet/sdk#15172
