### ISSUE TITLE
Self-Contained Single-File Win Form app does not run

### ISSUE THREAD

**Issue by jwu-dharmo** [microsoft/dotnet#1285]
I am on VS 2019 16.8.3 with .Net 5.0.

I have created a simple Win Form project without any NuGet or project dependency.  I have made sure it runs out of the IDE.

When I published the project to a self-contained single file exe, it does not run.  The Task explorer briefly showed the exe and switch it to suspended before killing it.  The exe worked fine after I republished it either without the single-file or the self-contained option.  It seems like both options cannot co-exist.

Any idea?

**Comment by leecow** [comment]
This issue was moved to dotnet/winforms#4437
