### ISSUE TITLE
ArgumentOutOfRangeException was thrown when creating DateTimeOffset for MinDate

### ISSUE THREAD

**Issue by ssaran046** [microsoft/dotnet#1304]
Please find the issue details here https://github.com/microsoft/ProjectReunion/issues/732.

**Comment by ssaran046** [comment]
Hi Team,

Any update on this?

**Comment by mairaw** [comment]
Issues are not reviewed here per https://github.com/microsoft/dotnet/issues/1275

Try filing at https://github.com/dotnet/runtime/issues.
