### ISSUE TITLE
Improve CLI experience when creating a new application

### ISSUE THREAD

**Issue by andrebaltieri** [microsoft/dotnet#1307]
Today we have a lot of templates and if you're starting on .NET is difficult to choose between them. Is also difficult to see what templates I can use... need to Google that.

If you're using Visual Studio, everything is more clear, the templates are organized and we have a GUI for that. But I think we have a lot of developers working through CLI, using VS Code.

The idea here is to have a global .NET command that show some selectable options on terminal, as Angular does when you start a new App.

For example `dotnet new` will show some questions to help me on creating my app.

```
dotnet new
  - Web application (ASP.NET/Blazor)
  - Mobile Application (MAUI)
  - Console Application
  ...
```

We can have more options after selecting the first one, and goes on. You got the idea.

Please, let me know if this make sense.

**Comment by svick** [comment]
Since this is specifically about the .Net SDK, I think you should close this issue here and reopen it at [the dotnet/sdk repo](https://github.com/dotnet/sdk).

**Comment by andrebaltieri** [comment]
Thanks!
