### ISSUE TITLE
Changelog for NuGet package Microsoft.NETFramework.ReferenceAssemblies?

### ISSUE THREAD

**Issue by YoshiRulz** [microsoft/dotnet#1308]
Sorry for opening an issue here, but this is the page listed for [`Microsoft.NETFramework.ReferenceAssemblies`](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/).

There's a [readme](https://github.com/microsoft/dotnet/blob/master/releases/reference-assemblies/README.md) in this repo for the reference assemblies package but it wasn't updated with the release of versions 1.0.1 or 1.0.2 earlier this month. Are the changes in these versions documented somewhere?

**Comment by mairaw** [comment]
@richlander @NikolaMilosavljevic do you know what's the process here and who owns updating the readme?

**Comment by NikolaMilosavljevic** [comment]
@mairaw I can update the readme.
