### ISSUE TITLE
RHBIN error, AppCenter and NoLinkerSymbols

### ISSUE THREAD

**Issue by premiaware** [microsoft/dotnet#1333]
UWP 6.2.12 (February 9th, 2021)

Error code RHBIND : error RHB0002: Failed to write PDB. Fix for build failures with RHBIN error when building Xamarin and SyncFusion UWP projects. This is an opt-in fix and requires customer to setting the msbuild property NoLinkerSymbols

I use SyncFusion Component in my UWP Project and for this reason is must use the NoLinkerSymbols during compilation. If i dont't use NoLinkerSymbols the store not working with error:

Submit error : L'invio non è riuscito con uno o più codici di errore 1201. More info about the error(s) can be found

Now i have need to use AppCenter for tracking the bugs of my App, but AppCenter not trace Stack if i use NoLinkerSymbols, so it is perfectly useless

how do you solve this thing? visual studio compiles correctly even without NoLinkerSymbols, but the store does not accept the app, it is possible that there are always problems with UWP.

**Comment by tommcdon** [comment]
Hello!  This sounds like an app store submission issue.  Please report the submission problem on https://partner.microsoft.com/support/.
