### ISSUE TITLE
My WPF project has a namespace error

### ISSUE THREAD

**Issue by 344089386** [microsoft/dotnet#1361]
Error Tip:
No type or namespace name "Windows" in namespace "test.wpf.system" (missing assembly reference?)

This error occurs when my project contains the System namespace.
I predict this is due to the implicit namespaces of.net6.
I tried `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` and `<Using Remove="XXX.System" />`  but it didn't work.

![image](https://user-images.githubusercontent.com/22017199/191935560-2c0b601d-507b-481b-921a-fd2807f9cca7.png)

Repeat steps：
build project

Error Code：
https://github.com/344089386/WpfTest

**Comment by RussKie** [comment]
Please raise WPF-related issues in https://github.com/dotnet/wpf.

> I tried `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` and `<Using Remove="XXX.System" />` but it didn't work.

This is not how implicit usings are enabled or disabled, refer to https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props#implicitusings.



> No type or namespace name "Windows" in namespace "test.wpf.system" (missing assembly reference?)

WPF (and other defaults) usings are described here: https://learn.microsoft.com/dotnet/core/project-sdk/overview#implicit-using-directives
