### ISSUE TITLE
RISC-V Support

### ISSUE THREAD

**Issue by archanox** [microsoft/dotnet#1380]
I know there are issues[1..] in the specific repos for RISC-V bring up, but I'm hoping that there's a meta issue to show the progress of the bring up.

What incentivised me to make this issue is that RISC-V International has asked its members if there is anything missing from their "Ecosystem Landscape", dotnet is one glaring omission.

https://lists.riscv.org/g/allmem/message/220

One of the stipulations is that there is

> Note that the submission form requires a link to a website/whitepaper/other proof of RISC-V support (existing, not just planned)

I'm lead to believe that several pieces have been merged and bring some support, but I haven't seen any evidence of RISC-V support outside of those pull requests.

Any help documenting the status and submitting an update proposal would be much appreciated.

1. https://github.com/dotnet/runtime/issues/36748
2. https://github.com/dotnet/runtime/issues/75749
3. https://github.com/dotnet/runtime/issues/84834

**Comment by danmoseley** [comment]
I'm going to move to the runtime repo since anything would start there.

**Comment by archanox** [comment]
@danmoseley yeah I was hoping to have a "meta" issue that overarches all the components of dotnet for the RISC-V platform, runtime, compiler, debugger etc etc

**Comment by archanox** [comment]
> There doesn't seem to be much interest in .NET open source IoT platforms, which is likely the target market for RISC-V at the moment.

I'd have to politely disagree with this sentiment 🙂 

I would suggest the nanoFramework would be more suitable for the domain you're interested in, which already has (some? all?) support for RISC-V.

With server grade RISC-V machines (rack mount 1U too) due out next month, having the full blown dotnet experience would be highly desirable. Including Dev and deployment.

**Comment by 0xStuart** [comment]
> I'd have to politely disagree with this sentiment slightly_smiling_face

Ah, well yeah I know its desirable.  It's just this was posted on Microsofts repo, and there doesn't seem to be much interest from Microsoft to support RISC-V right now.  Community efforts, which are showing signs of picking up, is slow.

There are some interesting low powered RISC-V SOC devises appearing, notably the BL808 which sit between MCUs and CPU's, which would be ideal for IoT, and full .NET (instead of nanoFramework).

**Comment by danmoseley** [comment]
> @danmoseley yeah I was hoping to have a "meta" issue that overarches all the components of dotnet for the RISC-V platform, runtime, compiler, debugger etc etc

Yep of course it's fine to continue here, just wanted to point out that the committer folks usually involved in this kind of discussion (like @jkotas) are all generally in the other repo.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/issues/36748 is currently the best place to track overall progress of the RISC-V .NET port and ask questions about it.
