### ISSUE TITLE
Wrong ObservableObject.SetProperty Method Description

### ISSUE THREAD

**Issue by PerfidusPistor** [microsoft/dotnet#1438]
The code is not perfoming what the documentation says

**Comment by giorgioGTelian** [comment]
hello @PerfidusPistor can you share with us the code you are working with?

**Comment by PerfidusPistor** [comment]
Hi, sure. This is the pull request https://github.com/CommunityToolkit/dotnet/pull/877

**Comment by Sergio0694** [comment]
Closing this, as it's in the wrong repo anyway 🙂
