### ISSUE TITLE
Please support more unary/binary operator operations.

### ISSUE THREAD

**Issue by zakean** [microsoft/dotnet#1444]
I hope for the addition of more unary/binary operator functionalities, such as a more concise `if` statement.

Normal usage:

```c#
if(bCondition)
{
    someVar = "Hello";
}
```

More concise:

```c#
if(bCondition)
    someVar = "Hello";
```

But I hope for support for the following syntax:

```c#
bool bCondition = true;
object obj = null;

bCondition??someVar = "Hello";
obj??bCondition= false;
(!bCondition)??someVar = "No";
```

**Comment by WeihanLi** [comment]
This relates to the C# language, you may want to create an issue in 
https://github.com/dotnet/csharplang/issues

**Comment by zakean** [comment]
> This relates to the C# language, you may want to create an issue in https://github.com/dotnet/csharplang/issues

Opps, sorry about that. I'll go ahead and create an issue in the C# language repo right away
