### ISSUE TITLE
Possible bug in System.Numerics BigInteger bitwise AND operation `&` in dotnet 9

### ISSUE THREAD

**Issue by Hecate2** [microsoft/dotnet#1458]
```csharp
System.Numerics.BigInteger.Parse("-9223372036854775808") & System.Numerics.BigInteger.Parse("-9223372036854775809")
```
This works in dotnet 8.0.204, with a result `-18446744073709551616`. But in dotnet 9.0.100 it throws an exception `Index was outside the bounds of the array`, because `System.Numerics.BigInteger.Parse("-9223372036854775808").GetBitLength() == 63`, and `System.Numerics.BigInteger.Parse("-9223372036854775809").GetBitLength() == 64`.
(Note that -9223372036854775808 == -2^63)
I am not really sure whether this is a bug or a feature.

**Comment by Hecate2** [comment]
Yet the bitwise OR operator works well. `System.Numerics.BigInteger.Parse("-9223372036854775808") | System.Numerics.BigInteger.Parse("-9223372036854775809")` is -1. Also XOR is well, returning 18446744073709551615.

**Comment by Youssef1313** [comment]
This belongs to dotnet/runtime repo.

@tannergooding Is that one fixed by https://github.com/dotnet/runtime/pull/105456?

**Comment by shargon** [comment]
Could someone transfer the issue to runtime?

**Comment by cschuchardt88** [comment]
@jeffhandley can you move to runtime?

**Comment by jeffhandley** [comment]
I can't transfer the issue across organizations, but I agree this is the same issue as dotnet/runtime#105456, which is fixed in main and will be included in the January 2025 servicing release.

Thank you for reporting that you encountered, @Hecate2.
