### ISSUE TITLE
[Proposal] To establish a official IRC for discussions and collaborations

### ISSUE THREAD

**Issue by prady00** [Microsoft/dotnet#18]
Pardon, writing here because could not find a better place, if there's one please include in docs for .net f/w

**Comment by joshfree** [comment]
The team has decided to use Gitter (https://gitter.im) for chat as it's fully integrated with GitHub.

* https://gitter.im/dotnet/corefx
* https://gitter.im/dotnet/coreclr
* https://gitter.im/dotnet/roslyn

I'm closing out this issue now that a chat system has been adopted.
