### ISSUE TITLE
Microsoft .NET Framework Assistant

### ISSUE THREAD

**Issue by Redsandro** [Microsoft/dotnet#185]
The [Microsoft .NET Framework Assistant](https://addons.mozilla.org/nl/firefox/addon/microsoft-net-framework-assist/) Firefox extension by [Microsoft](https://addons.mozilla.org/nl/firefox/user/microsoft-corporation/) is the only connection between Firefox and the Common Language Runtime for .NET in order to run ClickOnce WebLaunchers from Firefox. Is the code for that also in this repository? Who controls the Microsoft account?

It works nicely, but in at least Firefox 30 through 36, There is no mention of `.NET` or `CLR` in the `userAgent` (anymore), and there is no `application/x-ms-aplication` mentioned in `navigator.mimeTypes`.

We would like to be able to detect the presence/availability of this ClickOnce extension, so we can switch in javascript between opening the plugin page or opening the WebLauncher. It could use an update to show itself to client side javascript, or maybe there's a secret someone forgot to tell me.

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by Redsandro** [comment]
Well @richlander [removing the extension](https://addons.mozilla.org/nl/firefox/user/microsoft-corporation/) is not a solution. Is there an alternative for launching Microsoft ClickOnce `.application` links from Firefox?

**Comment by staceyhaffner** [comment]
Thanks for your feedback! The FireFox extension was not developed by Microsoft. That being said, we (the ClickOnce team) are currently investigating ClickOnce integration with major browsers. We don’t have an update yet, but we will respond to this issue once we know more.

To readers: Please add a reaction to communicate if you want my team to provide better ClickOnce support in FireFox.

**Comment by Redsandro** [comment]
@staceyhaffner ok gotcha, the username "Microsoft Corporation" made me think it was an official thing.
I'll be looking forward to this. Please keep us posted!

**Comment by DheerendraRathor** [comment]
With Firefox Quantum being an awesome browser and non of the existing add-ons (like FFClickOnce) being supported for FF 57, this is a real ask now! 
ClickOnce is already there for chrome, please make it for Firefox as well.

**Comment by Rushyo** [comment]
FxClickOnce dev here. I've got 10,000s of active Firefox users who can no longer use ClickOnce via the browser. It would be nice if you could provide them with an alternative.

**Comment by PingNGE** [comment]
I also need a way to launch apps via ClickOnce. I'm searching for a workaround, trying to force opening specific links with IE from Firefox. Do someone know about such an extension ? Or can it be configured inside Firefox with the per-application settings ?

**Comment by ahxfast** [comment]
There is a solution available here: https://www.reddit.com/r/firefox/comments/7cytbh/support_for_clickonce/

**Comment by whit0313** [comment]
Thanks @ahxfast ! It works fine for me.
The direct URL is [addons.mozilla.org/en/firefox/addon/breez-clickonce](https://addons.mozilla.org/en/firefox/addon/breez-clickonce/) by the way.

**Comment by Redsandro** [comment]
@PingNGE @Rushyo @DheerendraRathor the WindowsRemix ClickOnce helper plug-in is now available for Firefox.

See https://addons.mozilla.org/nl/firefox/addon/clickonce-helper/

I'm closing this issue as there seems no interest from the dotnet devs to revive their plug-in, and there are alternatives now.
