### ISSUE TITLE
Will Microsoft HTTP Client Libraries be added to GitHub?

### ISSUE THREAD

**Issue by PureKrome** [Microsoft/dotnet#188]
Hi MS team! :wave: 

Not sure if this the right place to ask, but will the [Microsoft HTTP Client Libraries](https://www.nuget.org/packages/Microsoft.Net.Http/) be released as OSS here in GH?

please say yes.
please say yes.
please say yes.
please say yes.
please say yes.
.yes say please
please say yes.
please say yes.

thanks :+1: :smiley: now here's an awesome sloth to try and influence you guys/gals to say YES!

![hugz](http://i.giphy.com/NcSksWOl9OHyU.gif)

**Comment by Petermarcu** [comment]
@PureKrome , timelines aren't known yet but yes, you will see a lot more of the networking libraries showing up on GitHub,

**Comment by PureKrome** [comment]
**hug** and thanks! keep up the awesome work!
