### ISSUE TITLE
Progressive JPEG

### ISSUE THREAD

**Issue by bardware** [Microsoft/dotnet#220]
Hi,

the question comes up every [now and then](http://stackoverflow.com/questions/2267717/save-jpg-in-progressive-format): will `System.Graphics.Bitmap` somewhen be able to save progressive JPEGs? Which github repository is the home of `System.Graphics`?

**Comment by patricksadowski** [comment]
Hi bardware,
I think you mean _System.Drawing.Graphics_. A new API is in design process. You can find the experimental component at [dotnet/corefxlab](https://github.com/dotnet/corefxlab/tree/master/src/System.Drawing.Graphics). Once the design process has completed the home of System.Drawing.Graphics will be [dotnet/corefx](https://github.com/dotnet/corefx).

Some discussions concerning the new API can be found
[here](https://github.com/dotnet/corefx/issues/1563) and [here](https://github.com/dotnet/corefxlab/issues/86).

**Comment by richlander** [comment]
/cc @bleroy 

Please re-activate if this is still an issue.
