### ISSUE TITLE
Memory Mapped File access : the file is being used by another process

### ISSUE THREAD

**Issue by hanu412** [Microsoft/dotnet#226]
I am trying to use MemoryMappedFile to write some bulk data from the database. Whenever I am running application in a single instance,it works perfectly well-as the writing is taking place sequentially. But whenever I am trying to run the same application in multi-instance mode,it is failing to write to the file. If one instance is writing data to the file,the other instance which got instantiated in parallel is unable to access this file.  

I looked at the file.cs class in the framework but I could not find a property or method which can give me information if the file is free to be written i.e.,it is not being used by any other process. 

Could someone help me -how do I check if the file is not being used by any other process?

public static void WriteToMMF(string fileName, byte[] records, long? beginOffset, long? endOffset)
        {
            //create MMF
            try
            {
                using (var writeMMF = MemoryMappedFile.CreateFromFile(fileName, FileMode.OpenOrCreate, "OutboundMMF", endOffset.Value))
                {
                    using (MemoryMappedViewAccessor accessor = writeMMF.CreateViewAccessor())
                    {
                        accessor.WriteArray(beginOffset.Value, records, 0, records.Length);

```
                }
            }
        }
        catch (Exception ex)
        {

            throw ex;

        }
    }
```

**Comment by barrattac** [comment]
See below link.  
http://stackoverflow.com/questions/876473/is-there-a-way-to-check-if-a-file-is-in-use

V/RChris Barratta

Date: Mon, 24 Aug 2015 16:13:13 -0700

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
