### ISSUE TITLE
LambdaCompiler

### ISSUE THREAD

**Issue by informatorius** [Microsoft/dotnet#229]
I found the Microsoft LambdaCompiler used e.g. by Moq is much slower in 64bit compared to 32bit even with .net 4.6 RyuJit. Where do I address this issue?

**Comment by sivarv** [comment]
Please file a Connect bug (http://connect.microsoft.com) along with a repro program.

**Comment by informatorius** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/1765569/lambdacompiler-compile-is-slow-in-64bit-compared-to-32bit
