### ISSUE TITLE
Discovery for new .NET Team projects

### ISSUE THREAD

**Issue by richlander** [Microsoft/dotnet#231]
I see that [CLRMD](https://github.com/Microsoft/clrmd) was published. That's great. How are people supposed to find projects like that, particularly when they are in the Microsoft not dotnet orgs.

Three potential options:
- Add them to: https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md
- Add them to a new file, to avoid being lost in the noise: dotnet-team-projects.md
- Add them to both

Thoughts?

**Comment by jlanng** [comment]
Maybe they could exist in the same list, but be clearly marked as MS projects?

**Comment by richlander** [comment]
@jlanng Right, that would be a slight variation on option 1. The basic question underlying this is whether people want to be able to find projects from the .NET team more easily than others. It's perfectly fine if they don't. This is in part because we have more tools coming, so I'm thinking ahead a bit on this.

**Comment by jlanng** [comment]
@richlander I can only speak for myself, but yes I certainly do want to

**Comment by snipesjr** [comment]
I'm with jlanng as well

**Comment by codespare** [comment]
OctoKit + PowerShell is a possiblity:
``` PowerShell
$repos = $gitHubAPI.Repository.GetAllForOrg($GitHubAccount).Result
$repos |
            sort UpdatedAt -Descending | select $colSort |
            ConvertTo-Html -As Table -Title "$GitHubAccount GitHub Repositories" > ".\github-orgs\${fileBaseName}.html"
```
