### ISSUE TITLE
Add python support to VS. I don't want other crappy IDEs handling my python code anymore make a python IDE part of VS

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/dotnet#262]
Like what I said above all the IDEs I find are slow to load for me the VS ones load faster than Photoshop CS6. So, I need such IDE that is great, knows what to highlight, and also knows other languages as well. and is better than Notepad++. As well as a way to debug python code in it and ways that is suggests on making it better as well as a simple way of python 2.x to 3.x conversion without less of functionality. Sadly I have some python 2 code that uses some bytes things that python 3 does not let me use.

**Comment by shiftkey** [comment]
[This is already a thing](https://www.visualstudio.com/en-us/features/python-vs.aspx)

**Comment by AraHaan** [comment]
oh ty so it comes with 2015? or just a addon?

**Comment by GonzaloFajardoMedina** [comment]
I think could be a problems for the libraries, but it's a good idea.

**Comment by AraHaan** [comment]
oh btw I did found a few python files that (when cythonized) makes the Incremental Linker use up over 1 GB of RAM when it should not on a computer that has a 4 GB of RAM actually in it (I also seen python.exe use that much RAM to in some cases so I think it is in some way die to the Incremental linker and not it's code).

**Comment by singlewind** [comment]
Personally, I'd like cheap my python things in JetBrains PyCharm. They have free community version.

**Comment by AraHaan** [comment]
For me PyCharm Freezes a lot (and sadly so does Visual Studio 2015 but not as much as PyCharm)

**Comment by danmosemsft** [comment]
@AraHaan The place for feedback on VS is http://connect.microsoft.com/VisualStudio
