### ISSUE TITLE
Different formats of dotnet461-api-changes.md and dotnet46-api-changes.md

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/dotnet#271]
`releases/net461/dotnet461-api-changes.md` is a markdown with fenced code block of `diff` format. It looks very nicely. 
But `releases/net46/dotnet46-api-changes.md` is just an html despite its extension.
It would be nice to see the same format in both files.

p.s. also let me ask how do you generate such diff for api changes?

**Comment by bleroy** [comment]
You're right, thanks, I'll fix it. We use an internal tool to generate the diffs.

**Comment by bleroy** [comment]
It's been fixed.
