### ISSUE TITLE
Quality Assurance - Csharp Coding Guidelines link does not work

### ISSUE THREAD

**Issue by achhunchha01** [Microsoft/dotnet#281]
I have observed that in dotnet-developer-projects.md under **Quality Assurance** section link for [C# Coding Guidelines](https://github.com/Microsoft/dotnet/blob/master/csharpcodingguidelines.com) is broken. It says that page does not exist.

**Comment by joshka** [comment]
I saw this issue after making the following fix https://github.com/Microsoft/dotnet/pull/302
