### ISSUE TITLE
Command Line generated projects into Visual Studio

### ISSUE THREAD

**Issue by anguoyang** [Microsoft/dotnet#282]
Hi, I followed the tips on this web link:
http://dotnet.github.io/getting-started/
Both the Windows and Docker samples run successfully, my question is: how to convert the command line generated projects(with project.json and nuget files) into Visual Studio so that I could use this powerful IDE? When I created the DNX project in Visual Studio and copied the src folder into DOCKER, and run the dotnet restore/run, it generated errors:
Errors in /home/hello/project.json
    System.Console 4.0.0-beta-23516 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.Threading 4.0.11-beta-23516 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.Dynamic.Runtime 4.0.0 provides a compile-time reference assembly for System.Dynamic.Runtime on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.Linq.Expressions 4.0.0 provides a compile-time reference assembly for System.Linq.Expressions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.IO 4.0.0 provides a compile-time reference assembly for System.IO on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.Threading.Tasks 4.0.0 provides a compile-time reference assembly for System.Threading.Tasks on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    System.Text.Encoding 4.0.0 provides a compile-time reference assembly for System.Text.Encoding on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
    Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64).

NuGet Config files used:
    /home/hello/hello_world/NuGet.Config
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
root@57b37f07a735:/home/hello# dotnet run
Project hello (DNXCore,Version=v5.0) will be compiled because some of its inputs were newer than its oldest output.
Compiling elloor 
                 NXCore,Version=v5.0
sr/share/dotnet/bin/dotnet compile-csc @/home/hello/obj/Debug/dnxcore50/dotnet-compile.rsp returned Exit Code 1
/home/hello/hello_world/obj/Debug/dnxcore50/dotnet-compile.assemblyinfo.cs(2,11): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
/home/hello/hello_world/obj/Debug/dnxcore50/dotnet-compile.assemblyinfo.cs(3,11): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute

[39;49mCompilation failed.
  0 Warning(s)
    2 Error(s)

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
