### ISSUE TITLE
.NET 4.6.1 GC taking a lot of longer time than 4.5

### ISSUE THREAD

**Issue by z2xlong** [Microsoft/dotnet#289]
Hi .NET Team,

I found .NET 4.6.1 is still not fix the bug of GC taking a lot of longer time than 4.5 on Windows Server 2008 R2 SP1, but there is no hotfix like as KB3088957 for .NET 4.6, so how can I do? thank you very much.

**Comment by Maoni0** [comment]
The right action to take is to capture some performance data so we can help you with the analysis. There could be many reasons GC is taking a lot of time - application/library behavior changes, machine config changes and changes in GC itself. We need data to tell which one it is. It sounds like you already have some data captured to tell that GC is taking more time, will you be willing to share that with us?

**Comment by z2xlong** [comment]
Hi Maoni,
Thanks for your reply.  Yes, I got some events via perfview,  as follow:I know it's a heavy load service, but it works  faster on .NET 4.5.1 than .NET 4.6.1Trace InfoMachine NameSVR4942HW1288Operating SystemWindows Server 2008 R2 EnterpriseOS Build Number7601.18933.amd64fre.win7sp1_gdr.150715-0600UTC offset where data was collected8.00UTC offset where PerfView is running8.00Delta of Local and Collection Time0.00OS Boot Time04/19/2016 11:40:19.537Trace Start Time04/27/2016 08:23:26.389Trace End Time04/27/2016 08:33:57.111Trace Duration (Sec)630.7CPU Frequency (Mhz)2,000Number Of Processors32Memory Size (Meg)196,580Pointer Size8Sample Profile Interval (MSec) 1.00Total Events3,594,065Lost Events0ETL File Size (MB)247.3 No data collection log file foundGC Stats for for Process  1456: w3wp Runtime Version: V 4.0.30319.0CLR Startup Flags: CONCURRENT_GC, LOADER_OPTIMIZATION_SINGLE_DOMAIN, LOADER_OPTIMIZATION_MULTI_DOMAIN, LOADER_SAFEMODE, SERVER_GC, HOARD_GC_VM, LEGACY_IMPERSONATION, DISABLE_COMMITTHREADSTACKTotal CPU Time: 307,847 msecTotal GC CPU Time: 59,483 msecTotal Allocs  : 33,378.262 MBGC CPU MSec/MB Alloc : 1.782 MSec/MBTotal GC Pause: 4,680.6 msec% Time paused for Garbage Collection: 7.5%% CPU Time spent Garbage Collecting: 19.3%Max GC Heap Size: 177,173.602 MBPeak Process Working Set: 196,217.262 MBPeak Virtual Memory Usage: 276,399.407 MB
GC Rollup By GenerationAll times are in msec.GenCountMax
PauseMax
Peak MBMax Alloc
MB/secTotal
PauseTotal
Alloc MBAlloc MB/
MSec GCSurvived MB/
MSec GCMean
PauseInducedALL9871.9177,173.63,511.6654,680.633,378.37.10.075520.1005720.94,556.6681.1852,128.1-26,714.60.10.079425.6014871.9177,173.63,511.6652,552.460,092.90.10.070638.10200.00.00.0000.00.00.0

0
Pause > 200 Msec GC Events for Process  1456: w3wpGC Events by TimeAll times are in msec.  Hover over columns for help.GC
IndexPause StartTrigger
ReasonGenSuspend
MsecPause
MSec%
Pause
Time% GCGen0
Alloc
MBGen0
Alloc
Rate
MB/secPeak
MBAfter
MBRatio
Peak/AfterPromoted
MBGen0
MBGen0
Survival
Rate %Gen0
Frag
%Gen1
MBGen1
Survival
Rate %Gen1
Frag
%Gen2
MBGen2
Survival
Rate %Gen2
Frag
%LOH
MBLOH
Survival
Rate %LOH
Frag
%Finalizable
Surv MBPinned
Obj53149566,404.114AllocSmall0N0.193390.6377.025.63,523.486680.873,637.863172,979.6920.02651.77235.97318100.00772.342非数字0.00157,886.097非数字0.0014,285.280非数字0.000.04253150574,383.505AllocSmall1N0.056653.0237.923.84,220.320556.12177,173.602172,741.7181.03638.985183.1358100.00378.817330.00157,886.097非数字27.1914,293.668非数字23.440.23253151581,856.379AllocSmall0N0.075353.0444.918.34,176.652612.414,556.591173,061.3790.03384.263107.7698100.00769.434非数字0.00157,886.097非数字0.0014,298.080非数字0.000.04153152592,000.770AllocSmall1N0.045871.8678.228.24,099.423418.67177,068.651172,719.6731.03772.325192.6617100.00342.836440.00157,886.097非数字26.8814,298.080非数字23.260.11353153596,580.831AllocSmall0N0.158720.87716.327.82,661.033717.583,037.561173,221.7700.02603.20280.38822100.00957.205非数字0.00157,886.097非数字0.0014,298.080非数字0.000.02353154601,566.289AllocSmall1N0.150595.21312.218.43,924.143920.15177,073.647172,629.2541.03385.758265.7633100.00173.133210.00157,886.097非数字26.7714,304.261非数字22.740.17353155610,398.130AllocSmall0N0.182348.1954.118.73,488.151423.493,699.528172,829.2200.02374.76484.29310100.00553.949非数字0.00157,886.097非数字0.0014,304.881非数字0.000.02253156619,433.480AllocSmall1N0.161432.3274.719.03,808.914438.45176,554.943172,552.0091.02324.308186.2244100.00174.807340.00157,886.097非数字26.6914,304.881非数字22.600.09253157628,101.945AllocSmall0N0.066315.3833.719.83,474.491421.853,650.129172,902.1880.02313.994214.7998100.00493.664非数字0.00157,886.097非数字0.0014,307.627非数字0.000.042
Condemned reasons for GCsThis table gives a more detailed account of exactly why a GC decided to collect that generation.   Hover over the column headings for more info.
GC IndexHeap
IndexInitial
Requested
GenerationFinal
GenerationGeneration
Budget
ExceededTime
TuningInducedEphemeral
LowExpand
HeapFragmented
EphemeralVery
Fragmented
EphemeralFragmented
Gen2High
MemoryCompacting
Full
GCSmall
HeapEphemeral
Before
BGCInternal
Tuning531490000000000000000531502010001000000001531510000000000000000531520010000000000001531530000000000000000531540010000000000001531550000000000000000531561010000000000001531570000000000000000Date: Wed, 27 Apr 2016 11:48:21 -0700

**Comment by Maoni0** [comment]
Do you mind making a table? This is extremely hard to read.

**Comment by swgillespie** [comment]
@z2xlong Hello, are you still having this problem?

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
