### ISSUE TITLE
dotnet command in Docker container does not return

### ISSUE THREAD

**Issue by aviral26** [Microsoft/dotnet#298]
I tried to run `dotnet restore`, `dotnet run` and `dotnet new` in a Ubuntu container using the published microsoft/dotnet image. The commands run successfully but do not return; the command line hangs and I have to exit and re-enter the container. When I re-enter, I can see the files have been created successfully.

**Comment by richlander** [comment]
Please re-activate if this is still an issue and share a minimal Dockerfile.
