### ISSUE TITLE
Problem running dotnet on Ubuntu 14.04

### ISSUE THREAD

**Issue by aviral26** [Microsoft/dotnet#299]
I followed the installation instructions at https://www.microsoft.com/net/core#ubuntu.

Facing the following issue: 

`dotnet new`
`Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main`
`Segmentation fault (core dumped)`

Additional information:

`uname -a`
`Linux ubuntu 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mesutpiskin** [comment]
you must check installation step

```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update
```

If the following error
_Err https://apt-mo.trafficmanager.net trusty/main amd64 Packages
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign https://apt-mo.trafficmanager.net trusty/main Translation-en
Fetched 809 kB in 10s (76.4 kB/s)
W: Failed to fetch https://apt-mo.trafficmanager.net/repos/dotnet/dists/trusty/main/binary-amd64/Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead._

```
echo -n | openssl s_client -connect apt-mo.trafficmanager.net:443 | \
  sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | \
  sudo tee '/usr/local/share/ca-certificates/apt_mo_trafficmanager_net.crt'
sudo update-ca-certificates

```
```
sudo apt-get update
sudo apt-get install dotnet-dev-1.0.0-preview1-002702
```
check result
`dotnet --info`

**Comment by richlander** [comment]
Please re-activate if this still an issue.
