### ISSUE TITLE
Which CLA?

### ISSUE THREAD

**Issue by fgreinacher** [Microsoft/dotnet#30]
Which CLA needs to be signed to contribute to .NET? Would be good to have this information in CONTRIBUTING.md.

Thanks a ton!

**Comment by joshfree** [comment]
The dotnetfoundation CLA needs to be completed when submitting pull requests to http://github.com/dotnet/corefx 

Here is the link https://cla2.dotnetfoundation.org/

**Comment by fgreinacher** [comment]
Thanks a lot!
