### ISSUE TITLE
Is it possible for UWP to refer a .NET Core console/library project?

### ISSUE THREAD

**Issue by Brian-Ding** [Microsoft/dotnet#300]
i am thinking since both uwp and .net core console app are based on dotnet core, is it possible to do so?

thank you

**Comment by Petermarcu** [comment]
It will be but

**Comment by Petermarcu** [comment]
It will be for library projects but its not wired up cleanly yet.

**Comment by Brian-Ding** [comment]
Thank you for your reply


Could you please be more specific? Are we expecting uwp (not library) can refer a corner core library, or the other way around, or both ways?

**Comment by Petermarcu** [comment]
It will be apps (UWP) referencing a standard library. Standard libraries (netstandard) will be the way to produce a library that can run everywhere that supports netstandard. UWP apps are one of those places that support it. The preview tooling we'll be releasing soon will have better support for creating a csproj based library that targets netstandard. It will be a flavor of a portable library.

**Comment by Brian-Ding** [comment]
Great! Looking forward to that


Thank you guys for the hard work here.
