### ISSUE TITLE
.NET 4.6.2 with Windows 8 

### ISSUE THREAD

**Issue by igarciaolaizola** [Microsoft/dotnet#312]
¿Is there a reason why Windows 8 has been discarded from the Supported Operating System list of .NET 4.6.2? I have installed the update successfully in a Windows 8 Enterprise 64bits.

**Comment by lextm** [comment]
https://support.microsoft.com/en-us/lifecycle?C2=16796

Because Windows 8 lifecycle has ended, and you are supposed to upgrade to Windows 8.1 or 10.

**Comment by fujiy** [comment]
What about Windows Server 2008?

**Comment by lextm** [comment]
@fujiy unfortunately, Microsoft decided not to support Windows Server 2008 with .NET Framework 4.6.2, and you have to use Windows Server 2008 R2 and above, as pages like below indicate,

https://www.microsoft.com/en-us/download/details.aspx?id=53344

**Comment by richlander** [comment]
This is all correct. The support matrix is considered with each new .NET release.
