### ISSUE TITLE
SqlDataReader.NextResultAsync and ReadAsync cause unobserved task exception even when awaited

### ISSUE THREAD

**Issue by jnm2** [Microsoft/dotnet#313]
I posted a fairly critical bug in the .NET Framework to Connect. I've heard nothing in reply for four months. 4.6.2 has come and gone. Is Connect a dead end? I would appreciate it if someone would respond.

https://connect.microsoft.com/VisualStudio/feedback/details/2592987/sqldatareader-nextresultasync-causes-unobserved-task-exception-even-when-awaited

**Comment by jnm2** [comment]
We're starting to suffer from this in production. Can someone at least acknowledge that this bug report has been looked at?

**Comment by jnm2** [comment]
Awesome! Followup finally happened at Connect. Thank you.

**Comment by frodegil** [comment]
Glad you managed to identify the cause. I was struggeling with the exact same issue for days when I found your post at Microsoft Connect. Just wanted to say thanks :)
My Stackoverflow question (First, I thought it was a Dapper issue):
http://stackoverflow.com/questions/40284205/dapper-sqlexception-and-unobserved-exception
