### ISSUE TITLE
Failed to restore packages on Docker Build

### ISSUE THREAD

**Issue by shanegray** [Microsoft/dotnet#314]
I'm getting an error on a new web project (and a few others) with restoring packages. Not machine specific.

```
log  : Restoring packages for /app/project.json...
log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/4.0.0/system.text.encodings.web.4.0.0.nupkg'.
log  : Response status code does not indicate success: 404 (Not Found).
```

Docker File

```
FROM microsoft/dotnet:latest

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]

RUN ["dotnet", "build"]

EXPOSE 5000/tcp

ENTRYPOINT ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]
```

Project created using 

```
dotnet new -t web
```

Nothing else added.

**Comment by Malhoura** [comment]
Hi I'm actually having the same issue, it's giving this error message when I run the build behind the corporate proxy, though when I run outside of the proxy it would build correctly. Are you running on a proxy?

**Comment by richlander** [comment]
Is this still an issue?

/cc @blackdwarf

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
