### ISSUE TITLE
Including native libraries in dotnet projects

### ISSUE THREAD

**Issue by patrickjamesbarry** [Microsoft/dotnet#317]
I have a legacy project that has a published a nuget package that looks like this: 
![image](https://cloud.githubusercontent.com/assets/2013066/18283350/c83f161c-7432-11e6-9c4f-abd1f21e6902.png)

Those are c++ dlls under the runtime folders, and it is not a dotnet/project.json project.

When I include this project as a dependency, I see these c++ dlls are included in the output dir when I perform a **dotnet publish**. however, they are not included in the output dir when I perform a **dotnet build**.  This means that when I try to run my project in Visual Studio, it cannot find the required c++ libs, because they are not in the bin directory.  

I have played around with copyToOutput includes and cannot seem to get these dlls to appear in output. Is there something broken or is this behaving as expected?

example project.json

```
{
  "version": "1.0.0-*",
  "packOptions": {
  },
  "buildOptions": {
    "outputName": "test.progect",
    "emitEntryPoint": false,
    "platform": "anycpu",
    "copyToOutput": {
      "include": [
        "**/*.json"
      ],
      "exclude": [
        "bin"
      ]
    }
  },
  "publishOptions": {
    "include": [
      "**/*.json"
    ],
    "exclude": [
      "bin"
    ]
  },
  "dependencies": {
    "ININ.Tracing-w64": "2.1.1.5",
    "RestSharp": "105.2.3"
  },
  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Runtime.Serialization": "4.0.0.0",
        "System.Xml": "4.0.0"
      }
    }
  },
  "configurations": {
    "Debug": {
      "buildOptions": {
        "define": [
          "DEBUG",
          "TRACE"
        ],
        "debugType": "portable"
      }
    },
    "Release": {
      "buildOptions": {
        "define": [
          "RELEASE",
          "TRACE"
        ],
        "optimize": true
      }
    },
    "win7-x64": {
      "buildOptions": {
        "define": [
          "DEBUG",
          "TRACE"
        ],
        "debugType": "portable"
      }
    }
  }
}
```

**Comment by richlander** [comment]
Closing due to active issue on dotnet/cli.
