### ISSUE TITLE
2 dotnet run command cannot work on ubuntu 14.04

### ISSUE THREAD

**Issue by hasanoruc** [Microsoft/dotnet#320]
First of all sorry my bad English.

My question is.. I cannot 2 dotnet run command on ubuntu. Please help me. I have a web project, running on ubuntu works perfect but now i added web api project but i cannot start 2 project at once.

Web api project program.cs file:

```
namespace KatmanWebAPI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseUrls("http://localhost:5021")
                .Build();

            host.Run();
        }
    }
}
```
And then webui project Program.cs file:

```
namespace KatmanWebUI
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseUrls("http://localhost:5020")
                .Build();

            host.Run();
        }
    }
}
```
I enter in KatmanWebUI project folder and run `dotnet run` command works properly and going fine. Also i run this server 70 days without restart. But when runs KatmanWebUI project and then i am starting KatmanWebAPI project and then interfering each other. For example when starting a page from KatmanWebUI page and css is going down. Or some icons not showing and web site in not going properly.

My nginx file about server backend:

```
upstream backend {
        server 127.0.0.1:5020;
        server 127.0.0.1:5021;
        server 127.0.0.1:19920;
}
```
So how can i start 2 projects run properly. System is Ubuntu 14.04 LTS Trusty.

**Comment by danroth27** [comment]
@tratcher @joshfree It sounds like you are having issues specifically with serving static files. Static files will by default be served from a wwwroot folder that is relative to the content root of the app. Both these projects are using the "current" directory for their content root. Perhaps the problem is that both apps are trying to serve static files from the same directory? That should in theory be just fine, unless there is some issue with the lower level file APIs.

**Comment by Tratcher** [comment]
Side note: Move UseUrls before UseIISIntegration.

I think your nginx upstream configuration is the problem. http://nginx.org/en/docs/http/ngx_http_upstream_module.html "By default, requests are distributed between the servers using a weighted round-robin balancing method." Nginx is routing requests randomly to your two different applications, so sometimes it cannot find the correct resources. You need to change your nginx config, or run a separate instance of nginx for each application.

**Comment by hasanoruc** [comment]
Yess. Only KatmanWebUI project runs 70 days perfectly. So only 1 project is going properly. i am stopping KatmanWebUI project and run KatmanWebAPI web api project going perfectly. So 2 projects not work same time. So what will do set about nginx config?

**Comment by hasanoruc** [comment]
Thank you very much all. I change a little change for nginx configuration and i solve this problem.

My nginx conf file is:
```
        location / {
        proxy_pass http://backend;
        proxy_set_header        Connection "";
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_buffer_size 8k;
        proxy_busy_buffers_size 8k;
        }

```

And i added ahother location name about webapi with this:

```
        location /api {
        proxy_pass http://127.0.0.1:5021;
        proxy_set_header        Connection "";
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_buffer_size 8k;
        proxy_busy_buffers_size 8k;
        }

```

And i deleted `server 127.0.0.1:5021;` from backend:

```
upstream backend {
        server 127.0.0.1:5020;
        server 127.0.0.1:19920;
}
```

And problem was solved. Thanks.
