### ISSUE TITLE
Unexpected character encountered while parsing value: #

### ISSUE THREAD

**Issue by tbertran** [Microsoft/dotnet#324]
I'm getting the following error when setting up a new Windows 7 64-bit box (VS 2015 Preview 3, .Net 1.0.0-preview3-003612)

`PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "D:\ProDev\Dev\ERMA\.vs\restore.dg"
error: Error reading 'D:\ProDev\Dev\ERMA\.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0.`

I tried to alter `restore.dg` and remove the commented out lines but it gets generated automatically every time I try to restore packages (see below):
`#:D:\ProDev\Dev\ERMA\ERMA.Web\ERMA.Web.xproj
D:\ProDev\Dev\ERMA\ERMA.Web\ERMA.Web.xproj|D:\ProDev\Dev\ERMA\ERMA.Web.Models\ERMA.Web.Models.xproj
# :D:\ProDev\Dev\ERMA\ERMA.Web.Test\ERMA.Web.Test.xproj

D:\ProDev\Dev\ERMA\ERMA.Web.Test\ERMA.Web.Test.xproj|D:\ProDev\Dev\ERMA\ERMA.Web\ERMA.Web.xproj
D:\ProDev\Dev\ERMA\ERMA.Web\ERMA.Web.xproj|D:\ProDev\Dev\ERMA\ERMA.Web.Models\ERMA.Web.Models.xproj`

**Comment by wburgers** [comment]
I've got the same problem
Nuget 3.5 restore works though
rather annoying that it does not work in VS

**Comment by csbudai** [comment]
Still I have exactly the same problem

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "c:\users\username\documents\visual studio 2015\Projects\projectname\.vs\restore.dg" -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"
error: Error reading 'c:\users\username\documents\visual studio 2015\Projects\projectname\.vs\restore.dg' at line 0 column 0 : Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
error:   Unexpected character encountered while parsing value: #. Path '', line 0, position 0.
```

Some additional info
```
Microsoft Visual Studio Professional 2015 Version 14.0.25431.01 Update 3

$ dir "C:\Program Files\dotnet\sdk"
26/09/2016  08:13    <DIR>          1.0.0-preview2-003131
16/09/2016  09:48    <DIR>          1.0.0-preview3-003612

$ dotnet.exe --version
1.0.0-preview3-003612
```

**Comment by benaadams** [comment]
Main bug over at https://github.com/dotnet/cli/issues/4248

Work around is either to run dotnet restore at command line or delete the preview3 folder from the sdk directory
