### ISSUE TITLE
CNG key providers to Mage and Mageui SDK tools fails on XBAP compile

### ISSUE THREAD

**Issue by TechnoDex** [Microsoft/dotnet#325]
In v4.6.2 Framework under the Windows Forms changes, the following change is not working
- Added support for CNG key providers to Mage and Mageui SDK tools [194373]

When compiling a WPF Solution as an XBAP application where the Project file contains a PropertyGroup with the HostInBrowser value set to True and using an RSA SHA2 CNG Certificate for Code Signing, the compilation fails the SignFile Task with error MSB3482.

This is the same error message that would be put out from the mage.exe utility prior to including support for the CNG Certificates.  

<PropertyGroup>
  <HostInBrowser>True</HostInBrowser>
</PropertyGroup>

1>Target "**ResignApplicationManifest**" in file "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets" from project "C:\Test\CNGTest.csproj" (target "GenerateManifests" depends on it):
1>Task "Message" skipped, due to false condition; ('$(MSBuildTargetsVerbose)'=='true') was evaluated as (''=='true').
1>Task "Message" skipped, due to false condition; ('$(MSBuildTargetsVerbose)'=='true') was evaluated as (''=='true').
1>Task "Message" skipped, due to false condition; ('$(MSBuildTargetsVerbose)'=='true') was evaluated as (''=='true').
1>Task "SignFile"
1>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(614,9): **error MSB3482: An error occurred while signing: Invalid provider type specified.**

**Comment by Tanya-Solyanik** [comment]
Hi TechnoDex,
It seems that you are signing your manifest in the VIsualStudio, or at least from the msbuild process? This had not been updated. The supported scenario is command line manifest signing using mge.exe or mageui.exe SDK tools. Here is a walkthrough:
https://msdn.microsoft.com/en-us/library/xc3tc5xx(v=vs.110).aspx
SDK can be downloaded from here:
https://www.microsoft.com/en-us/download/details.aspx?id=53321

Hope this helps,
Tanya
