### ISSUE TITLE
Stop adding auto connection strings in config files

### ISSUE THREAD

**Issue by sujaysarma** [Microsoft/dotnet#327]
Somewhere 2 versions ago .NET started adding invisible automatic connection strings to application configuration files. Trying to retrieve the 0th Connection String would always return:

"data source=.\SQLEXPRESS;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|aspnetdb.mdf;User Instance=true"

Removing this behavior means a trip to the machine.config file for each installed .NET framework and removing this value from there.

Can we please have a patch that removes this behavior?

**Comment by richlander** [comment]
What type of application are you using?

**Comment by sujaysarma** [comment]
ASP.NET obviously. Refering to the web.config files.

**Comment by csharpfritz** [comment]
Machine.Config has a default connection string in it called "LocalSqlServer" that has the contents you are referring to.  The configuration of ASPNet applications is hierarchical, so your web.config inherits everything from the configuration files "above" it, including machine.config.

You can prevent this connectionstring from being available in your application by adding a <clear /> element to the top of your connectionStrings section in web.config

**Comment by sujaysarma** [comment]
@csharpfritz Yes, that is what I am forced to do now. That behavior must be "default" instead of everyone having a "<remove ..." or a "<clear />" at the start of these config sections. This should be true for at least the appSettings and connectionStrings sections.

**Comment by richlander** [comment]
I doubt we can change this behavior now, good or bad, due to compatibility.

I would be surprised if >1 machine.config is consulted. It's only supposed to be 1/version.

Is this a performance concern or just that is it is unnecessary/annoying?

**Comment by sujaysarma** [comment]
"I doubt we can change this behavior now, good or bad, due to compatibility."
Do you seriously believe that people are using a local MSDE connection and expect it to be at default?

Anyways, this only affects people who are looking for ConnectionString[0] rather than by key name.

**Comment by richlander** [comment]
If we removed the existing ConnectionString[0] connection string, then ConnectionString[1] might no longer exist.That would be a break.

**Comment by sujaysarma** [comment]
You're joking right? 

My point is that ConnectionString[0] in these situations turn out to be the "data source=.\SQLEXPRESS;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|aspnetdb.mdf;User Instance=true" (the one am asking to be removed). 

If code accesses connection strings as ConnectionString[0], it would always get that above "default" connection string. That is the only situation where the situation you're talking about [breaking backward compatibility] arises. All the code that does ConnectionString["mydb"] will continue to work.

**Comment by richlander** [comment]
I wasn't joking. I meant if you are accessing your own connection string via index and not name, then your code would break if we removed the connection string currently stored at the 0 index.

**Comment by sujaysarma** [comment]
Why did you close this issue? @richlander

**Comment by richlander** [comment]
Because I provided an answer 4 months ago and there was no response. I said the change you are requesting was breaking, such that it isn't actionable.
