### ISSUE TITLE
dotnet build not working web app

### ISSUE THREAD

**Issue by joacar** [Microsoft/dotnet#340]
Hi,

Built a project earlier without any errors (targeted netcoreapp1.0).

Went on to another project (netcoreapp1.1) and it worked at a start. Then I migrated it to the new VS17 RC2 csproj-style (as i did with the previous) and now it stopped working. Tried to switch to netcoreapp1.0 but without any result. The project has built just fine on Mac (now it probably wont :)

# Installed .NET Core SDK/Runtimes
![dotnetcore](https://cloud.githubusercontent.com/assets/439028/21147456/60d19caa-c155-11e6-80f6-11398aa71041.PNG)

````
>dotnet --info
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
````

# Exception
````
C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(140,5): error MSB4062: The "Microsoft.NET.Build.Tasks.ResolvePackageDependencies" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\..\tools\netcoreapp1.0/Microsoft.NET.Build.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\..\App.csproj]
C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(82,5): error MSB4062: The "GenerateDepsFile" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\..\tools\netcoreapp1.0/Microsoft.NET.Build.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\..\App.csproj]
````

**Comment by joacar** [comment]
The issue was that the UserSecretsId wasn't enclosed in its own `<PropertyGroup>`. The project now builds from VS but fails from root-folder when using command line.

````
App
  App.sln
  -src
    -App
       App.csproj
````

**Comment by danmosemsft** [comment]
This should go to https://github.com/dotnet/cli

**Comment by codito** [comment]
I see the same error when a `sln` includes projects from newer sdk (`<Project Sdk="Microsoft.NET.Sdk">`) and older sdk (`<PackageReference Include="Microsoft.NET.Sdk">`).

May be related to https://github.com/dotnet/sdk/issues/352

**Comment by richlander** [comment]
Did you get resolution on this?

**Comment by richlander** [comment]
Please re-activate if this is still an issue.
