### ISSUE TITLE
Add support for readonly/const/final function parameters

### ISSUE THREAD

**Issue by johndog** [Microsoft/dotnet#345]
In a nutshell, add a feature so that the answer to this SO question is "yes":

http://stackoverflow.com/questions/2339074/can-parameters-be-constant

Probably shouldn't be a breaking change for API writers, since it only needs to be enforced in the locality of the function itself.  The purpose would be to make sure parameters aren't written over (i.e. used as temp variables) in the implementation.  Purpose is not to provide any guarantees to the caller.

**Comment by pharring** [comment]
This has been proposed many times (for C#) and is tracked at https://github.com/dotnet/roslyn/issues/115
Recommend closing this issue and moving the discussion to the roslyn repo.

**Comment by johndog** [comment]
I knew it couldn't be new, just couldn't find it.
