### ISSUE TITLE
`dotnet new -t web` fails if a readme is present

### ISSUE THREAD

**Issue by ebelew** [Microsoft/dotnet#346]
Repro:

1. Create new git repository
2. Add Readme.md as first commit
3. Execute dotnet command to create project scaffolding:
```
$ dotnet new -t web
Creating new C# project failed, directory already contains README.md
```
Is a readme really a blocking issue?

Possible solutions:

* Create `Readme.aspnet.md` instead?
* Move original readme.md to new file?

**Comment by richlander** [comment]
Can you try again with the latest tools? I tried this w/o issue.

```console
C:\Users\rich>md test

C:\Users\rich>cd test

C:\Users\rich\test>echo "hi" > README.md

C:\Users\rich\test>dotnet new web
Getting ready...
Content generation time: 91.5196 ms
The template "ASP.NET Core Empty" created successfully.

C:\Users\rich\test>
```
