### ISSUE TITLE
FileSystemWatcher events raise more than once

### ISSUE THREAD

**Issue by s-a** [Microsoft/dotnet#347]
REF.: http://stackoverflow.com/questions/1764809/filesystemwatcher-changed-event-is-raised-twice

Are there any working workarounds for the bug available? I am experiencing this in .net Framework 4.5.2. Maybe fixed in later versions?

**Comment by richlander** [comment]
I'm unfamiliar with this issue. Did you try one of the workarounds in the SO page?

**Comment by richlander** [comment]
Please re-activate if this is still an issue.

**Comment by s-a** [comment]
Thank you for the reply. Yes I tried every thing. 
Just tried to create a [reproducable example](https://github.com/s-a/dot-net-filesystemwatch-experiment/) but failed 😞. I was not able to reproduce this behavior on my machine. In fact I am getting `System.IO.IOException`s at https://github.com/s-a/dot-net-filesystemwatch-experiment/blob/bb2753d3e2072654d4ee4e736ace8c8565b0a238/Program.cs#L109 on our production servers. The main difference is that this this custom filewatcher class is implemented in a Windows service executable. 

I noticed this behaviour years ago to face this again now.


A user on SO wrote 

> I am afraid that this is a well-known bug/feature of the FileSystemWatcher class. This is from the documentation of the class:  ...

So I guess I am not the only person having trouble with this. I just thought maybe it is not a .NET problem. Maybe it has something to do with Windows messaging on specific servers.  

I need to investigate more time to explore behavior of code in a Windows service. Anyway any help would be wonderful. So maybe we can hold this issue open for a while? A coder reading this could have an idea to help.

**Comment by SmokinLeather** [comment]
@richlander 
Can this be reopened?

This is still an issue on .net Framework 4.6
Watching a specific file, I get 2 OnFileChanged event notifications (using MS NotePad).
Both FileSystemEventArgs args say ChangeType = Changed

I believe that one is for File Date changed. And one is for LastWrite changed. (could be other change types)
But there is no way to tell what the change type is from the FileSystemEventArgs arg.

My code uses
 watcher.NotifyFilter = NotifyFilters.LastWrite;
 
It would be nice if the FileSystemEventArgs would specify  "change type" (ie LastWrite, FileDate, etc)
Then the program could just process the event it cares about and ignore the rest.

**Comment by s-a** [comment]
@SmokinLeather are you able to reproduce this with this code? https://github.com/s-a/dot-net-filesystemwatch-experiment/ 

What Windows Version are you using?

**Comment by SmokinLeather** [comment]
@s-a
Thanks. I'll take a look at that experiment.

My test code is very simple. It's a windows forms app. I start it, then open the text file in Notepad. Make and edit to the textfile and save it. Then  consistently the OnFileChanged event fires two times, every time I save the text file. The FileSystemEventArgs are identical each time.

On Windows 10, Home Edition. Creator Update.
.Net Framework 4.6
==========================

```
     private void FileWatcherSetup(string path)
        {
            FileSystemWatcher watcher = new FileSystemWatcher();
            string folderName = Path.GetDirectoryName(path);
            string fileName = Path.GetFileName(path);
            watcher.Path = folderName;

            watcher.NotifyFilter = NotifyFilters.LastWrite;
            watcher.Filter = fileName;  
            watcher.Changed += new FileSystemEventHandler(OnFileChanged);
            watcher.EnableRaisingEvents = true;
        }
 int ctr = 0;
 private void OnFileChanged(object source, FileSystemEventArgs e)
        {
            Console.WriteLine("OnFileChanged" + ctr);
		ctr++;
        }

        public Form1()
        {
		  string  aFilepath = @"C:\Test\TestFile.txt";
            FileWatcherSetup(aFilepath);
	}        

```

**Comment by s-a** [comment]
I can confirm the behavior @SmokinLeather described. His efforts brought me to test this line of code at https://github.com/s-a/dot-net-filesystemwatch-experiment/blob/master/Program.cs#L132 which fires twice and is definitely reproducable on my system running on `Microsoft Windows [Version 10.0.10586]` using `.NET Framework 4.5.2.` 
I am sure construe underlying issue @SmokinLeather described will lead to the bug I originally reported. 

So @terrajobst @stephentoub @richlander please reopen this issue.

**Comment by Petermarcu** [comment]
We should move this issue to dotnet/corefx where the open source version of FileSystemWatcher exists. We should confirm whether or not it repro's on .NET Core where there have been a lot of fixes and then figure out if we need a fix or can identify what fixed it. Then we can work to port that change back to .NET Framework. I'll open that issue now and point back to this issue.

**Comment by Petermarcu** [comment]
Closing this issue in this repo. Any followup should be on https://github.com/dotnet/corefx/issues/25117

**Comment by Legends** [comment]
Only the changed event is execute twice, didn't try the .net core version.
Example executed in Linqpad 4:

```
void Main()
{
    Watch (GetTestDirectory(), "*.txt", true);
}

void Watch (string path, string filter, bool includeSubDirs)
{
using (var watcher = new FileSystemWatcher (path, filter))
{
    watcher.Created += FileCreatedChangedDeleted;
    watcher.Changed += FileCreatedChangedDeleted;
    watcher.Deleted += FileCreatedChangedDeleted;
    watcher.Renamed += FileRenamed;
    watcher.Error += FileError;
    watcher.IncludeSubdirectories = includeSubDirs;
    watcher.EnableRaisingEvents = true;
    Console.WriteLine ("Listening for events - press <enter> to end");
    Console.ReadLine();
    }
    }
    void FileCreatedChangedDeleted (object o, FileSystemEventArgs e)
    { Console.WriteLine ("File {0} has been {1}", e.FullPath, e.ChangeType);}
    
    void FileRenamed (object o, RenamedEventArgs e)
    { Console.WriteLine ("Renamed: {0}->{1}", e.OldFullPath, e.FullPath);}
    
    void FileError (object o, ErrorEventArgs e)
    { Console.WriteLine ("Error: " + e.GetException().Message);}


// Define other methods and classes here
string GetTestDirectory(){ return RuntimeInformation.IsOSPlatform (OSPlatform.Windows)? @"C:\Temp": "/tmp";}
```
