### ISSUE TITLE
System.Data.SqlClient.TdsParser cannot parse tabular SQL batch server response

### ISSUE THREAD

**Issue by cheziyi** [microsoft/dotnet#375]
System.Data.SqlClient.TdsParser from the latest .NET Frameworks throws an InvalidOperationException when trying to parse a generic TDS batch server response similar to this: https://msdn.microsoft.com/en-us/library/dd341261.aspx. Exception messages generally look like this:

> System.InvalidOperationException occurred
>   HResult=-2146233079
>   Message=Internal connection fatal error. Error state: 15, Token : 52
>   Source=System.Data
>   StackTrace:
>        at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>   InnerException: 

As far as we know, this issue occurs on System.Data v4.6.1636.0, as well as System.Data v4.6.1055.0, on both Windows 7 and Windows 10 machines.
This issue does not occur in .NET Core 1.0, nor does it occur on a clean Windows 7 SP1 installation with .NET Framework 4.5.2 installed.

This issue is also posted at https://connect.microsoft.com/VisualStudio/feedback/details/3129532

**Comment by richlander** [comment]
Asking the team for help.

**Comment by bazzilic** [comment]
Any updates on this?

**Comment by cheziyi** [comment]
A longer explanation is available here: https://stackoverflow.com/questions/42634394/sqlcommand-executereader-cannot-parse-tds-response

**Comment by corivera** [comment]
@cheziyi Do you have any isolated repro steps for this?

**Comment by cheziyi** [comment]
Hi @corivera,

I have create a repo here: https://github.com/cheziyi/TDSBridge, that returns a SQL Server Batch Response similar to the one here: https://msdn.microsoft.com/en-us/library/dd341261.aspx.

Steps to reproduce:
1. Build the project at https://github.com/cheziyi/TDSBridge.
2. Run it with the appropriate arguments:
`<listen port> <sql server address> <sql server port>`
_sql server address_: The IP address of a real SQL Server to negotiate authentication
_sql server port_: The port of the real SQL Server
_listen port_: The port on localhost for the TDSBridge to listen on
3. Using `sqlcmd`, connect to the localhost TDSBridge, with credentials of the real SQL Server.
4. Execute the SQL batch command `showmethemoney` to return a response similar to the one here: https://msdn.microsoft.com/en-us/library/dd341261.aspx

If all goes well, the TDSBridge should have an output similar to:
![proxy](https://user-images.githubusercontent.com/1861634/28299554-8ca82c52-6bac-11e7-9aad-8a96b9ee326f.PNG)

and `sqlcmd `should have an output similar to:
![sqlcmd](https://user-images.githubusercontent.com/1861634/28299480-14a48f8e-6bac-11e7-8746-e7c2464aa1de.PNG)

As you can see from the output of the TDSBridge, the bytes returned by the TDSBridge is similar to the one in the [MS-TDS] documentation.

5. Now, create a .NET Framework 4.5 C# project using a Windows 10 machine, and execute the same command using SqlCommand.ExecuteReader. It will fail.
6. Now, create a .NET Core C# project, and execute the same command using SqlCommand.ExecuteReader. It will work.

This demonstration shows that either the  .NET Framework 4.5 has an issue parsing TDS responses, or, the official MS-TDS documentation is erroneous or outdated.

**Comment by bazzilic** [comment]
@corivera is there any movement with this issue?

**Comment by corivera** [comment]
@bazzilic We haven't been able to look into this issue yet.

**Comment by vbejinariuS2P** [comment]
Had 2 days of work on this issue.

Everything was working for me on Development Environment but was throwing this exception on the Test Env.

I did two things at the same time, on the same pull request So I'm not too sure which one fixed this but you could check/resolve both.

My first guess on what fixed it, is that I've updated to the latest version of System.Data.SqlClient(which was .NetStandard 1.3 compatible). 
Second, I had a .NetStandard 2.0 project in my solution. I've removed it.

Hope it helps

**Comment by kalaskarsanket** [comment]
Looks like this is resolve, if still a problem kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
