### ISSUE TITLE
List of Download servers

### ISSUE THREAD

**Issue by iano123** [Microsoft/dotnet#390]
Hi,

this is probably not the place. But I think it can be directed easily.

I work for a company which is heavy on security. With the new visual studio you have packages and updates. We do not have internet access to our dev machines, but can request white listed https sites. This means we could enable the updates to work.

Could you tell me the list of hosts that are needed to enable the update mechanism?
For what I can see we need:
https://download.microsoft.com
https://login.live.com

Many THanks.

**Comment by iano123** [comment]
Ah please both for the installer as the updates inside visual studio.

I believe others will benefit of this information as well.

**Comment by richlander** [comment]
I passed on the request to the Visual Studio team.

**Comment by iano123** [comment]
Thank You!

**Comment by Petermarcu** [comment]
@richlander is this issue still being used to track?

**Comment by richlander** [comment]
Check out: https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio-behind-a-firewall-or-proxy-server
