### ISSUE TITLE
Please provide access to dotnet bugfix/improvement notes

### ISSUE THREAD

**Issue by coderb** [Microsoft/dotnet#396]
The new release notes for dotnet 4.7 include very brief descriptions of the changes.

I am very interested in the details behind a few of them, as I am sure others are.

eg I’d like to see details of “Improved reliability of the Windows Forms DataGrid control. [236488]”

There doesn't appear to be any way to get access to the issue notes #236488 at the current time.

**Comment by feathermann** [comment]
+1 to that, especially referring to 236488 - after having received dotnet 4.7 via windows update, our customers are seeing degraded performance on DataGrid control, we are observing that deinstallation of 4.7 fixes the problem.

**Comment by richlander** [comment]
We don't provide much detail in the release notes. They are there to help provide people with a sense of the improvements and to provide a unique ID (our internal VSTS bug tracking number) for each change.

@feathermann can you provide more info on the performance degradation? We want to learn more.

@Tanya-Solyanik can you provide more info on this change?

**Comment by Tanya-Solyanik** [comment]
@feathermann, we had fixed a recent performance degradation in DataGridView control in the upcoming release of .Net Framework (4.7.1) and will be servicing this bug in Windows Updates for 4.7 version.

@coderb  - This was a null reference exception when DataGridView control window Handle was destroyed after the tooltip object associates with this DataGridView had been destroyed . This might had looked as a crash on parent form closing.

**Comment by richlander** [comment]
I will take this as a vote that people want more detail in our release notes. Sounds good.
