### ISSUE TITLE
CancellationToken throws even if throwing is not requested

### ISSUE THREAD

**Issue by sam-wheat** [Microsoft/dotnet#410]
https://msdn.microsoft.com/en-us/library/system.threading.cancellationtoken.throwifcancellationrequested(v=vs.110).aspx

http://stackoverflow.com/questions/7343211/cancelling-a-task-is-throwing-an-exception

First link above documents ThrowIfCancellationRequested - presumably the token does not throw if the method is not called first, correct? 

        [Test]
        public async Task CancelTokenTest()
        {
            SemaphoreSlim sem = new SemaphoreSlim(0, 1);
            CancellationTokenSource src = new CancellationTokenSource();
            CancellationToken token = src.Token;
            Action a = async () => await sem.WaitAsync(token);
            a();
            src.Cancel(); // throws
        }

**Comment by jnm2** [comment]
I'm thinking this belongs at https://github.com/dotnet/corefx.

**Comment by svick** [comment]
In your code, `WaitAsync()` throws, because `token` became cancelled. Since `a` is `async void`, the exception is rethrown on the current synchronization context (if there is one).

Which part of that is not the behavior you would expect?

**Comment by sam-wheat** [comment]
Thanks svick, I do not expect the token to throw as I have not called ThrowIfCancellationRequested.
Sorry if I posted in the wrong place.

**Comment by sam-wheat** [comment]
It looks like I was confused on the purpose of ThrowIfCancellationRequested............

I read the [documentation for CancellationTokenSource](https://msdn.microsoft.com/en-us/library/system.threading.cancellationtokensource(v=vs.110).aspx) which says:

> Call the CancellationTokenSource.Cancel method to provide notification of cancellation. This sets the CancellationToken.IsCancellationRequested property on every copy of the cancellation token to true. 

and for some reason I thought that calling the CancellationTokenSource.Cancel method would provide notification of cancellation by seting the CancellationToken.IsCancellationRequested property on every copy of the cancellation token to true.  

But it looks like this is only half the story as the CancellationTokenSource appears to have to throw to cause the semaphore to continue.

**Comment by svick** [comment]
> But it looks like this is only half the story as the CancellationTokenSource appears to have to throw to cause the semaphore to continue.

It's not really the `CancellationTokenSource` itself that throws, it's the `WaitAsync`. And the whole point of passing the `CancellationToken` to that method is so that it can be cancelled, which you can observe as it throwing an exception.

Effectively, `WaitAsync` calls `ThrowIfCancellationRequested`, or does [something similar](http://referencesource.microsoft.com/#mscorlib/system/threading/SemaphoreSlim.cs,708), so that it can be cancelled.

**Comment by sam-wheat** [comment]
> which you can observe as it throwing an exception.
Regardless of who throws I would much rather observe the IsCancellationRequested property without the exception.  Having read the code (line 727) I am still not clear why WaitAsync - or anyone else - needs to throw.  
It seems to me that line 727 takes control from the developer (which she/he has by way of `ThrowIfCancellationRequested`) and just imposes the exception.  This is, in many cases (certainly in my case), a violation of [the good design principals found here](https://msdn.microsoft.com/en-us/library/ee796807(v=cs.20).aspx).

**Comment by svick** [comment]
@sam-wheat That's how `CancellationToken` works: if you pass it to a method, the token gets cancelled and the method observes it, it will throw an exception.

It does not take control from you, you gave up the control by passing the `CancellationToken` to the method.

If I understand you correctly, you propose that if the method observes that the `CancellationToken` is cancelled, it should just silently return? I think that would be a terrible idea, because you would have no indication that the method did not finish successfully.

**Comment by sam-wheat** [comment]
@svick No, I don't think `CancellationToken` works that way.  As cited in my post above I believe the functionality is like this:

> Call the CancellationTokenSource.Cancel method to provide notification of cancellation. This sets the CancellationToken.IsCancellationRequested property on every copy of the cancellation token to true.

If the developer observes the `IsCancellationRequested` property and chooses throw that is his decision (`ThrowIfCancellationRequested` makes this a bit easier).  

In many cases (such as mine), cancellation is part of normal program flow and I do not want to use or rely on exceptions.  In the case of the semaphore, I should at least have an opportunity to observe `IsCancellationRequested` and throw if i desire to to so.  However as you describe the WaitAsync method denies me this opportunity by throwing in advance.

I've worked around this by implementing a TryWaitAsync Extension method.  I still have to live with the exception at the framework level however.  My suggestion is that semaphore slim implement something like TryWaitAsync and not throw in this new method.

**Comment by svick** [comment]
> I don't think `CancellationToken` works that way.

What I meant is that, as far as I know, every single method that supports cancellation by accepting a `CancellationToken` does work that way.

> My suggestion is that semaphore slim implement something like TryWaitAsync and not throw in this new method.

Then you should file an issue on [the corefx repo](https://github.com/dotnet/corefx), following [the API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

**Comment by richlander** [comment]
Closing ... satisfactory guidance has been given. Thanks @svick.
