### ISSUE TITLE
Regression issue printing richText to impact printer between 4.6.2 and 4.7

### ISSUE THREAD

**Issue by darinclarkdev** [Microsoft/dotnet#414]
We use user32.dll SendMessage to print the contents of the RichTextBox control following the Microsoft example given here https://support.microsoft.com/en-us/help/811401/how-to-print-the-content-of-a-richtextbox-control-by-using-visual-basic-.net-or-visual-basic-2005. This works fine on most printers up through .net Framework 4.6.2. When we recompiled for 4.7 the page is printing about half size on Lexmark 2480 impact printer. We had observed this with previous framework versions on some Brother laser printers but were able to circumvent it by changing the print driver. We will not be able to move to 4.7 until we have a way around this.

**Comment by Tanya-Solyanik** [comment]
Hi DarinClarkDev,
Thank you for reporting this issue. Could you please try adding app.config file with the following compatibility switch under AppContextSwitchOverrides tag to see if this issue goes away:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7"/>
  </startup>
  <runtime>
    <AppContextSwitchOverrides
      value="Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl=true" />
  </runtime>
</configuration>

```
Another question: Had you upgraded the OS as well as the .Net Framework version? Does this only reproduces when your application is recompiled targeting 4.7?

Thank you, 
Tanya

**Comment by Tanya-Solyanik** [comment]
And another question  - does the content of RichTextBox control matter of does this reproduce with any text? If content matter, could you please share a sample?
Thank you, Tanya

**Comment by darinclarkdev** [comment]
Tanya,
I have only checked this on Windows 10 1703. It only happens when then application is targeting 4.7. If It is compiled for 4.6.2 it works fine. The content of the RichTextBox doesn't seem to matter but will check that. When I get a chance to test the compatibility switch I will.

Thanks

**Comment by Tanya-Solyanik** [comment]
Thank you for the response, I wonder if you had verified if PrintPageEventArgs are returning incorrect sizes for this printer. We were not able to reproduce this issue with our printers, so I have a couple follow up questions to you. I assume you have the latest printer driver compatible with windows 10, right? Are you able to print from Microsoft Word? Do you see any unexpected values when you step though your application? Anything else that would help us reproduce the issue?
Thank you, Tanya

**Comment by darinclarkdev** [comment]
[FORC1P.zip](https://github.com/Microsoft/dotnet/files/1070033/FORC1P.zip)

Tanya,
Using the compatibility switch when compiling for 4.7 does fix the issue.

The paper sizes look fine and are the same in 4.6.2 and 4.7. 
I have saw this before in .net 4.0 with a Brother Laser Printer. In that case I was able to use an HP LaserJet 4 driver as a work around.

The printer driver is one supplied by Windows.
It prints from word.

I have attached a scrubbed (removed customer info) copy of the rtf file I have been testing with. This is the way I have been building my RTF files for the last decade but I could be missing something that is throwing the new RichTextBox off. The crazy thing is most printers work fine.

This is from the Hardware properties event page of the printer if it is any help.
Device SWD\PRINTENUM\{371F026A-D25D-4D40-8C9C-161BA0AF0765} was configured.

Driver Name: printqueue.inf
Class Guid: {1ED2BBF9-11F0-4084-B21F-AD83A8E6DCDC}
Driver Date: 06/21/2006
Driver Version: 10.0.15063.0
Driver Provider: Microsoft
Driver Section: NO_DRV_LOCAL
Driver Rank: 0x0
Matching Device Id: PRINTENUM\LocalPrintQueue
Outranked Drivers: c_swdevice.inf:SWD\GenericRaw:00FF3001
Device Updated: false
Parent Device: USBPRINT\Lexmark_InternationalLexmark_Forms_Printer_2480\6&1f2b3f5e&0&USB001

**Comment by richlander** [comment]
Can you take a look at this again @Tanya-Solyanik ?

**Comment by richlander** [comment]
Hi @darinclarkdev. We have not been able to reproduce this. We could potentially setup a conf call so that we could see the issue on your machine. Please mail me at rlander@ms if you would like to do that. Otherwise, I'll close this issue.

**Comment by richlander** [comment]
Thoughts @darinclarkdev ?

**Comment by darinclarkdev** [comment]
@richlander if you use the AppContextSwitchOverrides that @Tanya-Solyanik provided it works fine. For now I am keeping that set of projects at 4.6.2. Since you guys aren't able to repro this and there is a workaround we can consider this closed.
