### ISSUE TITLE
Information on website regarding Fedora is not correct/optimal

### ISSUE THREAD

**Issue by bhkeys** [Microsoft/dotnet#415]
I noticed that the microsoft page for .NET core on Fedora does not support the latest version of Fedora.
https://www.microsoft.com/net/core#linuxfedora
And these instructions do not work on Fedora 25 despite being binary compatible with Fedora 24. There is a SIG that packaged dotnet and I am using it with success, could you guys consider redocumenting it to include this repo?
https://copr.fedorainfracloud.org/coprs/nmilosev/dotnet-sig/
Since it integrates with the package manager (and actually works), it would give Fedora users a much more standard and comfortable experience when getting started with .NET

**Comment by richlander** [comment]
can you take a look @leecow?

**Comment by leecow** [comment]
Thanks @bhkeys. .NET Core 1.0 and 1.1 do not support Fedora 25. Support for the 25 and 26 is being added to .NET Core 2.0. You can see the listing at [https://www.microsoft.com/net/core/preview#linuxfedora(]https://www.microsoft.com/net/core/preview#linuxfedora). We're also in the early phases of producing RPMs which can be seen at https://github.com/dotnet/core-setup#daily-builds and https://github.com/dotnet/cli#installers-and-binaries in the RHEL portion of the table.

**Comment by vstoykov** [comment]
nmilosev/dotnet-sig Copr is no longer available

**Comment by Petermarcu** [comment]
Closing this as .NET Core 2.0 is out and supports later versions of Fedora.
