### ISSUE TITLE
Internal error when trying to compile with .NetNative (Microsoft.NetNative.targets(691,5))

### ISSUE THREAD

**Issue by ebroglio** [microsoft/dotnet#420]
.nuget\packages\microsoft.net.native.compiler\1.6.2\tools\Microsoft.NetNative.targets(691,5): error : Internal compiler error: One or more errors occurred. 

Following code produces this error with version 5.3.3. With version 5.2.3 it is working fine. 

[DllImport("test.dll", CallingConvention = CallingConvention.StdCall)]
private static extern unsafe void test(Windows.Foundation.Point* points);

**Comment by richlander** [comment]
PTAL @lt72

**Comment by lt72** [comment]
PTAL @zamont

**Comment by zamont** [comment]
@ebroglio if you are still facing this issue, can you please send an email to dotnetnative@microsoft.com with all of the context you have? Team members will be able to pick up the issue and assist you.

**Comment by richlander** [comment]
Can you share more info @ebroglio ?

**Comment by ebroglio** [comment]
Create an empty uwp project.

add following lines:
[DllImport("test.dll", CallingConvention = CallingConvention.StdCall)]
private static extern unsafe void test(Windows.Foundation.Point* points);

then you get following error:
.nuget\packages\microsoft.net.native.compiler\1.7.3\tools\Microsoft.NetNative.targets(697,5): error : Internal compiler error: One or more errors occurred.

I'm using Microsoft.NETCore.UniversalWindowsPlatform version 6.0.5
When compiling without Native tool chain everything is working fine.

Currently I'm using a workaround to pass these points to my native dll.

By the way what is the reason that c# struct Windows.Foundation.Point returns double and Windows::Foundation::Point float?

**Comment by kalaskarsanket** [comment]
This issue has not got any input for long time and we have changed were issues are tracked. If this is still an issue kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
