### ISSUE TITLE
BigInteger should have a less strictly typed constructor

### ISSUE THREAD

**Issue by bazzilic** [Microsoft/dotnet#422]
`BigInteger` from `System.Numerics` could be "serialized" and "deserialized" to/from a byte array.

However, currently, it only has a constructor that takes `byte[]`. Since the constructor (according to the reference source) actually only uses `.Length` property and indexed access, it would have been enough to require `IList<byte>` as an argument.

First, asking for an interface instead of a specific type seems more in line with the ideology of the language. Second, there are situations when this would have been more convenient.

As an example, we are implementing some public key cryptosystems and use big integers internally. Many PK cryptosystems produce ciphertexts that are actually a pair of bigintegers, which are stored as a single byte array; e.g., in a `byte[96]` we have two big integers, 48 bytes long each. Reconstructing these would require an extra step of copying first and second halves of the array into individual arrays — an expensive operation, and it adds up when we are working with large data sets. Instead, if there was an `IList<byte>` constructor, we could have used `ArraySegment<byte>` and skip an unnecessary array copying.

**Comment by bazzilic** [comment]
Noted, thanks, will do a proposal in the corefx repo as well.

**Comment by richlander** [comment]
Agreed. This repo isn't the right one for this. Closing issue.

**Comment by jnm2** [comment]
> As an example, we are implementing some public key cryptosystems and use big integers internally.

Unless your product *is* a full crypto library, a thousand to one you shouldn't be doing this.

**Comment by jnm2** [comment]
(Everyone thinks they are the exception, but to be honest...)

**Comment by jnm2** [comment]
It's like speeding or not wearing a seat belt. Everyone is sure they can get away with it but the risk vs benefit just doesn't make any sense if you look at the consequences.

**Comment by bazzilic** [comment]
Our product is a crypto library.

**Comment by jnm2** [comment]
That's awesome, I'm glad to hear it!
