### ISSUE TITLE
visual studio 2013 & 2015 cannot configure HTML editor Formating

### ISSUE THREAD

**Issue by zengyunchun** [Microsoft/dotnet#428]
## Visual Studio text editor options as below
![](https://ooo.0o0.ooo/2017/06/20/594895754838b.png)

1.  As the picture, I can find Html(Web Forms) Formatting to change configuration, but when I use MVC project , CSHTML extension file will auto use HTML configuration that cannot allow me to configure the Formatting
2. Could you give me an advice for how to configure CSHTML formatting so that I can disable auto transferring the tag to lowercase when formatting the code.

Thanks a lot, Microsoft Engineers !!!!!!

**Comment by richlander** [comment]
@madskristensen who should look at this?

**Comment by madskristensen** [comment]
@richlander we have a thread with @zengyunchun going here https://github.com/MicrosoftDocs/visualstudio-docs/issues/161

We can't repro the issue and waiting for @zengyunchun to comment on whether or not he's using ReSharper or some other extension that causes the issue.

**Comment by richlander** [comment]
I am closing this issue since the other one is more primary. Tell me @zengyunchun is that is the wrong choice. Thanks @madskristensen!
