### ISSUE TITLE
WPF window not loading after .net 4.7 install on server core

### ISSUE THREAD

**Issue by ucthev** [microsoft/dotnet#431]
After installing .net framework 4.7 on Windows Server 2016 Core, WPF window does not load. It loads perfectly on full install of Windows Server 2016. Here is an example code (using PowerShell, which is how I use WPF windows to load and show some reports) which I have re-produced few times:
`PS C:\> Add-Type -AssemblyName PresentationFramework -Verbose
PS C:\> $wd = New-Object System.Windows.Window
New-Object : Exception calling ".ctor" with "0" argument(s): "The type initializer for '<Module>' threw an exception."
At line:1 char:7
+ $wd = New-Object System.Windows.Window
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand`

**Comment by ucthev** [comment]
PowerShell version installed on the server:
`PS C:\Users\umesh> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1358
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1358
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

**Comment by richlander** [comment]
Did this work before you installed .NET Framework 4.7?

**Comment by ucthev** [comment]
yes it did. its after .net 4.7 installation that it stopped working. I tested it couple of times and results have been consistent (wpf worked before .net 4.7 installation, not afterwards)

**Comment by richlander** [comment]
I passed on the issue to the WPF team. They are looking at it.

**Comment by ucthev** [comment]
great..thanks a lot!

**Comment by jvilimek** [comment]
Hi there, any workaround for this? I have tried to uninstall .net 4.7 and reinstall .net 4.6.2 but the issue is still there. I am experiencing not working VS tools installer (visualcppbuildtools_full.exe running on Windows Server 2016 core) since it needs WPF for some reason. It ends up with last entry in log "starting UX" and then it creashes with exception like here (from minidump: ModuleLoadException: The C++ module failed to load during appdomain initialization. DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
Win32Exception: The specified module could not be found).
But the dll is there (1 343 664 B, file version 4.7.2053.0).
Any help or hint appreciated.
I can even send you the minidump if this will help.

**Comment by jvilimek** [comment]
Hurray! I actually found it: after uninstalling .NET 4.7 and reinstalling .NET 4.6.2 I have enabled .NET 3.5 feature and now it works!
Add-WindowsFeature -Name NET-Framework-Core

**Comment by ucthakur** [comment]
the .net seems to be badly broken as I see it. After performing a fresh install of Windows Server 2016, I patched it with August 2017 cumulative patch (KB4034658), did not install .net 4.7 and guess what, I experience the exact same problem as mentioned in this issue with 4.6 as wel!! on a fresh install without patching it, everything was working great. 
This is too frustrating indeed. I do not unnecessarily want to install .net 3.5 on my system. How can this be fixed?

**Comment by richlander** [comment]
I just sent mail to the team again.

**Comment by AustinFontenotHEES** [comment]
Is there an update on this issue? When trying to install TFS 2018 on Server Core 2016, I am unable to run tfsconfig due to the same error.

**Comment by Abdulrazik** [comment]
any updates ? i'm trying to install TFS 2018 on server core and after the required restart i get the following error ... "tfsmgmt.exe has stopped working". tfsconfig gives the previous exception of "ModuleLoadException: The C++ module failed to load during appdomain initialization. DllNotFoundException: C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll"

**Comment by Abdulrazik** [comment]
i tried the beta version of the new framework 4.7.1 from microsoft at
https://www.microsoft.com/en-us/download/details.aspx?id=56115

and it seems to have fixed my issues ...

**Comment by richlander** [comment]
@Abdulrazik That's not a beta version, but the release version.

Hey @ucthev have you tried 4.7.1?

**Comment by ucthakur** [comment]
Hi Rich,

I am going to give it a try today.. will be updating shortly

________________________________

**Comment by ucthev** [comment]
I downloaded .net 4.7.1 installer, tried to run it on Windows Server 2016 Server Core installation but it failed to run at the point where it tries t verify "setuputility.exe". I tried using both online as well as offline installer and both had same results. 
These are the last lines from log file:
[12/8/2017, 2:12:28] Action: Downloading and/or Verifying Items
[12/8/2017, 2:12:28]Verifying Digital Signatures: C:\200815f6dbddb59efc\SetupUtility.exe
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 1
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 2
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 3
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 4
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 5
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 6
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 7
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 8
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 9
[12/8/2017, 2:12:28]LoadImage failed for rotation icon 10

Has anyone tried it on Server Core?

**Comment by richlander** [comment]
Just asked team to take a look.

**Comment by merriemcgaw** [comment]
@ucthakur, try installing silently with the /q command line parameter. That should get everything installed. We are taking a look at how to allow UI based setup on Server Core again in a future release.

**Comment by ucthev** [comment]
@merriemcgaw and @richlander thanks a lot! I was finally able to install it using /q command and I can see that WPF windows are now loading correctly! This has taken some time but glad to see it fixed! 
thanks again,

**Comment by kalaskarsanket** [comment]
As per last comment looks like this issue resolved, if still a problem kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
