### ISSUE TITLE
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) while loading Assembly using AssemblyResolve_LoadFrom

### ISSUE THREAD

**Issue by nigurr** [microsoft/dotnet#436]
Hi,

We have seen couple of customers hitting the above error (randomly) and the process gets aborted because of this error.
The files are present and the way we load the DLLs are pretty straightforward. Under what circumstances we throw this error and what are the possible causes?

Code:
```
var fileList = new DirectoryInfo(probingPath).GetFiles(assemblyName.Name + ".dll", SearchOption.TopDirectoryOnly);
if (fileList.Length > 0)
{
       return Assembly.LoadFrom(fileList.First().FullName);
}
```

Error:
```
DTAExecutionHost.exe Warning: 0 : Main.InitializeAndStartExecutionHost. Failed to load assembly: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll' or one of its dependencies. Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
File name: 'file:///C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll' ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.VisualStudio.TestService.Utility.TestPlatformAssemblyLoader.AssemblyResolve_LoadFrom(String probingPath, String name, Boolean recurse) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.Utility\TestPlatformAssemblyLoader.cs:line 86
```

**Comment by richlander** [comment]
Please provide the [fusion logs](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) for your application when this happens. The way the logs work if you don't have to predict exactly when this happens. You can enable logging and then collect the logs only when this crash occurs next. You can send the logs to rlander@ms if they are private. Please do try to interpret them first, however, as they may tell you the answer.

I just did a super quick search. Does [this SO post](https://stackoverflow.com/questions/26327244/visual-studio-2013-unit-test-error-could-not-load-microsoft-visualstudio-testpl) on incorrect app.config help?

**Comment by abhishekkumawat23** [comment]
@richlander : We are loading assembly at runtime using Assembly.LoadFrom. Thus fusion logs doesn't have binding logs for this runtime loading.

Can you please help us in identifying under what circumstances this (catastrophic load failure) issue is thrown?

Please let know if you need any additional info from us.

**Comment by richlander** [comment]
Do you handle the AppDomain.AssemblyResolve event?

which directory are you loading from? Is it from the VS directory?

**Comment by nigurr** [comment]
@richlander Yes we are resolving the event and so able to load the DLLs. Though it's working for 90% scenarios, the 10% scenarios are running into Catastrophic failure on similar machine.
We are loading from the VS directory `[VSIDE\CommonExtensions\Microsft\TestWindow]`

**Comment by emmanuelguerin** [comment]
Hitting the same problem when loading Microsoft.Build.Framework:
```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) --->
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Build.Framework.dll' or one of its dependencies.
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) --->
System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
```

**Comment by richlander** [comment]
Can you provide fusion logs for this? That might help.

**Comment by richlander** [comment]
Please provide us with more information so that can investigate further.

**Comment by kalaskarsanket** [comment]
This issue has not got any input for long time and we have changed were issues are tracked. If this is still an issue kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
