### ISSUE TITLE
Error -99 EADDRNOTAVAIL address not available

### ISSUE THREAD

**Issue by hujie5592427** [Microsoft/dotnet#439]
root@8e592f30159d:/hwapp# dotnet run --server.urls http://0.0.0.0:5000
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: (Error -99 EADDRNOTAVAIL address not available)
Hosting environment: Production
Content root path: /hwapp
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^CApplication is shutting down...

**Comment by richlander** [comment]
Can you provide more info on which distro you are using?

You might get a faster response filing this at [aspnet/home](https://github.com/aspnet/home/issues).

This info might also help: https://github.com/dotnet/dotnet-docker#interactively-build-and-run-an-aspnet-core-application

/cc @DamianEdwards

**Comment by Petermarcu** [comment]
Closing for now. If you are still hitting an issue, we should open this issue on the aspnet/home repo with more details.

**Comment by chtbof** [comment]
I have the same issue, I just run a empty example in docker dotnet runtime

**Comment by Petermarcu** [comment]
@chtbof can you open an issue on https://github.com/aspnet/home with all the details?
