### ISSUE TITLE
String.Compare w/ IgnoreNonSpace incorrect for "tT" = "ŧŦ" (stroke accent T) 

### ISSUE THREAD

**Issue by DerekZiemba** [Microsoft/dotnet#444]
Tested on Framework 4.5 and 4.6.2.  String Compare with CompareOptions.IgnoreNonSpace incorrectly compares "T" with a stroke accent.  Other stroke accent characters such as "D" and "H" compare correctly. These are ISO Latin 1 Extended A characters 

	Dim Invariant = CultureInfo.InvariantCulture.CompareInfo
	Dim Current = CultureInfo.CurrentCulture.CompareInfo

	Dim bInvariantStroke_T = Invariant.Compare("t", "ŧ", CompareOptions.IgnoreNonSpace) = 0    '//False
	Dim bCurrentStroke_T = Current.Compare("t", "ŧ", CompareOptions.IgnoreNonSpace) = 0        '//False
	Dim bInvariantStroke_T2 = Invariant.Compare("T", "Ŧ", CompareOptions.IgnoreNonSpace) = 0   '//False
	Dim bCurrentStroke_T2 = Current.Compare("T", "Ŧ", CompareOptions.IgnoreNonSpace) = 0       '//False

	Dim bInvariantStroke_D = Invariant.Compare("dD", "đĐ", CompareOptions.IgnoreNonSpace) = 0  '//True
	Dim bCurrentStroke_D = Current.Compare("dD", "đĐ", CompareOptions.IgnoreNonSpace) = 0      '//True

	Dim bInvariantStroke_H = Invariant.Compare("hH", "ħĦ", CompareOptions.IgnoreNonSpace) = 0  '//True
	Dim bCurrentStroke_H = Current.Compare("hH", "ħĦ", CompareOptions.IgnoreNonSpace) = 0      '//True

	Const AlphaNumericIgnoreCase = CompareOptions.IgnoreCase Or CompareOptions.IgnoreNonSpace Or CompareOptions.IgnoreSymbols Or CompareOptions.IgnoreWidth Or CompareOptions.IgnoreKanaType

	Dim bInvariantWithStroke_T = Invariant.Compare("diacritical", "ĐĩàĈŗįŧïćâĻ", AlphaNumericIgnoreCase) = 0 '//False
	Dim bCurrentWithStroke_T = Current.Compare("diacritical", "ĐĩàĈŗįŧïćâĻ", AlphaNumericIgnoreCase) = 0     '//False

	'//If stroke accent "T" is replaced with Caron accent "T", the comparison is correct:
	Dim bInvariantWithCaron_T = Invariant.Compare("diacritical", "ĐĩàĈŗįŤïćâĻ", AlphaNumericIgnoreCase) = 0  '//True
	Dim bCurrentWithCaron_T = Current.Compare("diacritical", "ĐĩàĈŗįŤïćâĻ", AlphaNumericIgnoreCase) = 0      '//True

I pulled characters for this test from here: https://docs.oracle.com/cd/E29584_01/webhelp/mdex_basicDev/src/rbdv_chars_mapping.html

**Comment by tarekgh** [comment]
@DerekZiemba the framework depends on the OS for the sorting behavior. so this is really an OS issue. 
I am CC'ing Windows guys and closing this issue here. 

@jefgen @ShawnSteele could you please track this issue in Windows side? Thanks, Tarek
