### ISSUE TITLE
System.IO.Compression.ZipFile in .Net Standard 2.0 project?

### ISSUE THREAD

**Issue by malichishti** [Microsoft/dotnet#447]
Hi,

I'm trying to add System.IO.Compression.ZipFile 4.3.0 into a .Net Standard 2.0 project, however it results into following errors:
![image](https://user-images.githubusercontent.com/17155996/28702824-feaa5cdc-73a2-11e7-8bc7-962d828d6ee2.png)

Can you please advise what is that i'm doing wrong? 

Ali

**Comment by danmosemsft** [comment]
@malichishti does this repro with the final release bits (VS 15.3 released today)?

**Comment by Petermarcu** [comment]
Closing for now. @malichishti let us know if you are still hitting this issue.
