### ISSUE TITLE
Changing internal interface breaks public base class even though it doesn't derive from interface

### ISSUE THREAD

**Issue by jabbera** [Microsoft/dotnet#457]
I know the subject of this issue sounds crazy, but it's true. If I make a change to an internal interface in an assembly it causes classes derived in **another** library to break even through **it does not, directly or indirectly, derive off the interface in any way**. There is no public api change! Not only that, but it fails with a very strange error. See: https://github.com/jabbera/InterfaceBug for a demo.

You can clearly see that: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.NoBug.cs) is internal and is only implemented by: [TroubleClass](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/TroubleClass.cs) which is also internal. The assembly does not expose internals. 

Note: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.NoBug.cs) is not Implemented by [TestBase](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/TestBase.cs)

In my derived assembly there is a class [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/master/DerivedClasses/UnrelatedClass.cs) that derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/TestBase.cs) Note again: This does not implement [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.NoBug.cs). It does however have another interface [IUnrelatedInterface](https://github.com/jabbera/InterfaceBug/blob/master/DerivedClasses/IUnrelatedInterface.cs) that has a mirror property of [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.Bug.cs)

If I rebuild my base assembly but comment out the [IToubleInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.Bug.cs#L5) property, my [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/master/DerivedClasses/UnrelatedClass.cs) fails to load with the following exception

```
Unhandled Exception: System.TypeLoadException: Method 'get_QueryContext' in type 'DerivedClasses.UnrelatedClass' from assembly 'derivedclasses, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ConsoleDriver.Program.Main()
```

This exception makes no sense. [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/master/DerivedClasses/UnrelatedClass.cs) clearly implements [IUnrelatedInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/master/DerivedClasses/IUnrelatedInterface.cs#L7) since it derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/TestBase.cs) which has an implementation [here](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/TestBase.cs#L7).

My understanding is [this change](https://github.com/jabbera/InterfaceBug/blob/master/BaseClasses/ITroubleInterface.Bug.cs#L5) should be ABI compatible. It certainly is source compatible as rebuilding my derived classes fixes the problem. I'm sure this has something to do with having duplicate interfaces with the same property, and that may seem like an anti-pattern, but this is part of a code generator so it's not as crazy as it sounds.

Windows 7/10/2008 R2 .NET 4.6.2., 4.7, 4.5.2

**Comment by jnm2** [comment]
@HaloFour you may find this interesting?

**Comment by richlander** [comment]
Closing as the most active variant of this issue is at https://github.com/dotnet/coreclr/issues/13564
