### ISSUE TITLE
Issues with store ingestion and Microsoft.Net.Native.Compiler version 1.6.3

### ISSUE THREAD

**Issue by CMartino-195** [Microsoft/dotnet#458]
Steps to reproduce

When compiling our application with Microsoft.NETCore.UniversalWindowsPlatform target version 5.3.3, it includes as a dependency Microsoft.Net.Native.Compiler version 1.6.3. The application compiles correctly without any issues, can also side-load the application to UWP devices and runs without issue.

When attempting to submit the application to the store however it fails with the error 1201. If the application is build targeting Microsoft.NETCore.UniversalWindowsPlatform version 5.2.2 however it will be accepted by the UWP store ingestion process without issue, the issue is with the native compiler version 1.6.3, as the compiler distributed with the UWP SDK allows the package to be submit without error.

Expected behavior

Ability to compile solution with package Microsoft.NETCore.UniversalWindowsPlatform (5.3.3) with dependency Microsoft.Net.Native.Compiler version 1.6.3 and submit application package to the store without encountering error 1201.

Actual behavior

When building with the package Microsoft.NETCore.UniversalWindowsPlatform (5.3.3) with dependency Microsoft.Net.Native.Compiler version 1.6.3 and submit application package to the store it is encountering error 1201, however does not encounter this issue when compiling with 5.2.2 and the ilc compiler supplied with the SDK.

**Comment by CMartino-195** [comment]
Update - known issue, being resolved in next publish.

**Comment by richlander** [comment]
Thanks. Closing the issue. Please report back or file a new issue if this is still a problem.
