### ISSUE TITLE
ubuntu 14.04 starting dotnet missing library

### ISSUE THREAD

**Issue by ljgww** [Microsoft/dotnet#460]
following: https://www.microsoft.com/net/core#linuxdebian

after step1

    $ dotnet
    Failed to load /opt/dotnet/host/fxr/1.1.0/libhostfxr.so, error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/dotnet/host/fxr/1.1.0/libhostfxr.so)

have installed: `/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19`

ubuntu offers thru software center:

    GNU Standard C++ Library v3 (development files)
    libstdc++6-4.4-dev

some libs available, which to use? (not v.3.4)

    lib32stdc++-4.8-dev - GNU Standard C++ Library v3 (development files)
    lib32stdc++6-4.7-dev - GNU Standard C++ Library v3 (development files)
    lib64stdc++-4.8-dev-powerpc-cross - GNU Standard C++ Library v3 (development files) (powerpc)
    libsfstdc++-4.8-dev-armhf-cross - GNU Standard C++ Library v3 (development files) (armhf)
    libstdc++-4.8-dev - GNU Standard C++ Library v3 (development files)
    libstdc++-4.8-dev-arm64-cross - GNU Standard C++ Library v3 (development files)
    libstdc++-4.8-dev-armhf-cross - GNU Standard C++ Library v3 (development files)
    libstdc++-4.8-dev-powerpc-cross - GNU Standard C++ Library v3 (development files)
    libstdc++-4.8-dev-ppc64el-cross - GNU Standard C++ Library v3 (development files)
    libstdc++6-4.7-dev - GNU Standard C++ Library v3 (development files)
    libx32stdc++-4.8-dev - GNU Standard C++ Library v3 (development files)
    libx32stdc++6-4.7-dev - GNU Standard C++ Library v3 (development files)
    lib64stdc++-4.8-dev - GNU Standard C++ Library v3 (development files)
    lib64stdc++6-4.7-dev - GNU Standard C++ Library v3 (development files)
    libc++-dev - LLVM C++ Standard library (development files)
    libhfstdc++6-4.7-dev-armel-cross - GNU Standard C++ Library v3 (development files) (armel)
    libsfstdc++6-4.7-dev-armhf-cross - GNU Standard C++ Library v3 (development files) (armhf)
    libstdc++6-4.4-dev - GNU Standard C++ Library v3 (development files)
    libstdc++6-4.6-dev - GNU Standard C++ Library v3 (development files)
    libstdc++6-4.7-dev-armel-cross - GNU Standard C++ Library v3 (development files)
    libstdc++6-4.7-dev-armhf-cross - GNU Standard C++ Library v3 (development files)

**Comment by ljgww** [comment]
looks like to be resolved by (cannot recreate exact step that has resolved it)

    sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get dist-upgrade

perheps by later:

    sudo apt-get install libstdc++6

At this moment (as suggested by the last step of installation):

    $ /usr/local/bin/dotnet --version
    1.0.4

(kinda expected to see 2.x.x) but :(

previous version still stays:

    $ ls -la /usr/bin/dotnet
    lrwxrwxrwx 1 root root 22 Jun  7 19:16 /usr/bin/dotnet -> ../share/dotnet/dotnet

'new' version:

     ls -la /usr/local/bin/dotnet 
     lrwxrwxrwx 1 root root 18 Aug 12 19:41 /usr/local/bin/dotnet -> /opt/dotnet/dotnet

**Comment by Petermarcu** [comment]
Looks like this was resolved. Closing.
