### ISSUE TITLE
403s on valid nuget config

### ISSUE THREAD

**Issue by patrickjamesbarry** [Microsoft/dotnet#467]
**My Environment**

- Mac - Sierra 10.12.6
- Nuget install: /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget
- NuGet Version: 4.3.0.4406
- .NET Command Line Tools (2.0.0)

Running dotnet restore, I am getting 403s when trying to resolve my dependencies. I have narrowed it down to this problem.  When using multiple sources, and using **disabledPackageSources** , this somehow breaks everything. Not only is the source that should be ignored used, no auth is sent with it.  As a workaround I am having to comment out the source in my nuget config file, but this took me a while to hunt down and is a bug.
  

> Retrying 'FindPackagesByIdAsyncCore' for source 'http://my.test.com/test/api/nuget/test-nuget-local/FindPackagesById()?id='test.alliances.common''.
>   Response status code does not indicate success: 403 (Forbidden).

To recreate issue, register 2 sources that require authentication in your nuget config file. This could be the same nuget repo/url, with different source names.  Add one of the sources to the disabledPackageSources node
```
<disabledPackageSources>
<add key="MyRepo1" value="true" />
</disabledPackageSources>
```
Register credentials for both repos..
```
<packageSourceCredentials>
    <MyRepo1>
      <add key="Username" value="username" />
      <add key="ClearTextPassword" value="pwd" />
    </MyRepo1>

    <MyRepo2>
     <add key="Username" value="username" />
      <add key="ClearTextPassword" value="pwd" />
    </MyRepo2>
</packageSourceCredentials>
```
Try to do a "dotnet restore" and watch the 403s fly by.

**Comment by Petermarcu** [comment]
Move here: https://github.com/NuGet/Home/issues/6033
