### ISSUE TITLE
Linux distro selection on dot.net/core looks bad

### ISSUE THREAD

**Issue by svick** [Microsoft/dotnet#468]
The box to select Linux distribution on https://www.microsoft.com/net/core#linuxredhat looks bad if the browser window is not wide enough.

For a wide window, it looks good:

![](https://user-images.githubusercontent.com/287848/29879975-ea818faa-8da6-11e7-83aa-66797354aee5.png)

For a narrower window, it starts looking bad, because the distribution buttons are no longer centered:

![](https://user-images.githubusercontent.com/287848/29880043-1346a0ce-8da7-11e7-97a3-4f4408b912b6.png)

And it looks even worse for a very narrow window:

![](https://user-images.githubusercontent.com/287848/29880109-3fda2016-8da7-11e7-9385-9cd064e97e45.png)

**Comment by Petermarcu** [comment]
@rowanmiller where is the right repo for this to be tracked?

**Comment by rowanmiller** [comment]
We're only a short time away from publishing a redesign of the site. This issue does not affect the redesign, so I think we can close this.

**Comment by Petermarcu** [comment]
Up to you :)
