### ISSUE TITLE
After .net 4.7 installation the webservice request timeout.

### ISSUE THREAD

**Issue by jitterbuffer** [Microsoft/dotnet#469]
We have an application, which makes a webservice request to our application server.

The webservice request were working fine with .net 4.5 and 4.6, however after upgrading .net to 4.7 the same webservice request times out. We have not done any code changes in our application between upgrade to .net 4.6 and 4.7.

The webservice request timeout is set 15 seconds, however if we set to 30 seconds the webservice request is successful. Not able to understand what is missing that a longer time makes request successful.

Just for reference here is code snippet, we set security protocol on the startup of application.

protected override void OnStartup(StartupEventArgs e)
    {
        base.OnStartup(e);

        System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
        ServicePointManager.ServerCertificateValidationCallback += this.RemoteCertificateValidationCallback;
        ......
        .....
   }

**Comment by richlander** [comment]
PTAL @davidsh

**Comment by davidsh** [comment]
There is not enough information to diagnose this.  Please attach a small repro solution that shows the problem.  Also, attaching Wireshark and System.Net Traces would be useful as well.

**Comment by richlander** [comment]
Can you share more info @jitterbuffer ?

**Comment by jitterbuffer** [comment]
It was our customer issue and they shared the .net 4.7 update fixed the issue. We went to find the .net update information but customer has not replied yet. 
I believe, it was .net issue and recent update fixed it. Lets close this issue on that note.
