### ISSUE TITLE
DataTable serialization incorrectly depends on the Current Culture's Number Format Info

### ISSUE THREAD

**Issue by logiclrd** [Microsoft/dotnet#471]
We have a client reporting problems with our application because they have configured the Windows Region & Language settings to use the string `"()"` as the negative sign for number formatting. This seems to be traceable back to the fact that the `DataTable` in question has a custom schema that specifies negative values for the autoincrement seed & step. When `DataTable` is trying to deserialize the schema, it assumes that the quantity negative one should look like `"()1"` and therefore does not recognize the `"-1"` in the XML data. Some quick testing reveals that a `DataTable` serialized under these conditions produces correct XML representing `"-1"` as `"-1"`; this issue affects only deserialization.

This issue only comes up when properties in the table's schema have negative values. Negative values in the row data do not trigger the problem.

Our client has informed us that this configuration is deliberate and desired. The only control we have over `DataTable` deserialization seems to be to override the entire process's `CultureInfo.CurrentCulture`, which in turn means that reports produced by our software will not use the `"()1"` format the client desires. There does not appear to be a way to work around this issue only for `DataTable` serialization/deserialization and without affecting other number formatting in the application.

The following code reproduces the issue:
```
            var serializer = new BinaryFormatter();

            var table = new DataTable();

            table.Columns.Add(
                new DataColumn("RowID", typeof(int))
                {
                    AutoIncrement = true,
                    AutoIncrementSeed = -1, // These lines produce attributes within the schema portion of the underlying XML representation of the DataTable with the value "-1".
                    AutoIncrementStep = -1,
                });

            table.Columns.Add("Value", typeof(string));

            table.Rows.Add(1, "Test");
            table.Rows.Add(2, "Data");

            var buffer = new MemoryStream();

            serializer.Serialize(buffer, table);

            CultureInfo.CurrentCulture =
                new CultureInfo("en-US")
                {
                    NumberFormat =
                        new NumberFormatInfo()
                        {
                            NegativeSign = "()" // DataTable's deserialization incorrectly uses this to ascertain the number format for deserializing the schema properties.
                        }
                };

            buffer.Position = 0;

            var table2 = (DataTable)serializer.Deserialize(buffer); // System.Exception: "-1 is not a valid value for Int64."
```

**Comment by logiclrd** [comment]
This issue was also reported here:

https://connect.microsoft.com/VisualStudio/feedback/details/3140181

My coworkers pointed out GitHub issues as another way to report the issue.

**Comment by richlander** [comment]
PTAL @terrajobst @weshaggard

**Comment by weshaggard** [comment]
@danmosemsft @ViktorHofer couuld you guys take a look?

**Comment by ViktorHofer** [comment]
Moved. Whoever has permissions, please close the issue.
