### ISSUE TITLE
dotnet commands modify the terminal's keypad/cursor behavior, but does not restore it on exit

### ISSUE THREAD

**Issue by osklil** [microsoft/dotnet#472]
Using GNU Screen's logging feature I was able to determine that most dotnet commands writes some escape sequences to modify the terminal on start. However, the terminal is not restored on exit.

E.g. output from "dotnet publish" (^[ is ascii 27, everything else as is):

^[[?1h^[=MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

The escape sequence ^[= ("Enter Alternative Keypad Mode") should probably be matched by ^[>("Exit Alternate Keypad Mode", also known as "Enter Numeric Keypad Mode"). And ^[[?1h ("Set cursor key to Application") should be matched by ^[[?1l ("Set cursor key to Cursor").

Regards,

Oskar Liljeblad (oskar@osk.mine.nu)

**Comment by richlander** [comment]
PTAL @livarcocc @kathleendollard

**Comment by richlander** [comment]
Can you give us more insight into what you are asking for? We haven't had similar feedback before.

**Comment by KathleenDollard** [comment]
@osklil 

I'm sorry we're having trouble following you here. Are you saying that the output after a command like dotnet publish contains an extra character? 

What OS and editor are you using to help us reproduce?

Thanks!

**Comment by osklil** [comment]
@KathleenDollard 
Yes, the output from "dotnet" includes escape sequences and control characters, for example to color the text appropriately. Some commands, for example "dotnet publish", output "^[=" to "enter alternative keypad mode". I don't know why this is done, or where (e.g. by an external library). Also, the escape sequence "^[=" may be specific for my terminal, but that's not what is relevant here. What is relevant is that "dotnet" does not restore the default mode on exit. It should do this by issuing the escape sequence for  "exit alternative keypad mode". If it is not issued, the keypad will be left in a non-default state.

**Comment by Frassle** [comment]
This is still happening. If I run "read" and push the four arrow keys I get "^[[A^[[B^[[C^[[D". If I run dotnet build and then run read and push the arrow keys again I get "^[OA^[OB^[OC^[OD". I have to run "tput rmkx" to return my terminal to normal.

This mode change causes some other programs to fail due to the unexpected escape sequences from arrow key inputs.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
