### ISSUE TITLE
.NET CLI Update Available Notification

### ISSUE THREAD

**Issue by khalidabuhakmeh** [Microsoft/dotnet#475]
On an interval, the .NET CLI tooling should check to see if there is a later version than the one you are currently using and inform you. Similar to the behavior exhibited by `npm`.

![image](https://user-images.githubusercontent.com/228256/30241698-95d9b2ae-9556-11e7-8939-9f01aa0ce2ee.png)

**Comment by svick** [comment]
One problem with this is that the .Net CLI does not have a way to update itself, there is nothing similar to the `npm i -g npm` shown above.

**Comment by Petermarcu** [comment]
This is a good feature request and something that has been considered (both the update check and the ability to update itself). Can you repost this on the dotnet/cli repo where the folks working on the CLI are more likely to engage?
