### ISSUE TITLE
Install Autodesk on Windows 10 Creators build

### ISSUE THREAD

**Issue by patrickmanson** [Microsoft/dotnet#491]
I have just got a new laptop preinstalled with windows 10 creators build. This build has .net 4.7 built in which i understand cannot be removed. Autodesk 2018 products will not install on .net 4.7. they require .net 4.6 but there is no way of installing that on this release. Rolling back to a previous version of windows is not an option for me. Will the .net 4.7.1 release provide any relief for this? Any other way of installing .net 4.6?

Thanks in advance.

**Comment by merriemcgaw** [comment]
Are you experiencing an install failure related to .NET version? Autodesk products require a minimum version of .NET 4.6 but should install fine on later versions of the Framework.  For answers specific to Autodesk products I would recommend their Install and Licensing community forums you can find here: [https://forums.autodesk.com/t5/installation-and-licensing/ct-p/3001](https://forums.autodesk.com/t5/installation-and-licensing/ct-p/3001).

**Comment by patrickmanson** [comment]
Hi merrie, yes it is a install failure. Autocad 2018 products require .net 4.6 not 4.7. I have read all that I can and have been directed from Autodesk to Microsoft as Autodesk believe that this is a microsoft issue, not an Autodesk one. Autocad 2018 will not install on the newer versions of .net.

Any other help you could provide would be most appreciated.

Cheers, Patrick

**Comment by merriemcgaw** [comment]
I would need to see the install logs for AutoCAD 2018 to try to understand the issue. If you can collect the logs and attach them to the this thread that will be helpful. 

This [thread ](https://forums.autodesk.com/t5/installation-licensing/creators-update-net-4-7-and-2018-products/m-p/7186886/highlight/true#M182344) on AutoDesks's site shows that some people are installing successfully installing (though running into other issues with 4.7 which are being addressed).

**Comment by patrickmanson** [comment]
Here is the log file.

I had read that post and tried the install options in there. I am not using a deployment so was not sure how to run the elevated command prompt or even if that would make any difference.

cheers

**Comment by merriemcgaw** [comment]
It looks like the log file didn't attach properly, I'm not able to locate it.  You can try sending to my Microsoft address. mmcgaw (at) Microsoft.com.

To get an elevated command prompt I type "cmd" into the search box on the taskbar.  Then when command prompt appears right click and choose Run as Administrator.

~Merrie

**Comment by richlander** [comment]
@patrickmanson Please share the log file in email. We'd like to help you. Otherwise, we'll close the issue.

**Comment by richlander** [comment]
Can you share the log file @patrickmanson ?
