### ISSUE TITLE
Documentation of RyuJIT optimizations

### ISSUE THREAD

**Issue by devsko** [Microsoft/dotnet#498]
It seems that several RyuJIT optimizations are implemented in 4.7.1 (or a earlier version) but I couldn't find anything about it in the release notes. 
Is the information available which optimization is implemented in which .NET version? 
(I am especially interested in System.Span<T> and the types in System.Numerics.Vector)

**Comment by Petermarcu** [comment]
@RussKeldorph

**Comment by RussKeldorph** [comment]
I believe this is covered in dotnet/coreclr#14250.  Note that Span<T> isn't part of .NET, though you can play with it using prerelease .NET Core.

**Comment by Petermarcu** [comment]
@devsko does that answer your question?

**Comment by Petermarcu** [comment]
Let us know if there are any more questions. Seems like this may have covered it.
