### ISSUE TITLE
Getting MSBuild properties from the new project format with the Visual Studio extension

### ISSUE THREAD

**Issue by ionoy** [Microsoft/dotnet#504]
I have an extension that needs to read MSBuild properties. 

Code looks like this:

```csharp
Project project = GetProject();
var intermediatePath = project.ConfigurationManager.ActiveConfiguration.Properties.Item("IntermediatePath");
```

It worked well with the old format, but with the new format, there is no `IntermediatePath` or `IntermediateOutputPath` or any property containing `obj` for that matter.

How do I get the intermediate output path with the new project format?

**Comment by jnm2** [comment]
Had pretty much the same question at https://github.com/Microsoft/msbuild/issues/1875.

**Comment by ionoy** [comment]
Maybe I'm misunderstanding something, but my issue is that I don't have all the properties loaded. There is no problem with SDK since VS/DTE takes care of it.

**Comment by jnm2** [comment]
Oh sorry, my bad.

**Comment by Petermarcu** [comment]
Issue moved to [Microsoft/msbuild #2633](https://github.com/Microsoft/msbuild/issues/2633) via [**ZenHub**](https://www.zenhub.com/)
