### ISSUE TITLE
Missing changelog for .NET Native 1.7 (UWP 5.4.1)

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/dotnet#518]
.NET Native for UWP 5.4.1 was [released few days ago to NuGet](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/5.4.1), but the changelog mentions only [5.4.0](https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native1.7/README.md) and [6.0.1](https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native2.0/README.md).

Expected solution: There should be changelog for .NET Native 1.7 (UWP 5.4.1) as well.

**Comment by Petermarcu** [comment]
@MeiChin-Tsai @joshfree @russellhadley

**Comment by joshfree** [comment]
Thanks for filing this issue.  Fixed with https://github.com/Microsoft/dotnet/commit/2a0823b96d7a78145c2de560873a30eed11c99c5
