### ISSUE TITLE
You must add a reference to assembly netstandard errors

### ISSUE THREAD

**Issue by fahadabdulaziz** [Microsoft/dotnet#527]
Hi,

After targeting .Net Framework 4.7.1, in many projects referencing net standard libraries. I get these errors:
![errs](https://user-images.githubusercontent.com/5483584/31769585-f06cdab6-b4dc-11e7-9a58-f6d3f52341da.png)

`csharp
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
`

Though I all the projects including that targeting net471 are building successfully!

Any thoughts ?

**Comment by Petermarcu** [comment]
Moved this issue here: https://github.com/dotnet/standard/issues/542

**Comment by fahadabdulaziz** [comment]
@Petermarcu Thank you
