### ISSUE TITLE
Dev Center Certification Fails for Microsoft.NETCore.UniversalWindowsPlatform 6.0.1

### ISSUE THREAD

**Issue by EdiWang** [Microsoft/dotnet#528]
**Steps to Reproducte:**

1. Upgrade UWP's nuget package to Microsoft.NETCore.UniversalWindowsPlatform 6.0.1
2. Apply Acrylic Brush on any UI element (IMPORTANT, PLEASE APPLY, OR WONT REPRODUCE ISSUE)
3. Target 16299 for both target and min version.
4. Generate an app package to upload to store

**Actual Behaviour:**

Certification Failed
> PI ClearCommBreak in kernel32.dll is not supported for this application type. System.IO.Ports.dll calls this API.
> API ClearCommError in kernel32.dll is not supported for this application type. System.IO.Ports.dll calls this API.
> .... etc.

**Workaround**

Downgrade the package to 5.4.1 will fix the problem. 

**Note**

I don't know if the dev center is not ready for verify 6.x uwp package, or it is the package itself have problem?

FYI the question on MSDN forum https://social.msdn.microsoft.com/Forums/en-US/b7355d61-cbf9-42e6-a9eb-44ffa144aa1f/rs31709certification-failure-due-to-unsupported-apis-after-upgrading-to-16299-sdk?forum=wpsubmit

**Comment by Petermarcu** [comment]
Moved this here: https://github.com/dotnet/corefx/issues/24754
