### ISSUE TITLE
Can I build normal TCP/UDP server and HTTP server and WebSocket in a single asp.net core application?

### ISSUE THREAD

**Issue by 19317362** [Microsoft/dotnet#533]
I've checked the document. HTTP and WebSocket in a single asp.net core is ready.
Can I add TCP/UDP server in it? 
I want try Dotnetty + asp.net core.

Is this possiable?

**Comment by richlander** [comment]
PTAL @terrajobst @weshaggard

**Comment by 19317362** [comment]
I want try Dotnetty + asp.net core.

**Comment by Kulak** [comment]
I have the same question.  Theoretically it shall be possible.

**Comment by terrajobst** [comment]
@davidfowl @davidsh

**Comment by davidsh** [comment]
>Can I build normal TCP/UDP server

What does "normal" mean in this context?  

In term of a .NET Core application, one can certainly combine the various networking APIs for TCP/UDP, HTTP and WebSocket in a single application.

**Comment by davidfowl** [comment]
Yes you can do it in a single application there's no single application model that encompasses that. ASP.NET doesn't interact with dotnetty but you can certainly use both of them in the same application.

**Comment by Kulak** [comment]
I agree.  I just put a UDP listener and it works.

**Comment by terrajobst** [comment]
Closing as it seems we answered the question. @19317362 please free to reopen if we didn't.
