### ISSUE TITLE
My  Application crashes with “System.AccessViolationException” while launching it in Win10 2017 machine

### ISSUE THREAD

**Issue by KSaravana** [microsoft/dotnet#537]
I am getting this error when loading the third party library component to my application but the same application(crashing application) is integrated with another application there it is working fine though it uses the same third party component.
For winform (C# code) , am using native C++ dll( This is third party DLL) at this point of time my application crashes with "System.AccessViolationException". (Refer above for stack trace) .  Recently got updated version of  3rd party DLL, but it works fine for WIN7 machine but crashing for win10 2017(1703 and 1709 build versions) consistently. 

Note: Issues is reproducible always in windows 10 machine. The application is working fine in Windows7, issues observed only on win10 2017.(Build no 1703).

Please guide me to resolve this issue.

Event Viewer Stack trace: Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr) at System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control.DefWndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control.WmCreate(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef) at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

After Every crash the memory dump is created in below location:C:\ProgramData\Microsoft\Windows\WER\ReportQueue\ How to Analyze this memory dump logs? I have checked the report.txt file in this crash dump and observed that the last loaded dll was diasymreader.dll,Can I get any clue to proceed with this ?LoadedModule[162]=C:\Windows\Microsoft.NET\Framework\v4.0.3‌​0319\diasymreader.dl‌​l

**Comment by KSaravana** [comment]
After Every crash the memory dump is created in below location:C:\ProgramData\Microsoft\Windows\WER\ReportQueue\ How to Analyze this memory dump logs? I have checked the report.txt file in this crash dump and observed that the last loaded dll was diasymreader.dll,Can I get any clue to proceed with this ?LoadedModule[162]=C:\Windows\Microsoft.NET\Framework\v4.0.3‌​0319\diasymreader.dl‌​l

**Comment by Tanya-Solyanik** [comment]
Hi KSaravana, is there any chance you could share a sample application that repros this crash? Is the 3rd party library public?

**Comment by richlander** [comment]
Hi @KSaravana ... We are going to need more information. Feel free to mail me at rlander@ms if you would like.

**Comment by richlander** [comment]
Any more info @KSaravana ?

**Comment by kalaskarsanket** [comment]
This issue has not got any input for long time and we have changed were issues are tracked. If this is still an issue kindly raise a new issue in the appropriate repo as mentioned in [dotnet/1275](https://github.com/microsoft/dotnet/issues/1275)
