### ISSUE TITLE
Windows 10 WPF Maximised Window Touch Keyboard Support

### ISSUE THREAD

**Issue by james1301** [Microsoft/dotnet#540]
In Windows 8.1 a WPF window would be resized when using the Touch Keyboard (so that it would not appear over the top of the application and you could always see the text box you were entering into), when it was maximised or not. In Windows 10 it only seems to do this when a window is not maximised?

I presumed this was a .net related thing rather than exact Windows Version. What is the reason for this and is this something that is going to be fixed? This can also be seen in Windows 10 by just using a File Explorer maximised or not.

Thanks,
James

**Comment by richlander** [comment]
I was directed to this sample. Does that help?

https://github.com/Microsoft/WPF-Samples/tree/master/Input%20and%20Commands/TouchKeyboard/TouchKeyboardNotifier

**Comment by james1301** [comment]
Thanks that is a good workaround. But ideally wanting actual feedback to this issue and what is happening with it. I don't really want an extra layer in between my controls really, or to have to deal with any other issues using this might bring up. I don't believe this should really be a problem, especially as it's an issue with standard windows apps, like File Explorer. This looks bad on Windows, not just to our clients.

**Comment by richlander** [comment]
I talked to the team again. They tell me that this experience is a different in Windows 10, as you've noticed. We've decided to leave this particular behavior up to either the operating system or to developers. It isn't obvious that we should be making a change here given the larger change in Windows.

**Comment by james1301** [comment]
Thanks for your response. Fair enough I can see why you might not want to change this behaviour, due to Windows different behaviours. 

Would be useful though if you built it into your standard Window or something though.

**Comment by richlander** [comment]
Thanks. Closing issue since it seems like the original issue is now understood.
