### ISSUE TITLE
DefaultIfEmpty ignors default value if Sum linq used

### ISSUE THREAD

**Issue by EAlhovik** [Microsoft/dotnet#549]
# General

.NET 4.5 or .NET Core version: 2.0
OS version: any
Visual Studio any

# Code to reproduce
```
using System;
using System.Collections.Generic;
using System.Linq;
					
public class Program
{
	public static void Main()
	{
		var emptyList = new List<int?>();

		Console.WriteLine(emptyList.DefaultIfEmpty(null).Sum());
	}
}
```

# Expected results
Sum method returns null and noting in console.

# Actual results
0 number in console

**Comment by jnm2** [comment]
`new List<int?> { null }.Sum()` returns `0`, so you would expect `new List<int?>().DefaultIfEmpty(null).Sum()` to behave identically (as indeed it does).

Nulls are skipped, but that doesn't mean that totaling didn't happen. The total is initialized to zero and then for each item that is not null, the amount is added. Even `new List<int?> { }.Sum()` returns `0`.

**Comment by EAlhovik** [comment]
There are no exceptions of the rule in [documentation](https://msdn.microsoft.com/en-us/library/bb355419(v=vs.110).aspx)

> Returns the specified value in a singleton collection if the sequence is empty.

In this way the test below with empty sequence should always return the default value.

```
	[TestCase(1)]
	[TestCase(5)]
	[TestCase(null)]
	public void DefaultIfEmpty_OutputsDefaulValues(int? defaultValue)
	{
		var actualResult = new List<int?>().DefaultIfEmpty(defaultValue).Sum();
		
		Assert.AreEqual(defaultValue, actualResult);
	}
```

**Comment by jnm2** [comment]
Sure, `DefaultIfEmpty` returns the default value which is `null`. Then you feed that into `.Sum()` which ignores nulls.

The documentation does not say that `Sum` returns the default value if the collection is empty. `Sum` is not named `DefaultIfEmpty`. =D

**Comment by richlander** [comment]
PTAL @terrajobst @weshaggard

**Comment by svick** [comment]
The thing I find confusing is that the return type of `Sum(IEnumerable<int?>)` is `int?`, but it will never return `null`. Though I don't think there is anything that can be done about that now.

**Comment by EAlhovik** [comment]
Thanks! Now I think it could be closed

**Comment by jnm2** [comment]
@svick I think it's because it needed to match the `IQuerable.Sum` return type. With IQueryable they probably wanted to leave the door open for other semantics, such as when Entity Framework translates to SQL and executes via a database engine. T-SQL's `sum` can return null.
