### ISSUE TITLE
.NET 4.7.1 installer crashes on server core

### ISSUE THREAD

**Issue by CJHarmath** [microsoft/dotnet#551]
How to repro:
Grab a Server Core 2016 and just run the installer as is on an interactive session by running the setup exe with no parameters.

Expected result: 
Either the install works or at least detects and warns that you should only run in quiet mode on server core.
preferably, it should be smart about running on core and just do it's job to install in quiet mode, but not crash.

work around: run the installer in quiet mode ( -q switch )

Please do test the installer on server core as well with defaults and handle this use case. 
Some of us hate the idea of GUI's on servers. Unfortunately we are a minority, but we are here and won't give up!

**Comment by Petermarcu** [comment]
@merriemcgaw

**Comment by richlander** [comment]
I sent mail to the team to ask for help / insight.

**Comment by Taomyn** [comment]
Still a problem installing v4.8 on core servers - there is no warning in the GUI, you just get to the "Install" button at the licence agreement, and it simply closes down. Took finding this issue in Github to find the solution and use "-q" on the installer.

I do recommend the following in a command-prompt (not Powershell) so you get an idea when it's completed:

`start /wait ndp48-x86-x64-allos-enu.exe /q /norestart`

It won't instantly come back but waits for the installer to conclude, and won't reboot automatically.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
