### ISSUE TITLE
HTTP runtime cache memory monitor fails to start under certain conditions in 4.7.1

### ISSUE THREAD

**Issue by mrahl** [microsoft/dotnet#552]
I think I have found __two issues in LowPhysicalMemoryMonitor__ that prevent the periodic memory monitor / cache scavenging thread from running. That means memory usage can go beyond configured thresholds, and beyond threshold for Proactive Auto Heal in Azure Web Apps, causing unnecessary recycles.

__Issue 1: Timer is not started if memory pressure at startup is at certain level and PrivateBytesPollTime has default value__

If the memory usage at the time of application startup fulfills the condition PressureHigh > PressureLast > PressureLow / 2, the Timer driving the periodic check/scavenging is never started (it is instantiated as stopped).

This happens because LowPhysicalMemoryMonitor.AdjustTimer (called from LowPhysicalMemoryMonitor.Start to start the timer) in this scenario determines that no update is required to the timer interval, unless LowPhysicalMemoryMonitor.s_pollInterval is less than 30 seconds. The s_pollInterval is initialized according to the CacheSection.PrivateBytesPollTime setting, which defaults to 2 minutes.

The timer therefore remains stopped, unless you apply the workaround: Setting PrivateBytesPollTime to less than 30 seconds.

__Issue 2: Timer is suddenly stopped if PercentagePhysicalMemoryUsedLimit has default value__

If no value is specified for for CacheSection.PercentagePhysicalMemoryUsedLimit, LowPhysicalMemoryMonitor will not initialize the s_pollInterval field with any value. It will therefore be 0, which will cause the Timer to stop when the periodic check calls LowPhysicalMemoryMonitor.AdjustTimer and the condition PressureHigh > PressureLast > PressureLow / 2 is again met.

**Comment by richlander** [comment]
@lt72, @brianrob Can you take a look?

**Comment by brianrob** [comment]
This looks like an issue in System.Web.Hosting.

@sajayantony, do you know who a good contact for this is?

**Comment by HongGit** [comment]
ASP.NET has bug opened tracking this issue, [523523](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=523523&_a=edit&triage=true).

**Comment by richlander** [comment]
The link above is to the private Microsoft bug tracker. @HongGit is there a public GH issue you can use or do you want this one to be that?

**Comment by HongGit** [comment]
Let's keep this one.

**Comment by leecow** [comment]
Looks like the mentioned issues are possibly fixed. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
