### ISSUE TITLE
NET SDKs  Developer Pack and Runtime, Supported Operating Systems and Visual Studio

### ISSUE THREAD

**Issue by kiquenet** [microsoft/dotnet#564]
IMHO, more clearly if https://www.microsoft.com/net/download/visual-studio-sdks if it will appears table with Supported Operating Systems for each one Microsoft .NET Framework X.x.x and with Supported Versions of Visual Studio.

Suggestions:
.NET SDKs (.Net Framework o .NET Core) : Developer Pack and Runtime, and Supported Operating Systems and Supported Versions of Visual Studio.

**Comment by richlander** [comment]
We are planning on fixing this. @rowanmiller is working on this.

**Comment by rowanmiller** [comment]
Listing what's included in VS is already live. We have an offline email thread to work out if anything else needs added.

**Comment by richlander** [comment]
What do you think @kiquenet ?

**Comment by kiquenet** [comment]
offline email thread  ? 

 "Supportatbility Matrix" with .NET SDKs , Operating Systems , and Visual Studio versions.

Maybe useful any "Supportatbility Matrix" for Visual Studio - Team Foundation Server, for example, like a Exchange Server Supportability Matrix
https://technet.microsoft.com/en-us/library/ff728623%28v=exchg.150%29.aspx?f=255&MSPPError=-2147217396

**Comment by leecow** [comment]
Sounds like this may have been resolved. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
