### ISSUE TITLE
.net 4.5.2 - w3p crash with .net web api

### ISSUE THREAD

**Issue by sannaroby** [microsoft/dotnet#565]
We've a problem with our .net web API 2 web services hosted on IIS-7 (windows server 2008 R2. net 4.5.2). Sometimes the w3p process crashes. We can see this from the server event viewer (see discussion [here](https://forums.asp.net/post/6177999.aspx)):

    An unhandled exception occurred and the process was terminated.

    Application ID: /LM/W3SVC/57/ROOT

    Process ID: 7340

    Exception: System.ArgumentException

    Message: Value does not fall within the expected range.

    StackTrace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
    at System.Web.Hosting.IIS7WorkerRequest.GetUserToken()
    at System.Web.HttpContext.get_ClientIdentityToken()
    at System.Web.HttpContext.get_ImpersonationToken()
    at System.Web.ClientImpersonationContext.Start(HttpContext context, Boolean throwOnError)
    at System.Web.ThreadContext.EnterExecutionContext()
    at System.Web.Hosting.AspNetHostExecutionContextManager.SetHostExecutionContext(HostExecutionContext hostExecutionContext)
    at System.Threading.HostExecutionContextManager.SetHostExecutionContextInternal(HostExecutionContext hostContext)
    at System.Threading.ExecutionContext.SetExecutionContext(ExecutionContext executionContext, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
    at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

The W3P crashes when we call the remote methods below (not every time). In this method, we read the requested file (image) from a nas hard disk, we scale it (see ScaleImage method) and we return it to the client.

     public async Task<HttpResponseMessage> GetPhoto(string id, ImageResolutionType resolutionType)
     {
         string fileFullPath = this.GetFileFullPath(id);
         string fileFormat = this.GetFileFormat(fileFullPath);

         HttpResponseMessage result = this.Request.CreateResponse();
         var allBytes = this.ScaleImage(fileFullPath, (int)resolutionType);
         result.Content = new ByteArrayContent(allBytes);
         result.Content.Headers.ContentType = new MediaTypeHeaderValue(fileFormat);
         result.Content.Headers.ContentDisposition = new ContentDispositionHeaderValue("attachment"){ 
         FileName = Path.GetFileName(fileFullPath)};

         return result;
    }
    private byte[] ScaleImage(string path, int maxWidth)
     {
        byte[] data = null;

        using (var image = Image.FromFile(path))
        {
            int width = image.Width;
            int height = image.Height;
            int newHeight = height;
            int newWidth = width;

            if (width > maxWidth)
            {
                double ratio = (double)width / (double)height;
                newWidth = maxWidth;
                newHeight = (int)(newWidth / ratio);
            }

            using (var ms = new MemoryStream())
            {
                using (var newImage = new Bitmap(newWidth, newHeight))
                {
                    using (var graphics = Graphics.FromImage(newImage))
                        graphics.DrawImage(image, 0, 0, newWidth, newHeight);

                    newImage.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                    data = ms.ToArray();
                }
            }
        }

        return data;
    }

We have logs for each method that could be called by clients, at the start and at the end of each methods. This logs has been omitted in the posted code in order to avoid redundant code. When the w3p crashes there is no log for the GetPhoto method. It seems that the request fail before to arrive to the GetPhoto method or after to have processed the request.

**Comment by HongGit** [comment]
@sannaroby is this the same issue as [this](https://forums.asp.net/t/2132070.aspx)?  If not, could you please share the full call stack?  It would be great if you could provide a simple repro app or repro steps for us to investigate further.  Or you may want to collect the full crash dump follow [this blog](https://blogs.msdn.microsoft.com/webtopics/2009/11/25/how-to-collect-a-crash-dump-of-an-iis-worker-process-on-iis-7-0-and-above/).

**Comment by sannaroby** [comment]
Yes, it's the same problem of [here](https://forums.asp.net/t/2132070.aspx) (I'm the one who wrote that post). I don't have a simple repro app, but the code is that indicated in the post. We have logs for each method that could be called by clients, at the start and at the end of each methods. This logs has been omitted in the posted code in order to avoid redundant code. When the w3p crashes there is no log for the GetPhoto method. It seems that the request fail before to arrive to the GetPhoto method or after to have processed the request.

**Comment by sannaroby** [comment]
@HongGit I've added [here](https://www.dropbox.com/s/xdfp18vkhfuzsu9/report.mht?dl=0) a DebugDiag Analysis Report.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
