### ISSUE TITLE
Missing changelog for .NET Native 2.0 (UWP 6.0.2)

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/dotnet#569]
[.NET Native for UWP 6.0.2 was released few days ago to NuGet](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.0.2), but the changelog mentions only 6.0.1.

Expected solution: There should be changelog for .NET Native 2.0 (UWP 6.0.2) as well.

**Comment by HollyAM** [comment]
It is there now!

**Comment by richlander** [comment]
See: https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native2.0/README.md
