### ISSUE TITLE
BufferedOutputStream.write(tmp, 0, len) throws java.net.SocketException while copying zip_file with size more than 2GB

### ISSUE THREAD

**Issue by KSaravana** [Microsoft/dotnet#570]
byte[] tmp = new byte[4096];
		InputStream instream = super.getSource().createInputStream();
		try {
			int len;
			while ((len = instream.read(tmp)) >= 0) {
				bufferedOutputStream.write(tmp, 0, len);
			}
		} finally {
			instream.close();
		}
I am trying to copy a zip_File which has more than 2 GB to a remote machine,using bufferedOutputStream.write(byte[] b, int off, int len) method to write the data. getting the following Exception :
    java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source) 
Can you help me to get rid of this exception?

**Comment by svick** [comment]
How is this related to .Net?

**Comment by richlander** [comment]
This looks like a Java issue. This repo is for .NET.
