### ISSUE TITLE
thread contention at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation

### ISSUE THREAD

**Issue by AndresPabloGomez** [Microsoft/dotnet#571]
Please change the method GetTypeInformation to use ReaderWriterLockSlim or something else, to access typeNameCache dictionary.

**Comment by msisterna** [comment]
I have the same problem.

**Comment by Petermarcu** [comment]
@danmosemsft can you take a look and move this to another repo if its better tracked there?

**Comment by danmosemsft** [comment]
Moved to https://github.com/dotnet/corefx/issues/25529
