### ISSUE TITLE
WPF - Manipulation misbehaviour - Windows 10 Anniversy Update and successors

### ISSUE THREAD

**Issue by Clemani** [microsoft/dotnet#575]
Very often, when i want to do a pinch zoom with 2 fingers e.DeltaManipulation.Scale.X and e.DeltaManipulation.Scale.Y is 1.0 ...
but e.DeltaManipulation.Translation.X or e.DeltaManipulation.Translation.Y is <> 1.0 instead.

I have attached a sample app, you can reproduce the error with it.
The test app does not actually perform scroll or zoom, it displays the triggered supposed action in the top of the form.
Try scrolling and zoom in/out with the fingers, very often you can see that the Manipulation event "fires" scroll instead zoom.

I can reproduce the error on MS Surface Pro 4 Tablet.

The error occurs with Windows 10 Anniversy Update, Creators Spring and Fall.
I thought first it's also a Fall Update issue, but it seems to happen on all Windows 10 versions.
The error does not happen on Windows 8.1, .NET 4.6.2

[ManipulationScrollZoomTest.zip](https://github.com/Microsoft/dotnet/files/1519678/ManipulationScrollZoomTest.zip)

**Comment by Clemani** [comment]
This error seems to not happen on Lenovo ideapad MIIX 310 (1280x800 pixel), at least it works very much more reliable in a quick short test.
I guess it's an issue with HighDPI devices, or a MS Surface specific problem.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
