### ISSUE TITLE
System.ComponentModel.Annotations assembly not found error again

### ISSUE THREAD

**Issue by codearoo** [Microsoft/dotnet#584]
I don't know which of the many Microsoft teams to post this with.
Last time we updated our NuGet packages, we had this error and now when we just did it recently it happened again. We updated to 4.4.0. 
And the project file of a particular Test project type ends up with this:
`    <Reference Include="System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.ComponentModel.Annotations.4.4.0\lib\net461\System.ComponentModel.Annotations.dll</HintPath>
    </Reference>
`
And it complains it can't find ver 4.2.0.0.
But when I change it manually it doesn't seem to help.. it now fails to find that version. I know previously there was something really messed up like it was actually 4.0.2.0 not 4.2.0.0 or whatever.. so we had to manually fix the project or app.config file. I have no idea how to find that version number now (Windows 10 details of a DLL no longer see to show assembly versions, just file version which is 4.6.25519.3.

What the heck is going on? When is this absurd thing going to get fixed? Lots of posts about this weird versioning problem..  it's as if the old VB6 days are back with DLL hell.

I don't understand why anything needs to show up in app.config anyway for these DLL references when it's all done through NuGet. What a mess.
I'm going to try with today's update of 4.4.1 .. 1st attempt was that all kinds of references failed. Undoing that and will try again later.

**Comment by codearoo** [comment]
So I had to manually add 
`      <dependentAssembly>
        <assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
`
To the app.config file of the project to make it work. But this test project has been working for months and this ComponentModel.Annotation section in the app.config was NOT in there. I just verified in our repo history.

**Comment by richlander** [comment]
PTAL @terrajobst  @AlexGhiondea

**Comment by StefanoD** [comment]
Same problem here.

**Comment by camainc** [comment]
Same problem here

**Comment by ericnewton76** [comment]
We are back to Guid DLL hell due to the restrictive versioning scheme used by fusion. It simply must be changed to semver without needing those binding redirects.  

It’s time for the net assembly loader to be configurable and allow for looser semver strategies for assembly binding.

**Comment by terrajobst** [comment]
As @ericnewton76 said, these problems are a result of the .NET Framework binding policy, which is exact match only. Everything else requires binding redirects. Thankfully, since .NET Framework 4.5.2 you can configure your project to [automatically produce the correct binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection) without having to mess with your `app.config` file.

> It’s time for the net assembly loader to be configurable and allow for looser semver strategies for assembly binding

All .NET binders that were built after .NET Framework behave this way (Mono, Silverlight, Phone, Xamarin, .NET Core, etc). We're extremely unlikely to add this feature to the .NET Framework due to cost, complexity, and backwards-compatibility concerns.

**Comment by terrajobst** [comment]
@codearoo

Given my earlier response, I'm going to close this.

**Comment by camainc** [comment]
>  Thankfully, since .NET Framework 4.5.2 you can configure your project to automatically produce the correct binding redirects without having to mess with your app.config file.

Well, I tried that first and unfortunately it did not work for me. I had to add the entry to my web.config.

**Comment by terrajobst** [comment]
@camainc 

Unfortunately, automatic binding redirects don't work for `web.config` (as the build doesn't produce a config file; instead, it uses the one from your project directly). However, you don't have to hand-edit the config file. When binding conflicts occur, you'll get a warning in the Error List. You can double click the warning which will then prompt you to confirm that you want the binding redirects added to your project file.

**Comment by camainc** [comment]
" When binding conflicts occur, you'll get a warning in the Error List. "

I was getting a build error, which would not let me build the project or solution until I resolved that issue.

**Comment by camainc** [comment]
Here are the details:

Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) occurred

**Comment by Izzmo** [comment]
Any updates?

**Comment by terrajobst** [comment]
My comments from above are still the current state of the world. .NET Framework projects don't support automatic binding redirects, you have to manually add them to your `web.config`, but usually you'll get warnings you can double click and the will add the correct binding entries in your `web.config` file.

**Comment by RCristiam** [comment]
> 
> 
> My comments from above are still the current state of the world. .NET Framework web projects don't support automatic binding redirects, you have to manually add them to your `web.config`, but usually you'll get warnings you can double click and the will add the correct binding entries in your `web.config` file.

I have been looking for all other examples and this one is the only that fixed. Thank you
