### ISSUE TITLE
System.Drawing.Rectangle.Contains returns 'true' due overflow

### ISSUE THREAD

**Issue by patricksadowski** [microsoft/dotnet#589]
I've tried to file this issue with my LiveID at https://connect.microsoft.com/VisualStudio/Feedback but I get an error "You are not authorized to submit the feedback for this connection."

__Sample__
```csharp
var rectangle1 = new Rectangle(0, 0, 10, 10);
var rectangle2 = new Rectangle(int.MaxValue, 0, 10, 10);
Assert.False(rectangle.Contains(rectangle2));
```
`rectangle2` is logically not contained inside `rectangle1` but the method returns `true`. The addition of `rectangle2.X` and `rectangle2.Width` leads to an overflow. The sum is then used for a comparison which evaluates to `true`.

I'm using .NET 4.6.1

**Comment by jnm2** [comment]
The same thing afflicts [`Rectangle.Contains(Point)`](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Rectangle.cs,c1fa24ddf29349d8) via [`Rectangle.Contains(int, int).`](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Rectangle.cs,dac9c1f7c01c7b62).

**Comment by Tanya-Solyanik** [comment]
Please use floating point versions of the `Contains` APIs. https://msdn.microsoft.com/en-us/library/system.drawing.rectanglef(v=vs.110).aspx

**Comment by jnm2** [comment]
@Tanya-Solyanik What if the domain is integers? Floats are lossy. `(float)int.MaxValue == (float)(int.MaxValue - 1)`
Even if floats could be used instead of ints, why should `Rectangle.Contains` remain buggy?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
