### ISSUE TITLE
Calling UWP from .NET Core 2.0

### ISSUE THREAD

**Issue by nesherhh** [microsoft/dotnet#590]
Is it possible to call Windows 10 APIs (UWP) from a .NET Core 2.0 App?
It does work from .NET Framework 4.7, but not from .NET Core 2.0.
I'm getting this exception at runtime:
```
System.TypeLoadException: Could not load type 'System.Threading.Tasks.AsyncCausalityTracer' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.Threading.Tasks.AsyncInfoToTaskBridge`2..ctor(CancellationToken cancellationToken)
   at System.WindowsRuntimeSystemExtensions.AsTask[TResult](IAsyncOperation`1 source, CancellationToken cancellationToken)
   at System.WindowsRuntimeSystemExtensions.AsTask[TResult](IAsyncOperation`1 source)
   at System.WindowsRuntimeSystemExtensions.GetAwaiter[TResult](IAsyncOperation`1 source)
   at ClassLibrary1.Class1.<Abc>d__0.MoveNext() in c:\tmp\ConsoleApp1\ClassLibrary1\Class1.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ConsoleApp1.Program.<Main>d__0.MoveNext() in c:\tmp\ConsoleApp1\ConsoleApp1\Program.cs:line 16
```

**Comment by richlander** [comment]
PTAL @weshaggard @terrajobst @Petermarcu

**Comment by iamcarbon** [comment]
Do we know if a fix is landing in .NETCORE 2.1?

**Comment by cfeilen** [comment]
Also hitting this.

**Comment by iamcarbon** [comment]
Any update from the team?

**Comment by matt1va** [comment]
This also repro'd for me when building the .NET Core app targeting 2.1

**Comment by MaxxDelusional** [comment]
I can confirm. This is not working in 2.1.

I only received this error after adding the `System.Runtime.WindowsRuntime` nuget package. I can't seem to find a version of this assembly that will allow me use UWP APIs in my dotnetcore console app.

**Comment by andriysavin** [comment]
Looks like an artificial limitation. Since UWP apis can be called from .net core if not using async/await infrastructure, it's only a matter of porting System.Runtime.WindowsRuntime to this runtime. I hate sticking to full framework just because of this library. Any hope on this?

**Comment by andriysavin** [comment]
https://github.com/dotnet/corefx/issues/22789

**Comment by luqunl** [comment]
@jeffschwMSFT , @richlander

**Comment by dlech** [comment]
FWIW, I had success calling UWP Bluetooth LE APIs from a netcoreapp3.0 using .NET Core 3.0 preview 1.

**Comment by GiancarloLelli** [comment]
Hello @dlech - any chance you could share how you did that?

**Comment by jeffschwMSFT** [comment]
@GiancarloLelli around Preview 2 we plan on having a sample that demonstrates how to build such an app.  There are a few things you need to add to your project file (manually right now) and it should work.
From an existing netcoreapp3.0 you can add the following to your project file:
  <ItemGroup>
    <Reference Include="Windows">
      <HintPath><insert full path>\Windows.winmd</HintPath>
    </Reference>
  </ItemGroup>
Add the necessary nuget packages:
dotnet add package System.Runtime.WindowsRuntime --version 4.6.0-preview.18571.3 
And possibly:
dotnet add package System.Runtime.WindowsRuntime.UI.Xaml --version 4.6.0-preview.18571.3

**Comment by GiancarloLelli** [comment]
Hi @jeffschwMSFT  - apparently after digging a little on GitHub and the web I came up with the same solution you mentioned. I've successfully started a BLE Advertisement from a .NET Core 3.0 console app.
Thanks for the feedback though :) I'm really looking forward an official guidance - in case you need any help writing it, I would be happy to help!

**Comment by dlech** [comment]
> Hello @dlech - any chance you could share how you did that?

It sounds like you found what you need, but FWIW, I am (perhaps foolishly :smile:) attempting to make a cross-platform .NET hardware library at <https://github.com/DandyCode/Dandy.Devices>. This is a netstandard2.0 library that can then be used from a netcoreapp3.0 console app, for example.

**Comment by mahdouch550** [comment]
Also hitting this.

using await BitmapDecoder.CreateAsync method in a  .NET Core Web Application.

getting this exception:
System.TypeLoadException: Could not load type System.Threading.Tasks.AsyncCausalityTracer from assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

The same method works in a simple console application and gives expected results:
var decoder = await BitmapDecoder.CreateAsync(randomAccessStream);

**Comment by jeffschwMSFT** [comment]
@mahdouch550 what version of .NET Core are you using?  Can you share a repro of the failure you are seeing?  Thanks

**Comment by mahdouch550** [comment]
I'm creating a BitmapDecoder using await BitmapDecoder.CreateAsync method in a  .NET Core Web Application Project but I'm getting this exception

System.TypeLoadException: Could not load type System.Threading.Tasks.AsyncCausalityTracer from assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

The same method works in a simple console application and gives expected results.

var decoder = await BitmapDecoder.CreateAsync(randomAccessStream);

<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
</PropertyGroup>

**Comment by jeffschwMSFT** [comment]
WinRT is not supported on netcoreapp2.1.  Are you able to try .NET Core 3.0 Preview 5?

**Comment by mahdouch550** [comment]
Not yet, I will try that right away. Thanks

**Comment by leecow** [comment]
Looks like this is possibly resolved. 

This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
