### ISSUE TITLE
Suggestion - Release Notes More Visible on dot.net 

### ISSUE THREAD

**Issue by scottsauber** [Microsoft/dotnet#598]
It'd be handy to have a link to the release notes on the dot.net website for the Current/LTS versions, somewhere close to the Download button here - https://www.microsoft.com/net/download/windows

Right now you can get there by going to "download archive" but that's not super discoverable that's where the Release Notes live.

For instance - if you look at Node - https://nodejs.org/en/ - they have the "changelog" right next to the download button.

**Comment by shanselman** [comment]
@rowanmiller

**Comment by rowanmiller** [comment]
Would the post-download splash page work? Or is it important to be able to get these before downloading?

**Comment by scottsauber** [comment]
I think before downloading would be ideal, so I know if it’s worth downloading or not.

**Comment by scottsauber** [comment]
I also like the way Node does it in the link above where you can see multiple versions all at once. So if I missed an update in between my version and the latest, I can quickly see what I missed and read that previous version back’s release notes alongside the current version’s.

**Comment by rowanmiller** [comment]
Agreed that the Node page is nice, but our download story just isn't that simple for .NET. We made some changes to make the page simpler, but it's evident we went to far with it as too much stuff is hidden away.

I think we should surface release notes and LTS/Current tags on the [All Downloads page](https://www.microsoft.com/net/download/all), but I'm assuming you would want an easier way to get to these things (a.k.a having something directly on the Downloads page itself).

**Comment by scottsauber** [comment]
I think having it on the All Downloads page makes a lot of sense so you could see them side-by-side with the versions.  :thumbsup:

This is probably a really ignorant question, but what is the complication with the download story for .NET Core?  From my POV, it seems like there's just .NET Core and the .NET Framework?  

Today the Release notes just live here for .NET core: https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.5.md and here for .NET Framework: https://github.com/Microsoft/dotnet/blob/master/releases/net471/dotnet471-changes.md

So I would imagine it would look something like this...?
![image](https://user-images.githubusercontent.com/10823939/37859120-39db2eb2-2edd-11e8-8c4f-b9c1dede96ad.png)

**Comment by rowanmiller** [comment]
Agreed the release notes part is easy. For the "not as simple as Node", I just meant that we can't have a single Current and LTS button - we have a few more options than that. We need to do some work on the download page, so I will handle adding release notes as part of that.

**Comment by scottsauber** [comment]
Closing this since it looks like this has landed.  Thanks @rowanmiller!
