### ISSUE TITLE
In .net framework 4.7 / 4.7.1 rowdefinitions with asterisk in grid get out of bounds if content rows is collapsed.

### ISSUE THREAD

**Issue by EynsherKiel** [microsoft/dotnet#605]
This bugs appeared if set several controls with grids in stackpanel or same control.

Sample repo - 
https://github.com/EynsherKiel/GridDotNetBugs

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
