### ISSUE TITLE
Update README with where to officially file Suggestions/Updates/Feature Requests if not here

### ISSUE THREAD

**Issue by ericnewton76** [microsoft/dotnet#608]
Hey.  Thanks for creating this repo.

I'm looking for the official place to file Feedback/Suggestions/etc for the BCL framework.  The BCL blog hasnt been used since 2012, unfortunately (was cool to see the guys talking about upcoming stuff)

Specifically I wanna create a new suggestion:
In relation to the new Span<T>, Memory<T> array slice helpers, another possible benefit would be an additional StringBuilder type Append method overload for StringBuilder... ie, `StringBuilder.Append(StringBuilder value)` to eliminate requiring `StringBuilder value` to be `ToString()` and minimizing string allocations, and instead, internally the StringBuilder could either do an array copy from the internal buffer from value instance via Span<T>/Memory<T> or something like that.  

I'm throwing this in because a lot of the framework types' methods will get new overloads for the Span<T> support.  So while you're in StringBuilder and adding Span<T> overloads, add another overload to Append for StringBuilder argument too...   ;)

**Comment by kalaskarsanket** [comment]
@ericnewton76 You can reach out to us on [Dev Community](https://developercommunity.visualstudio.com/spaces/61/index.html). For all other issues reach out to us on appropriate repo as mentioned here [Microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
