### ISSUE TITLE
Suggestion: Add overload for StringBuilder.Append that takes StringBuilder argument

### ISSUE THREAD

**Issue by ericnewton76** [Microsoft/dotnet#609]
In relation to the new Span, Memory array slice helpers, another possible benefit would be an additional StringBuilder type Append method overload for StringBuilder... ie, StringBuilder.Append(StringBuilder value) to eliminate requiring StringBuilder value to be ToString() and minimizing string allocations, and instead, internally the StringBuilder could either do an array copy from the internal buffer from value instance via Span/Memory or something like that.

I'm throwing this in because a lot of the framework types' methods will get new overloads for the Span support. So while you're in StringBuilder and adding Span overloads, add another overload to Append for StringBuilder argument too... ;)

**Comment by jnm2** [comment]
Already done in https://github.com/dotnet/corefx/issues/4928, so this would be a request for a port to .NET Framework.

**Comment by AlexGhiondea** [comment]
Resolving as this is addressed in .NET Core.
