### ISSUE TITLE
Suggestion: Add StringBuilder.IndexOf

### ISSUE THREAD

**Issue by ericnewton76** [Microsoft/dotnet#610]
Stringbuilder desperately needs an `IndexOf` and `LastIndexOf` method with same overloads as `System.String.IndexOf` and `System.String.LastIndexOf` that works on the internal buffer for a call to `public System.Text.StringBuilder Replace (char oldChar, char newChar, int startIndex, int count)`

Sometimes you only need to Find-and-Replace a single instance of a substring within the StringBuilder.  However, there's not a good way to the index of that one substring... you have to call StringBuilder.ToString() which is a new string alloc (+1 string alloc), and call indexof on the string, and either use that index on the StringBuilder.Replace and then ultimately still ToString() after the Replace (+1 string alloc)

This could be ignored in lieu of #611 since you could iterate a returned Span<T> yourself, however _it would be great to get added for completeness of the StringBuilder type_

**Comment by jnm2** [comment]
Related: https://github.com/dotnet/corefx/issues/11390

**Comment by AlexGhiondea** [comment]
Thanks for the suggestions @ericnewton76! You can follow the discussion around these types in the CoreFx repo.
