### ISSUE TITLE
Suggestion: Span<T> StringBuilder.GetSpan() method + few overloads

### ISSUE THREAD

**Issue by ericnewton76** [Microsoft/dotnet#611]
This is in relation to the IndexOf/LastIndexOf suggestion #610 to expose the internal buffer as a Span<T> which hopefully could be iterated to find characters within the StringBuilder without first having to call ToString() which could potentially be a waste of string alloc.

```
public Span<T> GetSpan(); //returns whole buffer up to Length
public Span<T> GetSpan(int index, int count) //returns specific area of buffer
```

TBH, I bet the StringBuilder is getting this treatment, but also really hoping for #610 IndexOf/LastIndexOf to get added as well.

**Comment by sidristij** [comment]
StringBuilder is a chain and cannot be represented as one buffer

**Comment by jnm2** [comment]
See the proposal at https://github.com/dotnet/corefx/issues/21248.

**Comment by AlexGhiondea** [comment]
I am going to close this issue as there is a better one opened in the CoreFx repo.
