### ISSUE TITLE
Detect the build trigger/type in .csproj

### ISSUE THREAD

**Issue by TheYorkshireDev** [microsoft/dotnet#612]
I am wondering if there is any way to distinguish the trigger behind a build within the `.csproj`?

I ask in particular to dotnet core 2.0. I know that a few of the dotnet commands (`dotnet <cmd>`) actually trigger builds such as `dotnet build` and `dotnet publish`. I feel it would be useful to know what command triggered the build (build/publish) and use that information in a condition for a target.

```xml
<Target Name="DebugRunWebpack" BeforeTargets="Build" Condition="'$(BuildTrigger)' != 'publish'">
...
</Target>
```

* If this is not available at the moment is there any workarounds?
* Is there any appetite for it to be added in the future?

**Comment by jnm2** [comment]
`'$(MSBuildRuntimeType)' == 'Core'"` is one thing I an aware of.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
