### ISSUE TITLE
Error on compiling empty UWP project

### ISSUE THREAD

**Issue by mogikanin** [microsoft/dotnet#617]
Hi, I'm not sure is this a correct repo to post this bug, but I'm encountered a weird error on compiling empty UWP project.

Environment:
VS2017 (15.5.5)
Windows 10.0.16299 Build 16299

Steps:
1. Create empty UWP project (blank app)
2. Try to compile
```Severity	Code	Description	Project	File	Line	Suppression State
Error		Type universe cannot resolve assembly: System.ServiceModel.Primitives, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	App1			
Error		Cannot resolve Assembly or Windows Metadata file 'System.ServiceModel.Primitives.dll'	App1	D:\Projects\App1\App1\App1.csproj
```

Also, the bug is NOT reproduced if I downgrade Microsoft.NETCore.UniversalWindowsPlatform in used nuget packages from 6.0.6 to 6.0.5

**Comment by mogikanin** [comment]
[Sample project](https://github.com/Microsoft/dotnet/files/1706436/App1.zip)

**Comment by mogikanin** [comment]
the same error with VS 15.5.5 and 6.0.7 Also I remember that some time ago (probably several months) 6.0.6 worked well on my machine. Maybe the cause of issue is one of updates for .net? Will try VS preview and let you know too.

**Comment by mogikanin** [comment]
the same error on VS 15.6.0 preview 4. Works only 6.0.5.

**Comment by kalaskarsanket** [comment]
This issue has not got any input for long time and we have changed were issues are tracked. If this is still an issue kindly send the new issue to dotnetnative@microsoft.com..
