### ISSUE TITLE
Having issue in .net core 1.1 Antiforgery token

### ISSUE THREAD

**Issue by basavarajaC** [microsoft/dotnet#620]
I have an application .net core 1.1 mvc6 application,  where i am not able to to set the Anti forgery secure flag and session cookie Secure Flag. Please help.

**Comment by jnm2** [comment]
You might be looking for https://github.com/aspnet/Mvc/issues.

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
