### ISSUE TITLE
ConcurrentDictionary deserialization issue

### ISSUE THREAD

**Issue by magneto-81** [microsoft/dotnet#621]
ConcurrentDictionary with case insensitive string key, serialized with previous versions, does not correctly deserialize on .NET Framework 4.7.1
The issue is related with known issue [521954](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/521954%20-%20BCL%20CultureAwareComparer%20with%20ignore%20casing%20on%20serialized%20on%20previous%20versions%20of%20.NET%20do%20not%20correctly%20deserialize%20on%20.NET%204.7.1.md).
However the fixes for this issue doesn’t resolve the ConcurrentDictionary bug.

### How to reproduce
Create a ConcurrentDictionary put some data on it and serialize to file with the following code:
``` csharp
private void SaveDictionary(string filename) {
    var dictionary = new ConcurrentDictionary<string, string>(StringComparer.InvariantCultureIgnoreCase);
    dictionary.GetOrAdd("Test1", delegate { return "Test1"; });
    dictionary.GetOrAdd("Test2", delegate { return "Test2"; });
    dictionary.GetOrAdd("test3", delegate { return "test3"; });

    using (var stream = new MemoryStream()) {
        new BinaryFormatter().Serialize(stream, dictionary);
        byte[] bytes = stream.ToArray();

        File.WriteAllBytes(filename, bytes);
   }
} 
```
Load the dictionary and test it with the following code:
``` csharp
 private ConcurrentDictionary<string, string> LoadDictionary(string filename) {
    byte[] bytes = File.ReadAllBytes(filename);

    ConcurrentDictionary<string, string> dictionary;
    using (var stream = new MemoryStream(bytes)) {
        dictionary = (ConcurrentDictionary<string, string>)new BinaryFormatter().Deserialize(stream);
    }

    // Test the content of the Dictionary
    var entrys = dictionary.ToArray();
    foreach (var entry in entrys) {
        if (!dictionary.ContainsKey(entry.Key)) {
            throw new Exception("Corrupted Dictionary");
        }
    }
    return dictionary;
}
```
If the SaveDictionary is executed on framework 4.7 and the LoadDictionary on Framework 4.7.1 the test fail.

### Deep analysis
We have verified that the OnDeserialized method of ConcurrentDictionary is invoked before the OnDeserializedMethod of the Comparer. So the Dictionary initialize his internal structure using an incomplete class (this generate the HashCodes for the keys as a CaseSensitive Comparer) then the Comparer complete the deserialization changing itself in a CaseInsensitive comparer.

**Comment by AlexGhiondea** [comment]
@gargiulofrancesco thank you for reporting this!

We are able to reproduce this and we are looking for ways we can address this. The issue seems to be (as you identified) that the serialized comparer the document uses hasn't fully de-serialized itself.

I'll update this issue once we know more.

**Comment by gargiulofrancesco** [comment]
Are there any news?

**Comment by AlexGhiondea** [comment]
@gargiulofrancesco I tried contacting you over email to gather some more information about your issue.

Right now we understand the issue and we are going to address it in a future .NET Framework release.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275).
