### ISSUE TITLE
[4.7.1] [WinForms] High DPI PerMonitorV2 does not work if started on a different monitor

### ISSUE THREAD

**Issue by wizzard0** [microsoft/dotnet#626]
Repro: 
0. Win10 1709, VS2017, .NET 4.7.1
1. Have 2 monitors, with DPI 96 and 192 (for example). I use Surface Book + regular monitor
2. Set "Second screen only", logoff, login again, have system DPI at 96
3. Switch to "PC Screen only"
4. Open `PerMonitorDemo.sln` from `dotnet-samples`, confirm that Visual Studio uses raster scaling at this point.
5. Start app, Observe controls messed up.
5.1. If you switch monitors to "Extend", the DPIChanged message arrives, and the app rescales properly.
5.2. except for ToolStrip control which does not scale properly under all circumstances.

![image](https://user-images.githubusercontent.com/424619/36351747-1140aa6c-14b7-11e8-92eb-9ff5b83be509.png)

note: also submitted the issue to https://github.com/Microsoft/dotnet-samples/issues/40 , feel free to close either one.

**Comment by Tanya-Solyanik** [comment]
@wizzard0 we are working on the initial re-sizing and ToolStrip and other menu-like controls and plan to fix them for the next version of the .NET Framework.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
