### ISSUE TITLE
exe built on .net version 4.7 adds System.Windows.Forms.ApplicationConfigurationSection in app.confing on 4.6 version when i run .exe

### ISSUE THREAD

**Issue by amolbs222** [microsoft/dotnet#638]
Hello,

I have an application(.net) which is built on .net version 4.7.1 , when i run this application (.exe) on .net 4.6 version System.Windows.Forms.ApplicationConfigurationSection node automatically gets added to my configuration file. i gone through code there not any such code of adding System.Windows.Forms.ApplicationConfigurationSection to config file.

Does .net adds this automatically? 

can you please tell me how come out of this as i don't want to remove "System.Windows.Forms.ApplicationConfigurationSection" every time from config file manually. is there another way that can prevent "System.Windows.Forms.ApplicationConfigurationSection" getting added to app.config 

Note-when i remove "System.Windows.Forms.ApplicationConfigurationSection" it gets added automatically on 4.6 version of .net

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
