### ISSUE TITLE
Dotnet crashes

### ISSUE THREAD

**Issue by rvhelden** [Microsoft/dotnet#643]
While I was expirementing with opencl dotnet was crashing on me in an unusual way, When running the following code, dotnet crashes without any warnings.

    public class CLInvoke
    {
        [DllImport("OpenCL.dll", EntryPoint = "clGetPlatformIDs", SetLastError = true)]
        public static extern int GetPlatformIds2(int numEntries, out IntPtr[] platformIds, out int numberOfFoundPlatforms);
        [DllImport("OpenCL.dll", EntryPoint = "clGetPlatformIDs", SetLastError = true)]
        public static extern int GetPlatformIds3(int numEntries, [MarshalAs(UnmanagedType.LPArray)] ref IntPtr[] platformIds, out int numberOfFoundPlatforms);
    }

    class Program
    {
        static void Main(string[] args)
        {
            IntPtr[] platformIds4 = new IntPtr[1];
            CLInvoke.GetPlatformIds2(1, out var platformIds2, out var numberOfFoundPlatforms1);
            CLInvoke.GetPlatformIds3(1, ref platformIds4, out var numberOfFoundPlatforms2);
        }
    }

I got this in the eventviewer

> Fault bucket 2280225067781916381, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

> Problem signature:
P1: dotnet.exe
P2: 2.0.26021.1
P3: 5a3b026e
P4: StackHash_159d
P5: 10.0.16299.248
P6: effc9126
P7: c0000374
P8: PCH_D7_FROM_ntdll+0x00000000000F87BB
P9: 
P10: 

> Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER89F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA75.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA99.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERAAA.tmp.txt

> These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_dotnet.exe_d42b49bb486e64cbbe6025a352eb73130bec95_4a6d869b_367e0dde

> Analysis symbol: 
Rechecking for solution: 0
Report Id: dc283bf8-8f94-4982-8d9a-11a289d761aa
Report Status: 268435456
Hashed bucket: d74ea37af007825bdfa4fc9e351506dd

I have attached all the files from the eventviewer entry
[CrashReport.zip](https://github.com/Microsoft/dotnet/files/1766259/CrashReport.zip)

**Comment by Petermarcu** [comment]
Moving to the dotnet/core-setup repo here: https://github.com/dotnet/core-setup/issues/3818
