### ISSUE TITLE
NullReference when Stylus Widget installed

### ISSUE THREAD

**Issue by gustavocalheiros** [microsoft/dotnet#663]
I've recently noticed a huge number of crashes in an application, reported by different users which have some kind of stylus or touch input, just after they installed the windows update KB4058258.

Reading the .NET 4.7.2 early access release notes, I noticed a lot of improvements on behavior of stylus and touch devices that would seem to solve the problem, but even after installing it, the problem remains.

bug seems related to:
https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/481090-WPF%20Touch%20generates%20NullReferenceException%20in%20ProcessInputReport.md

.NET 4.7.2 release notes:
https://github.com/Microsoft/dotnet-framework-early-access/blob/master/release-notes/build-3052/dotnet-build-3052-changes.md

more info:
https://developercommunity.visualstudio.com/content/problem/205823/exception-after-kb4058258-with-wacom-tablets-1.html

My question is if this bug will really be addressed in the final version of 4.7.2 or if there is any way of working it around.

Thanks in advance.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this still an issue, please reach out to us on [Dev Community](https://developercommunity.visualstudio.com/spaces/61/index.html). For all other issues, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
