### ISSUE TITLE
UWP - Couldn't register background task

### ISSUE THREAD

**Issue by mogikanin** [microsoft/dotnet#667]
Hi, can someone explain why this piece of code throws  `Class not registered (Excep_FromHResult 0x80040154)` exception? The issue is not reproduced on our development machines, but quite often reproduced on users environment. I can provide a list of DeviceFamilyVersions, if needed.

```
var builder = new BackgroundTaskBuilder { Name = BACKGROUND_WATCHER_TASK };
builder.AddCondition(new SystemCondition(SystemConditionType.InternetAvailable));
builder.SetTrigger(new SystemTrigger(SystemTriggerType.NetworkStateChange, false));

BackgroundExecutionManager.RemoveAccess();
var result = await BackgroundExecutionManager.RequestAccessAsync();

// Remove all previous tasks (if any)
var tasks = BackgroundTaskRegistration.AllTasks.Values.Where(_ => _.Name == BACKGROUND_WATCHER_TASK).ToList();
tasks.ForEach(_ => _.Unregister(false));

// and register...
builder.Register();
```

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. For all UWP issues reach out to us  on dotnetnative@microsoft.com. For all other issues, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
