### ISSUE TITLE
UWP DatagramSocket does not receive data until after data is sent on the socket.

### ISSUE THREAD

**Issue by jrimig** [microsoft/dotnet#669]
See: https://stackoverflow.com/a/39767527 and https://stackoverflow.com/a/39768462

You can also use https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DatagramSocket to demonstrate this issue. Use scenario 5 to listen for multicast traffic and observe nothing is received until after hitting the send button. 

Visual Studio 2017 15.6.2
.NET Framework 4.7.02558
Windows 10 Anniversary Edition (10.0: Build 14393)

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please reach out to us at dotnetnative@microsoft.com. For all other issues, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
