### ISSUE TITLE
Merge in the Awesome .NET List

### ISSUE THREAD

**Issue by richlander** [Microsoft/dotnet#68]
Merge in missing OSS projects from here: 

https://github.com/quozd/awesome-dotnet/blob/master/README.md

to here:
https://github.com/Microsoft/dotnet/blob/master/dotnet-projects.md

See approval from maintainer: 
https://twitter.com/vquozd/status/535338938744193026 

Thanks!!

**Comment by paladique** [comment]
Is this still an outstanding issue? I did some simple comparisons between the two and it looks like it's still not merged. If not I'd be interested in taking this on. :raising_hand:
