### ISSUE TITLE
.Net 4.7 Installing problem

### ISSUE THREAD

**Issue by bmbekir** [microsoft/dotnet#680]
I installed windows 10 now. Our project run with .Net framework 4.7.1. Visual studio Installer not install 4.7 and 4.7.1 I try to install "NDP471-DevPack" but it is not installed.
Error : [11D8:0A7C][2018-03-26T15:46:44]e000: Error 0x81f40001: Bundle condition evaluated to false: ((VersionNT = v6.1 AND ServicePackLevel >= 1) OR      (VersionNT = v6.2 AND NOT (OSInstallationType = "Client")) OR      (VersionNT = v6.3) OR      (VersionNT = v10.0 AND OSBuildNumber >= 14393) OR      (VersionNT > v10.0))
[11D8:0A7C][2018-03-26T15:46:44]i199: Detect complete, result: 0x0

![image](https://user-images.githubusercontent.com/6053311/37907579-35fee198-310e-11e8-808e-6b0b5ca6dca9.png)

**Comment by zdavatz** [comment]
What is your Output of:
`
Get-ChildItem "hklm:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" | Get-ItemPropertyValue -Name Release | % { $_ -ge 461308 }
`

**Comment by zdavatz** [comment]
I can not uinstall 4.7.1 because it is tied into the OS as it seems ;(.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
