### ISSUE TITLE
MSMQ support for .net core

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/dotnet#716]
It looks like there are no libraries provided in .net standard / .net core to support MSMQ. In that case, how can we use MSMQ while working with asp.net core 2.0 and above web application?

**Comment by jnm2** [comment]
This is tracked at https://github.com/dotnet/corefx/issues/6204.

**Comment by kalaskarsanket** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
