### ISSUE TITLE
Microsoft.NETCore.UniversalWindowsPlatform Version 6.1.2 gives upload error

### ISSUE THREAD

**Issue by hwjSoftware** [Microsoft/dotnet#721]
A simple test app could be uploaded to the store without error.
Changing Microsoft.NETCore.UniversalWindowsPlatform Version 6.0.8 to 6.1.2 gives the upload error: 
The declared package dependency does not exist. Dependency: Microsoft.NET.Native.Framework.2.1. Minimum version: 2.1.26417.0.
I use VS 15.7.0 Preview 5.0 with .NET Framework Version 4.7.02556 and build 16299. 
What can I change to use version 6.1.2 in store submissions?

**Comment by ratishphilip** [comment]
You need to downgrade to v6.0.8 and then it will upload successfully.
It is the same issue as #728 

I had the same issue. Got fixed by downgrading to v6.0.8.

**Comment by hwjSoftware** [comment]
Did you mean that v6.1.2 can't be used at all?

**Comment by ratishphilip** [comment]
I'm not sure about that. Maybe some kind of update is required at the app certification side.

I spent an hour trying to figure out why my app submission is giving this error before I noticed #728.

When I shifted back to v6.0.8. the submission went through.

Maybe Microsoft will update it after Build 2018 event.

**Comment by zamont** [comment]
Hi @hwjSoftware . Thanks for reporting issue and adopting the latest UWP tools! I've just responded to #728 and we've since updated the Microsoft.NET.Core.UniversalWindowsPlatform package on NuGet to 6.1.4 and the Windows Store is setup to accept these app submissions. Can you please upgrade and give this a try?

**Comment by hwjSoftware** [comment]
A test app using v6.1.4 could be uploaded to the Store without error.
