### ISSUE TITLE
TypeDescriptor gives all threads the same non-thread-safe ReflectPropertyDescriptor 

### ISSUE THREAD

**Issue by jnm2** [Microsoft/dotnet#732]
### Defect

The TypeDescriptor API causes race conditions by handing out the same instance of ReflectPropertyDescriptor to all threads, even though instances of ReflectPropertyDescriptor are not thread-safe:

[`ReflectPropertyDescriptor.AmbientValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,414990b682eca44e)
[`ReflectPropertyDescriptor.ChangedEventValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,1c05b2eeda4fb8fd)
[`ReflectPropertyDescriptor.IPropChangedEventValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,2e9295611c83788d)
[`ReflectPropertyDescriptor.DefaultValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,c583e4f4ea20817a)
[`ReflectPropertyDescriptor.GetMethodValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,3b48df1474c54332)
[`ReflectPropertyDescriptor.ResetMethodValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,8ccc601e1d4e0e2a)
[`ReflectPropertyDescriptor.SetMethodValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,08db7c642e76ecb4)
[`ReflectPropertyDescriptor.ShouldSerializeMethodValue`](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/ReflectPropertyDescriptor.cs,5680e7ef6dbf6069)

Since other threads receive the same instance from `TypeDescriptor.GetProperties`, they execute these methods concurrently. Often, after the `state` bit is set but before the corresponding field is initialized. **This causes the PropertyDescriptor to transiently act as though the underlying member in question is missing.**

### Practical effect

This is causing our tests to fail. Even though it hasn't been seen in production yet, TypeDescriptor is used frequently on background threads. As far as I can tell, there's nothing to prevent this from happening at random in production.

I don't see any mitigation for this bug other than to use a shared lock before accessing any method of  any PropertyDescriptor in case it is a ReflectPropertyDescriptor, though a mitigation would be appreciated.

Needed while targeting .NET Framework 4.6.2. Repros against net45 and net471 as well.

### Repro

Here is a repro I put together that fails 9 out of 10 runs. It doesn't test SetValue and GetValue, which are the other interesting methods for us; they fail too, but less often than ResetValue and ShouldSerializeValue.

##### ReflectPropertyDescriptor repro.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
```

##### Program.cs

```cs
using System;
using System.ComponentModel;
using System.Threading;

namespace ReflectPropertyDescriptor_repro
{
    public sealed class SomeType
    {
        public int SomeProperty { get; set; }

        private void ResetSomeProperty() => SomeProperty = 42;

        private bool ShouldSerializeSomeProperty() => false;
    }

    public static class Program
    {
        public static void ConcurrentTest()
        {
            var propertyDescriptor = TypeDescriptor.GetProperties(typeof(SomeType))[nameof(SomeType.SomeProperty)];
            var instance = new SomeType();

            propertyDescriptor.ResetValue(instance);
            if (instance.SomeProperty != 42)
            {
                throw new Exception("Race condition inside ReflectPropertyDescriptor: ResetSomeProperty cannot have been actually invoked.");
            }

            if (propertyDescriptor.ShouldSerializeValue(instance))
            {
                throw new Exception("Race condition inside ReflectPropertyDescriptor: ShouldSerializeSomeProperty cannot have been actually invoked.");
            }
        }

        public static void Main()
        {
            const int threadCount = 10;

            using (var finished = new CountdownEvent(threadCount))
            {
                for (var i = 0; i < threadCount; i++)
                {
                    new Thread(() =>
                    {
                        ConcurrentTest();
                        finished.Signal();
                    }).Start();
                }

                finished.Wait();
            }
        }
    }
}
```

**Comment by jnm2** [comment]
Just tried this on .NET Core and discovered that it has been fixed.
Located the PR: [Fix some race conditions in TypeConverter lib](https://github.com/dotnet/corefx/pull/13224)
Issue: [TypeDescriptor.GetProperties full of race conditions](https://github.com/dotnet/corefx/issues/13215)

Please port these fixes to .NET Framework.

**Comment by AlexGhiondea** [comment]
@jnm2 thanks for reporting this. I am glad to hear that this is addressed in .NET Core! 

I have marked that PR as something we should consider porting back to .NET Framework.

**Comment by jnm2** [comment]
@AlexGhiondea Thanks for marking that! Is there any chance this will be fixed over Windows Update for 4.6.2, or will we be forced to target 4.7.2?

We've been avoiding 4.7 and 4.7.1, and due to the ValueTuple issues each has had, this turned out to be a very good thing for us.

**Comment by AlexGhiondea** [comment]
@jnm2 .NET Framework 4.7.2 has just released and it does not contain the fix you have mentioned. We are going to consider it for a future version of .NET Framework!

To consider this for servicing we would need to understand the business impact of the bug and balance it with the compatibility risk of the change.

**Comment by jnm2** [comment]
Thanks for the info. Is there for a way for us to be updated when you know whether or not it will make it into the fall release?

**Comment by AlexGhiondea** [comment]
@jnm2 we don't have that mechanism unfortunately. You can reach out to me offline and we can discuss this further if you want.

**Comment by jnm2** [comment]
I appreciate it. What's a good way to contact you?

**Comment by AlexGhiondea** [comment]
@jnm2 you can reach me at # ghiondea [_d_o_t_] alexandru [_`_a_t_`_] microsoft.com #

**Comment by jnm2** [comment]
That's very gracious of you. Thanks!
