### ISSUE TITLE
System.IO.Compression.ZipArchive missing in 4.7.2

### ISSUE THREAD

**Issue by mariocatch** [microsoft/dotnet#751]
In an ASP Core project, targeting 4.7.2, System.IO.Compression.ZipArchive is missing. Downgrading to 4.7.1 brings it back, but going back up to 4.7.2 breaks it again.

**Comment by joperezr** [comment]
can you please share a binlog with the error so that we can diagnose what is happening here? In order to produce a binlog, simply build your project from the command prompt like: `msbuild yourProject.csproj /t:rebuild /bl` which will drop a msbuild.binlog file on your current directory.

**Comment by AlexGhiondea** [comment]
@mariocatch can you also clarify what you mean by it 'missing'?

**Comment by ChrisJBeacon** [comment]
I can confirm the issue reported as well.  We were using System.IO.Compression.ZipArchive but it is no longer accessible in 4.7.2.  We were forced to down grade to 4.7.1 where it is accessible.

**Comment by AlexGhiondea** [comment]
Can you share a repro with us? Does it happen every time, during a specific type of project? Can you share more about the environment you are running in?

**Comment by AlexGhiondea** [comment]
We were able to repro this in house and we can confirm that this is the same issue as [this one](https://github.com/Microsoft/dotnet/blob/master/releases/net472/KnownIssues/613745%20-%20Single-name%20references%20are%20removed%20by%20the%20SDK%20when%20targeting%204.7.2.md).

@joperezr is going to update the known issue with a workaround for when you are using packages.config as well.

@dsplaisted is working on a fix that will address this class of issues.

**Comment by joperezr** [comment]
Sharing the workaround through here while I write the PR to update that issue:

Add this to your .csproj
```xml
<ItemGroup>
  <Reference Include="System.IO.Compression" />
</ItemGroup>
```

That should fix the issue.

**Comment by dsplaisted** [comment]
The fix for this just went in here: https://github.com/dotnet/sdk/pull/2250

**Comment by Paul2701** [comment]
To use the ZipFile class, you must reference the System.IO.Compression.FileSystem assembly in your project.
https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=netframework-4.8
