### ISSUE TITLE
Typo in https://www.microsoft.com/net/download/all

### ISSUE THREAD

**Issue by jnm2** [Microsoft/dotnet#763]
I'm not sure of a good place to report this [typo](https://www.microsoft.com/net/download/all) (this repo was suggested):

![image](https://user-images.githubusercontent.com/8040367/40519455-9da3485e-5f8d-11e8-8c94-f11f9ef0a2b1.png)

**Comment by mairaw** [comment]
@rowanmiller can you take a look?

**Comment by rowanmiller** [comment]
Fixed. @jnm2 many thanks for reporting!
