### ISSUE TITLE
PackageReference can't Exclude it's reference

### ISSUE THREAD

**Issue by chrishaly** [Microsoft/dotnet#764]
There are 3 packages: LibA1, LibA2, LibB.
Contents of LibA1 and LibA2 are the same, LibA1 and LibA2 both have only one assembly LibA.dll. they both also have only a class A.
LibB reference LibA1. LibB has a class B.

In project LibC, referenced LibB and LibA2. the purpose is use LibA2 instead LibA2 in runtime.

csporj of LibC is:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibA2" Version="1.0.0" />
        <PackageReference Include="LibB" Version="1.0.1" />
    </ItemGroup>

</Project>
```
when compile errors is:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'A' exists in both 'LibA1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'LibA2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	LibC	x:\...\LibC\C.cs	7	Active
```
it's expect.

then I try to exclude LibA1 from LibB, so I changed csproj as:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibA2" Version="1.0.0" />
        <PackageReference Include="LibB" Version="1.0.1" Exclude="All" />
    </ItemGroup>

</Project>
```
the error remains.

I found some article said, use ExcludeAssets instead of Exclude, so I change csporj to:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LibA2" Version="1.0.0" />
        <PackageReference Include="LibB" Version="1.0.1">
            <ExcludeAssets>All</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
```

above error disappeared, but B.dll also be excluded, new error occured as:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'LibB' could not be found (are you missing a using directive or an assembly reference?)	LibC	x:\...\LibC\C.cs	8	Active
```

so how can I exclude LibA1 from LibB in csporj of LibC?

**Comment by danmosemsft** [comment]
@chrishaly is this running on .NET Core?

**Comment by joperezr** [comment]
Hi @chrishaly, I see what is going on. You can't really exclude the assets from the LibB reference, because as you've now seen this will also remove the libB.dll as you have seen already. In order to get this to work, you need to manually reference LibA1 package as well and exclude the assets of that package. If you don't do this, what is happening behind the scenes is that LibB is automatically adding a reference to LibA1, and since you are not excluding assets that is why you end up with both references and get a conflict. So basically, you want your .csproj to look something like:
```xml
    <ItemGroup>
        <PackageReference Include="LibA2" Version="1.0.0" />
        <PackageReference Include="LibB" Version="1.0.1" />
        <PackageReference Include="LibA1" Version="1.0.0">   <!-- I'm not sure what the version of this package is, so I just assumed 1.0.0. The real version is whichever version LibB package depends on. -->
            <ExcludeAssets>All</ExcludeAssets>
        </PackageReference>
    </ItemGroup>
```

**Comment by chrishaly** [comment]
@danmosemsft yes .NET Core
@joperezr you are right, it's solved my issue.

I made a little change, LibA1 with asssembly name LibA1.dll, and LibA2 has assembly name LibA2.dll

After publish LibC has file list as:

```
LibA2.dll
LibB.dll
LibC.deps.json
LibC.dll
LibC.pdb
```
It's all right.

But there are another issue about this.
A new .NET Core Console App project LibTest.ConsoleApp1 created with .csproj

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LibC\LibC.csproj" />
    </ItemGroup>

</Project>

```

After publish LibTest.ConsoleApp1, LibA1.dll, and LibA2.dll both in publish output directory.

Then I change LibTest.ConsoleApp1.csproj to 
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LibC\LibC.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LibA1" Version="1.0.3">
            <ExcludeAssets>All</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
```

After publish LibTest.ConsoleApp1 only LibA2.dll in the publish output directory, that's expected.

This is not a big problem, but wheather LibA1.dll is needed or not by default is a question.
Since LibA1 was excluded in LibC it's also should be excluded by default in project which directly or indirectly referenced LibC what do you think?

**Comment by joperezr** [comment]
This is by design. It would be bad for the new project to assume that you don't need to bring in all of the dependencies that LibC depends on. Depending on which target platform your new project runs on, it might cause issues at runtime. If you believe that this is not the right behavior I would suggest you opening an issue on the http://github.com/dotnet/sdk repo as I believe that would be a good place for it.

**Comment by chrishaly** [comment]
ok thanks
