### ISSUE TITLE
Docs : gpg: no valid OpenPGP data found - Ubuntu 18.04

### ISSUE THREAD

**Issue by TheBeachMaster** [Microsoft/dotnet#769]
From the given steps in [this link](https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-current), the command 
`wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg`  fails with `gpg: no valid OpenPGP data found.` on a fresh Ubuntu 18.04.

But running `wget -qO- https://packages.microsoft.com/keys/microsoft.asc --no-check-certificate | gpg --dearmor > microsoft.asc.gpg` works.

**Comment by SusLes** [comment]
This issue has been moved to [https://github.com/dotnet/core/issues/1621](https://github.com/dotnet/core/issues/1621)
