### ISSUE TITLE
Will .NET Core 2.1's Span-based APIs be made available on the .NET Framework? If so, when?

### ISSUE THREAD

**Issue by stakx** [Microsoft/dotnet#770]
There's a long discussion over at https://github.com/dotnet/standard/issues/682. Originally the OP wanted to know whether the new `Span`-based APIs in the .NET Core 2.1 class library would be made available via a new version of .NET Standard. The discussion has shifted more towards what .NET Standard is, or should be, and one important question hasn't been answered yet so I'd like to ask it here:

Will .NET Core 2.1's new `Span`-based APIs <sup>(*)</sup> be brought to the .NET Framework? If so, what's an approximate version / timeframe for this to happen?

<sup>(*)</sup> By "`Span`-based APIs", I do not mean what's in the `System.Memory` package on NuGet, but also all the additional methods in the FCL using `Span` et al., such as those on `Stream`. I also implicitly assume that introducing these APIs on NETFX would include support for `Span` in the JIT.

**Comment by terrajobst** [comment]
We haven't finalized our plans for the upcoming release of .NET Framework in terms of feature set and timeline. I expect we'll include that information as part of the .NET Standard vNext plan and which framework versions will implement it and when.

**Comment by stakx** [comment]
Thanks for replying, @terrajobst. Sorry to keep bothering you, but in this case, can you by chance already give a rough ETA for when the .NET Standard vNext plan will be announced publicly?

**Comment by stakx** [comment]
Just stumbled over this statement in https://github.com/dotnet/coreclr/issues/18280#issuecomment-394404682:

> The proper runtime support by byref-like types and features that depend on it (e.g. fast span) won't ever show up in .NET Framework update [...].

(If that is true, then it might actually be misleading and a disservice to developers to add `Span` APIs to the FCL.)

**Comment by jnm2** [comment]
@stakx I certainly hope that's not what @jkotas was saying. I think his point was that you'd have to opt in by targeting a newer version versus getting upgraded by Windows Update.

**Comment by stakx** [comment]
@jnm2 - Ah... I see. Yes, let's hope he indeed meant it in the way you just explained it. Thanks for clarifying!

**Comment by jnm2** [comment]
@stakx If it's quirkable, it could be done in 4.8. I am very curious to hear what the team's actual plans are.
I'd leave .NET Framework for .NET Core the minute the whole Windows Forms and WPF stack can be developed and run on .NET Core 3. In the meantime, .NET Framework is still important.

**Comment by stakx** [comment]
No idea what quirkable means, but I trust that you folks know what you're up to there. 😆

**Comment by Alois-xx** [comment]
@jkotas: Since .NET 4.8 is expected 2019 it is pretty clear that Span<T> won´t show up before 2020 if at all. So the long term plan is that .NET 4.8 is the last major release while you are working on making .NET Core 3.0 to work with WPF WF?, WinForms, ... to give us a migration path off from Desktop .NET Framework to .NET Core.

**Comment by stakx** [comment]
Another quote from Rich Lander confirming that (fast?) span won't be in .NET 4.8: https://blogs.msdn.microsoft.com/dotnet/2018/06/06/announcing-net-framework-4-8-early-access-build-3621/#comment-554635

**Comment by stakx** [comment]
Closing this, as I guess my question has been sufficiently answered: "Span APIs wont come to the .NET Framework because it'll soon be put to rest." If I have misunderstood, feel free to correct me.
