### ISSUE TITLE
Can these Reflection / Reflection.Emit bugfixes be backported from .NET Core to .NET Framework?

### ISSUE THREAD

**Issue by stakx** [Microsoft/dotnet#771]
I've recently submitted several bugfixes for Reflection and Reflection.Emit which I would love to see backported to the .NET Framework. The goal is to increase the accuracy of dynamic proxying of types (with e.g. DynamicProxy) which would directly benefit mocking libraries (e.g. Moq, NSubstitute, FakeItEasy) and DI containers (e.g. Castle Windsor, Autofac).

I suspect that there is significant code share between the CLR and the CoreCLR in the Reflection facilities, since both runtimes had the same bugs, so backporting would seem generally feasible.

Could the following changes from CoreCLR please be backported to the .NET Framework?:

#### Reflection: Fix `FormatException` when querying `ParameterInfo.DefaultValue` of optional `DateTime` parameter
* bug report: https://github.com/dotnet/corefx/issues/26164
* implementation: https://github.com/dotnet/coreclr/pull/17877
* tests: https://github.com/dotnet/corefx/pull/29533

#### Reflection.Emit: Allow `ParameterBuilder.SetConstant(null)` for value-typed parameters

* bug report: https://github.com/dotnet/corefx/issues/26184
* implementation: https://github.com/dotnet/coreclr/pull/17887 + https://github.com/dotnet/coreclr/pull/17915 (amendment)
* tests: https://github.com/dotnet/corefx/pull/29532

#### Reflection: Fix `FormatException` when querying `ParameterInfo.DefaultValue` of optional (closed generic) enum parameter
* bug report: https://github.com/dotnet/corefx/issues/29570
* implementation: https://github.com/dotnet/coreclr/pull/17917

#### Reflection: Allow `ParameterBuilder.SetConstant(nonNullValue)` for nullable enum parameters
* bug report: https://github.com/dotnet/coreclr/issues/17893
* implementation: https://github.com/dotnet/coreclr/pull/17977
* tests: https://github.com/dotnet/corefx/pull/29676

If I am asking in the wrong place, please let me know how to proceed in order to advance this request.

**Comment by AlexGhiondea** [comment]
@stakx thanks for your help fixing those issues!

I am going to mark the issues so that we consider them for the next version of .NET Framework.

**Comment by stakx** [comment]
@AlexGhiondea: Thank you, that is great to hear and much appreciated! :+1:

I assume that the labels you've added will suffice for further tracking, so I am closing this issue.

Thank you!
