### ISSUE TITLE
Hope ThreadPoolTimer.CreatePeriodicTimer can start a job immediately

### ISSUE THREAD

**Issue by kevin-jing** [Microsoft/dotnet#773]
Now it works like wait > work > wait ... 
How to work like work > wait > work …? 
https://docs.microsoft.com/en-us/windows/uwp/threading-async/create-a-periodic-work-item
I'm actually using a workaround: 
ThreadPoolTimer.CreateTimer(MonitorAsync, TimeSpan.FromSeconds(0)); 
PeriodicTimer = ThreadPoolTimer.CreatePeriodicTimer(MonitorAsync, TimeSpan.FromSeconds(10)); 
It's not beautiful. 
I hope MS can add another overload like: 
CreatePeriodicTimer(TimerElapsedHandler handler, TimeSpan period, TimeSpan delay);

**Comment by SusLes** [comment]
@kevin-jing
Moved to [https://github.com/dotnet/coreclr/issues/18331](https://github.com/dotnet/coreclr/issues/18331).
