### ISSUE TITLE
WPF data binding on DataView relation fails

### ISSUE THREAD

**Issue by maelstraggiotti** [microsoft/dotnet#780]
We have noticed a behavior change on .Net Framework 4.7.2 when a WPF data binding points through a ADO DataSet relation using an indexer property.

For a DataSet with two tables in a parent/child relation, when DataContext is set to the parent row's DataRowView and the control is bound using an expression like ```{Binding Children[0].ChildName}```, the data source is read but never updated. It was not the case prior updating to 4.7.2 (with 4.7.1 and older).

I can't identify any binding properties altering this behavior. This is kind of a major regression for us, as we strongly relies on these bindings.

The attached project allow reproducing the issue with a minimal setup.

[BindingIssue.zip](https://github.com/Microsoft/dotnet/files/2112042/BindingIssue.zip)

edit : it seems related to changes into ```MS.Internal.Data.ValueTable```, which returns a weak reference pointing to the child DataView. The reference is alive on target update but goes out of scope after that. If we forcefully keep a reference to the child DataRowView (using ugly reflective hack), the source is correctly updated as the reference is kept alive.

Thanks for your help.

**Comment by vivmishra** [comment]
@SamBent

**Comment by maelstraggiotti** [comment]
We are worried that the impact might be bigger. 

It seems KB4338419/KB4338420 (Update for Microsoft .NET Framework 4.6.2 ) installed the 4.7.3130.0 assemblies which contains this bug.

Thanks

**Comment by SamBent** [comment]
I've finally figured out the problem.  ADO returns a newly-created object (of type DataView or RelatedView) for each call to the getter of a "DataSet collection property".  These objects are not referenced by any other ADO objects, so it is up to the caller to keep them alive.  But WPF tries hard not to add strong references to these objects.  There are only three ways:

1. Creating a collection view over the object 
2. Adding a ValueChanged listener for one of the object's properties 
3. Caching the object in the ValueTable

Actually (3) no longer happens at all - it was causing a memory leak of the entire DataSet (DDVSO 297912).  If the app never uses (1) or (2), there's nothing to keep the object alive.  After a while, the object is GC'd, and the app silently stops working.

I'm fixing this for .Net 4.8.   In the meantime, the "ugly reflective hack" can be replaced by a non-reflective (but still somewhat ugly) hack that simply uses (1) or (2):

1. Add `<ListBox ItemsSource="{Binding Children}"/>`   (ask for a collection view) 
2. Add `<TextBlock Text="{Binding Children.Count}"/>`  (ask for a ValueChanged listener)

The added element can be made small or placed off-screen.

**Comment by maelstraggiotti** [comment]
I'm glad you figured it out. Thanks.
