### ISSUE TITLE
Assembly.GetCallingAssembly() hase bug

### ISSUE THREAD

**Issue by agebullhu** [Microsoft/dotnet#793]
when i call "Assembly.GetCallingAssembly()" by release model and select  optimized code , the result Assembly is center method Assembly,no calling method Assembly!

**Comment by jnm2** [comment]
`GetCallingAssembly` and `GetExecutingAssembly` are known to be fragile by definition.

See https://docs.microsoft.com/dotnet/api/system.reflection.assembly.getcallingassembly?view=netframework-4.7.2#remarks. Specifically:

> This effect also occurs when `M1` executes as a tail call from `M2`, or when `M2` executes as a tail call from `M3`. You can prevent the JIT compiler from inlining the method that calls GetCallingAssembly, by applying the MethodImplAttribute attribute with the MethodImplOptions.NoInlining flag, but there is no similar mechanism for preventing tail calls.

**Comment by jnm2** [comment]
See also:

`https://github.com/dotnet/corefx/issues/1784#issuecomment-115805990`
`https://github.com/dotnet/corefx/issues/2221#issuecomment-147288985`
`https://github.com/dotnet/corefx/issues/11212#issuecomment-248383696`

**Comment by agebullhu** [comment]
thank, my code is changed,using type of Assembly argument bypass this bug.

**Comment by jnm2** [comment]
@agebullhu Good, that's the best technical solution that I know of.
