### ISSUE TITLE
dotnet publish fail on warnings

### ISSUE THREAD

**Issue by ChaosCA** [Microsoft/dotnet#799]
Hey there,

I apologies if this is the wrong place. This is more of a feature suggestion to have a flag on the `dotnet publish` command that causes it to exit with a non-zero status code when it encounters a warning.

This is useful for CI/CD applications that are unmanaged, failing on warnings can prevent potentially buggy code from reaching production when it otherwise may have not be caught. Sort of like a `strict` mode.

**Comment by SusLes** [comment]
This issue has been moved to the CLI Repo:  https://github.com/dotnet/cli/issues/9640.
