### ISSUE TITLE
6.0.1 NETCore.UniversalWindowsPlatform version doesn't work with 17134 (1803) SDK version

### ISSUE THREAD

**Issue by Kath118** [Microsoft/dotnet#800]
The version 6.0.1 of NetCore doesn't work with 17134 target and min version on UWP project.

Visual Studio: 2017
Target and Min version: 17134 (1803)
NETCore.UniversalWindowsPlatform: 6.0.1

![image](https://user-images.githubusercontent.com/39101155/42461792-99e4568c-835e-11e8-836d-174d32c140fa.png)

**Comment by MagicAndre1981** [comment]
update to [6.1.5](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.1.5) and try again.
