### ISSUE TITLE
Is there have a mascot for dotnet?

### ISSUE THREAD

**Issue by shenglingshi** [microsoft/dotnet#808]
Can we choose a animal as a mascot for dotnet?

**Comment by svick** [comment]
.Net already has a mascot, the .Net Bot:

[![](https://raw.githubusercontent.com/dotnet/swag/71f7cbc4b74444d9022638f60ff03ca30e2a1ea6/dotnet-bot/dotnet-bot_branded.png)](https://github.com/dotnet/swag/blob/71f7cbc/dotnet-bot/dotnet-bot_branded.png)

**Comment by shenglingshi** [comment]
Thanks!

**Comment by alur2020** [comment]
can someone close this issue?
