### ISSUE TITLE
Upgrade from .NET 4.6.2 to 4.7.2 causes ID6041: The provided RSA key is invalid

### ISSUE THREAD

**Issue by thuannguy** [Microsoft/dotnet#812]
I upgraded a solution from .NET 4.6.2 to 4.7.2 and got a problem with RSA and CNG certificates.

Related code:
```csharp
private void FederatedAuthentication_FederationConfigurationCreated(object sender, System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs es)
{
    System.Security.Cryptography.X509Certificates.X509Certificate2 serviceCertificate = es.FederationConfiguration.ServiceCertificate;
			es.FederationConfiguration.IdentityConfiguration.SecurityTokenHandlers.AddOrReplace(
				new SessionSecurityTokenHandler(new System.Collections.ObjectModel.ReadOnlyCollection<CookieTransform>(
					 new List<System.IdentityModel.CookieTransform> 
					{ 
						new DeflateCookieTransform(), 
						new RsaEncryptionCookieTransform(serviceCertificate), 
						new RsaSignatureCookieTransform(serviceCertificate) 
					})
				 ));
}
```

Stack trace:

> [InvalidOperationException: ID6041: The provided RSA key is invalid.]
   System.IdentityModel.RsaEncryptionCookieTransform.Encode(Byte[] value) +360
   System.IdentityModel.Tokens.SessionSecurityTokenHandler.ApplyTransforms(Byte[] cookie, Boolean outbound) +74
   System.IdentityModel.Tokens.SessionSecurityTokenHandler.WriteToken(XmlWriter writer, SecurityToken token) +893
   System.IdentityModel.Tokens.SessionSecurityTokenHandler.WriteToken(SessionSecurityToken sessionToken) +136
   System.IdentityModel.Services.SessionAuthenticationModule.WriteSessionTokenToCookie(SessionSecurityToken sessionToken) +203
   System.IdentityModel.Services.SessionAuthenticationModule.AuthenticateSessionSecurityToken(SessionSecurityToken sessionToken, Boolean writeCookie) +129
   System.IdentityModel.Services.WSFederationAuthenticationModule.SignInWithResponseMessage(HttpRequestBase request) +1224
   System.IdentityModel.Services.WSFederationAuthenticationModule.OnAuthenticateRequest(Object sender, EventArgs args) +545
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91

The line that causes the exception is: https://github.com/Microsoft/referencesource/blob/7f0c570e24e6f0084b3c5794e1a50de9fbe00ca4/System.IdentityModel/System/IdentityModel/RsaEncryptionCookieTransform.cs#L299

```csharp
    RSACryptoServiceProvider provider = encryptionKey as RSACryptoServiceProvider;
    if ( provider == null )
    {
        throw DiagnosticUtility.ThrowHelperInvalidOperation( SR.GetString( SR.ID6041 ) );
    }
```
Track back to the constructor showed me:

```csharp
    public RsaEncryptionCookieTransform(X509Certificate2 certificate)
    {
        if (null == certificate)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("certificate");
        }
        _encryptionKey = X509Util.EnsureAndGetPrivateRSAKey(certificate);
        decryptionKeys.Add(_encryptionKey);
    }
```

Running debug showed me that the _encryptionKey is of type CNG.
Is there any documented guideline for this breaking change? What is the correct way to keep the current behavior? My application is huge so there might be a lot more breaks.

P/S: I found some links that mentioned something similar, but not quite the same:
https://github.com/Microsoft/dotnet/issues/341
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.6.2-4.7.2

**Comment by brentschmaltz** [comment]
@thuannguy can you try using a 'quirk' that will instruct the runtime to return a RSACryptoServiceProvider.
There is an example here: https://github.com/brentschmaltz/WCF/blob/master/RSACastingWithX509AsymmetricKey/App.config

**Comment by thuannguy** [comment]
@brentschmaltz thank you :) I tried that switch by looking at the source code, but it doesn't quite work for me: https://github.com/Microsoft/dotnet/issues/816

**Comment by thuannguy** [comment]
Any news on this? Any other things that I should check out?

**Comment by brentschmaltz** [comment]
@thuannguy I just reviewed the code. Other than overriding I am not seeing a fix. The bug is in System.IdentityModel that ships with .Net Framework. We would have to get a fix into 4.8 and push to get it backported.

**Comment by thuannguy** [comment]
@brentschmaltz thank you for the info. Given that .Net 4.8 is far from ready (I once read that it will take 12 months since the day 4.7.2 was shipped), I won't be able to upgrade my solution any time soon 😞 I hope it will be approved to fix and merge back as you mentioned 😃

**Comment by thuannguy** [comment]
@brentschmaltz I need to try https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sqlallproducts-allversions out for my product, which means I need to update to .NET 4.7.2. In reality, I can wait until SQL 2019 and .NET 4.8 are released and upgrade to it. However, my worry is that after this issue is fixed for 4.8, some other hidden issues will reveal themselves😢

**Comment by stroborobo** [comment]
FYI, worked for us, posted the other issue here: https://github.com/Microsoft/dotnet/issues/816#issuecomment-452323862

**Comment by thuannguy** [comment]
@stroborobo thank you one more time 😄
