### ISSUE TITLE
UWP 6.1.7 missing runtime dependencies

### ISSUE THREAD

**Issue by robv8r** [Microsoft/dotnet#825]
While attempting to upgrade the Microsoft.NETCore.UniversalWindowsPlatform NuGet package to version 6.1.7, I receive many errors including the following:

```
NU1103: Unable to find a stable package runtime.win10-arm.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ] 
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1103: Unable to find a stable package runtime.win10-arm-aot.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ] 
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1103: Unable to find a stable package runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ] 
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1103: Unable to find a stable package runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1103: Unable to find a stable package runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1103: Unable to find a stable package runtime.win10-x86-aot.Microsoft.NETCore.UniversalWindowsPlatform with version (>= 6.1.7)
  - Found 12 version(s) in nuget.org [ Nearest version: 6.2.0-preview1-26502-02 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

I have verified that these packages are not available in the NuGet Gallery:

https://www.nuget.org/packages/runtime.win10-arm.Microsoft.NETCore.UniversalWindowsPlatform

https://www.nuget.org/packages/runtime.win10-arm-aot.Microsoft.NETCore.UniversalWindowsPlatform

https://www.nuget.org/packages/runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform

https://www.nuget.org/packages/runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform

https://www.nuget.org/packages/runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform

https://www.nuget.org/packages/runtime.win10-x86-aot.Microsoft.NETCore.UniversalWindowsPlatform

**Comment by martinsuchan** [comment]
I have no such issues, maybe Microsoft replaced the wrong 6.1.7 package already?  
https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/6.1.7  

By the way, isn't is strange that the Dependencies for target UAP 10.0.15138 are identical both in NuGet 6.1.5 and 6.1.7? Shouldn't there be updated NuGet dependency with the fix for CVE mentioned in the [changelog](https://github.com/Microsoft/dotnet/blob/master/releases/UWP/net-native2.1/README.md)?
```
UAP 10.0.15138
Microsoft.Net.Native.Compiler (>= 2.1.8)
Microsoft.Net.UWPCoreRuntimeSdk (>= 2.1.2)
Microsoft.NETCore.Platforms (>= 2.0.0)
NETStandard.Library (>= 2.0.3)
```

**Comment by robv8r** [comment]
You are correct.  This no longer appears to be an issue.  My best guess is that MS was in the process of uploading the packages or NuGet was busy processing and distributing them when I filed this bug.

Since this is no longer a problem, I'll close the issue.
