### ISSUE TITLE
JIT creates wrong result when optimized on x86

### ISSUE THREAD

**Issue by lukas-ais** [Microsoft/dotnet#835]
We found a bug in the JIT optimizer. It seems there are several preconditions needed to hit the bug:

- The bug occurs only on x86. (Same c# code on x64 is running fine.)
- The bug is caused by optimizer. (When optimization is disabled - in Debug build or with MethodImpl attribute -, the code is running fine.)
- The bug occurs only when a generic type is used.

Environment:

- Runtime is .NET 4.7.2
- Compiler: VS2018 (15.8.0)
- Target Platform: We verified the problem with 4.6.1 and 4.7.2

Here is the sample code to reproduce the problem.

```c#
namespace OptimizedPropertyException
{
    internal static class Program
    {
        static void Main(string[] args)
        {
            var sut = new NodeReference<BaseNode>();
            var x = new BaseNode();
            sut.Node = x;

            Console.WriteLine($"Disposed = {sut.IsChildDisposed}");
            x.IsDisposed = true;
            Console.WriteLine($"Disposed = {sut.IsChildDisposed}"); // EXCEPTION
        }
    }

    public class NodeReference<T>
        where T : BaseNode
    {
        private T node;

        public bool? IsChildDisposed
        {
            get
            {
                bool? result = null;
                if (this.Node != null)
                {
                    result = this.Node.IsDisposed;
                }

                return result;
            }
        }

        public T Node
        {
            //[MethodImpl(MethodImplOptions.NoOptimization)]
            get
            {
                if (this.node != null && this.node.IsDisposed)
                {
                    this.node = null;
                }
                return this.node;
            }
            set => this.node = value;
        }
    }

    public class BaseNode
    {
        public bool IsDisposed { get; internal set; }
    }
}
```

When running with optimization, the Main method will fail on the second access to the property `IsChildDisposed`.
According to our analysis the problem is caused by the optimization of the method `get_Node`.

The code may be somehow special. But I think the generalized use case is: The method (getter) sets a member conditionally to `null` before returning the updated member.

We analyzed the IL code. But we did not find any relevant differences.

So, lets have a look on the optimized assembler code of the getter:

```asm
02610583  add         byte ptr [eax],al  
02610585  add         byte ptr [eax],al  
02610587  add         byte ptr [ecx+ebx-24h],dl  
0261058B  add         byte ptr [eax],al  
0261058D  add         byte ptr [eax],al  
0261058F  add         byte ptr [eax+19h],cl  
02610592  fadd        qword ptr [eax]  
02610594  ror         byte ptr [esi-24h],0  
--- ...\NodeReference.cs 
                if (this.node != null && this.node.IsDisposed)
02610598  push        ebp  
02610599  mov         ebp,esp  
0261059B  mov         eax,dword ptr [ecx+4]  
0261059E  test        eax,eax  
026105A0  je          026105AD  
026105A2  cmp         byte ptr [eax+4],0  
026105A6  je          026105AD  
                {
                    this.node = null;
026105A8  xor         edx,edx  
026105AA  mov         dword ptr [ecx+4],edx  
026105AD  pop         ebp  
026105AE  ret  
```

The member `node` will be loaded into the register EAX on 0261059B.
In case it is already `null`, we jump to 026105AD, this means `return`.
The method calling convention seems to say "The method return value can be found on EAX".

In case the member will be set to `null` (026105AA), the member will be updated, but EAX still contains the original member value/pointer.
I think something is missing here: setting EAX to zero. Why is EDX used to set member value? If EAX would be used in 026105A8 and 026105AA, the behavior should be as expected.

I hope my analysis is correct. At least it is an explanation for the high level behavior: The getter of `IsChildDisposed` will access the property `Node` two times sub-sequentially, for checking `null` and then to use it. According to the optimizer bug the first access does not return `null` but the second one does, which is causing the `NullReferenceException`.

**Comment by benaadams** [comment]
Might want to also file at https://github.com/dotnet/coreclr

**Comment by karelz** [comment]
This issue was moved to dotnet/coreclr#19547
