### ISSUE TITLE
What are the tools to inspect easily memory layouts of struct/classes and jitted code with C#

### ISSUE THREAD

**Issue by fredpointzero** [Microsoft/dotnet#841]
Hi,

I am trying to optimize C# code in terms of memory layouts and jit'ed code but I have hard times to find whether I am optimizing or not.

Concerning memory I use the Memory view of Visual Studio to analyze the data in memory and SharpLab's Head/Stack inspection to get the memory layout of struct/classes (which is great).
- It would be nice to get this information from an actual project (and not a small sandbox like SharpLab's editor) so we can get actual information on the project we are working on.
(So, you don't have to copy paste each time in SharpLab, and don't loose your project build configuration, which can impact the way code is compiled)
- Also, I don't know if there is any way to get this information for a .Net Native (coreRT) compiled code?

Concerning assembly and jit'ed code, I often try to cache values with generic struct so the cache is directly inserted in jit'ed code. But validating that it is optimized properly is not straightforward.

Currently, I use Visual Studio's assembly view (debugging with JIT optimizations) so I can check this, but:
 - I find it hard to know if the code was properly jit'ed for each generic instantiation and that the jit'ed code is actually different with different cached values
- I often tend to have misconfigured debugging settings, so I am never sure I am actually debugging the jit'ed optimized code
- SharpLab is great to test patterns and quickly know if a pattern is optimized during jit, but SharpLab does not support static constructors with the JIT asm output.

It seems that the only reliable way to do this is to [view the jit dumps](https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md) but this requires a custom coreCLR build and a setup for dogfooding it, which is not straightforward as well.
Maybe there are other tools that can check the jit'ed code quicker than a custom coreCLR?

Also, I plan to use coreRT to have more optimization during IL to assembly compilation phase, but I will have the same question: How can I validate that my code is actually optimized as planned with coreRT?

**Comment by briansull** [comment]
I recommned that you  view the jit dumps by building and using a checked version of coreCLR.
It may be a bit complex to setup but it is the proper  way to understand what the JIT is dong.

https://github.com/dotnet/coreclr/blob/master/Documentation/building/viewing-jit-dumps.md
