### ISSUE TITLE
Consolidate and cleanup temporary artifacts on Linux

### ISSUE THREAD

**Issue by chrisd8088** [microsoft/dotnet#880]
Hi!  I'm getting started with .NET Core and ASP.NET on Linux, and as a Linux user, I noticed with a minor degree of dismay how many temporary artifacts are created and left behind when compiling and running even a small demo .NET application.

Including the locations documented in [Managing the global packages, cache, and temp folders](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders), here are the ones I noticed after a simple demo build and run:

```
~/.dotnet/
~/.nuget/
~/.local/share/NuGet/
~/.templateengine/
/tmp/.NETCoreApp,Version=v?.?.AssesmblyAttributes.cs
/tmp/.dotnet/shm/
/tmp/CoreFxPipe_*
/tmp/NuGetScratch/lock/
/tmp/clr-debug-pipe-*-*-{in,out}
/tmp/tmp*.tmp
```

Some of these seem to accumulate many small leftover files over time, like all the zero-bytes files under `/tmp/NuGetScratch/lock/`.  The `/tmp/tmp*.tmp` files appear to have artifacts related to the "dotnet restore" command.

It would be truly fantastic if these could (a) be automatically cleaned up whenever possible, so as to minimize cruft leftover from builds and runs, and (b) be consolidated into just a few locations, e.g., `/tmp/dotnet/` for *all* global temporary things, and a couple of home directory locations following the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) like `~/.cache/dotnet/` for user-specific cached stuff and `~/.local/share/dotnet/` for user-specific data.

I should also add that I really appreciate all the documentation on getting started on Linux, and the relative ease of installation of the packages.  Thank you; it's clear a huge amount of effort has gone into making these packages cross-platform.

**Comment by nicolasr75** [comment]
This seems to be related:
I have two applications that communicate via a named pipe. When one of the apps was accidentally started with sudo, a CoreFxPipe_* file remains in /tmp that can then not be opened by the other side (not run as sudo!) because of "Permission denied". The only way to fix it, is to manually delete the file with sudo :-(

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
