### ISSUE TITLE
Compile error CS0139 has misleading grammar

### ISSUE THREAD

**Issue by equin0x80** [microsoft/dotnet#904]
The error states: "No enclosing loop out of which to break or continue."
This suggests that we are either "breaking out of a loop" or "continuing out of a loop". However, the "continue" keyword proceeds *through* the loop (next iteration), not *out of* it.
A simple alternative might be "No enclosing loop for 'break' or 'continue'."

**Comment by jnm2** [comment]
Sounds like a request for https://github.com/dotnet/roslyn/?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
