### ISSUE TITLE
Crash in Microsoft.NETCore.UniversalWindowsPlatform 6.1.X when deserializing Nullable<int>

### ISSUE THREAD

**Issue by lukasvolf** [Microsoft/dotnet#905]
UWP app that references Microsoft.NETCore.UniversalWindowsPlatform 6.1.X (I've tried 6.1.5, 6.1.7 and 6.1.9) crashes in Release (after being compiled with NET Native) when I attempt to de-serialize an object from XML using DataContractSerializer when the object has a property of type Nullable<int>. It works fine without crashes in 6.0.12. 
`[DataContract]
public class Test
{
    public Nullable<int> Value { get; set; }
}`

When you change the nuget to 6.0.12, it works and the app runs fine. With 6.1.9 the app is immediately reported by Malwarebytes as malware and quarantined, after adding an exception to Malwarebytes, the app crashes with a Win32 exception.

[DeserializationCrash.zip](https://github.com/Microsoft/dotnet/files/2514830/DeserializationCrash.zip)
![malwarebytes](https://user-images.githubusercontent.com/29753601/47500519-4f623c00-d863-11e8-8aab-0104d478057d.png)

**Comment by lukasvolf** [comment]
Any progress on this? Do you need anything else to get it fixed?

**Comment by MichalStrehovsky** [comment]
Do you have a stack trace of the crash? I'm not able to reproduce it.

**Comment by lukasvolf** [comment]
It's no longer reproducible here either using VS 2017 15.9.2. I guess it must have been fixed in some update since then.
