### ISSUE TITLE
XMLReaderSettings EnableLegacyXmlSettings always true for asp.net applications

### ISSUE THREAD

**Issue by PaulVrugt** [microsoft/dotnet#910]
We've been trying to avoid XXE attacks in our application, and found out that starting .net framework 4.5.2 xmldocument should be safe by default, because the XMLResolver is set to null by default starting this framework version. This is also stated in the owasp documentation (https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#XmlDocument) This is (after some digging in the reference source) done by setting the xmlResolver property of the XmlTextReaderImpl class to null. However, this is only done when EnableLegacyXmlSettings is not set to true. This method returns true, when the framework version used is not 4.5.2 or higher. However, in asp.net, the framework check for TargetAtLeast_Desktop_V4_5_2 in BinaryCompatibility always returns false.

After some more digging, this check is done via the system.runtime.versioning.binarycompatibility.TargetsAtLeast_Desktop_V4_5_2, which in turn gets the data from the AppWasBuiltForFramework property, which uses the method ReadTargetFrameworkId.

Now we are getting to the core of the issue. The ReadTargetFrameworkId uses the AppDomain.CurrentDomain.GetTargetFrameworkName method, which returns null in asp.net. The problem here seems to be that the target frameworkname is only initialized when the appdomain is the defaultappdomain (see appdomain.cs:625). Seeing as an asp.net application never runs on the default appdomain, the targetframework will never be filled, and the targetframework is not determined. This causes the TargetAtLeast_Desktop_V4_5_2 method to return false, and the Legacy xml settings to always be enabled, leaving us vulnerable to XXE attacks.

Even when the check on appdomain.cs:625 would be changed so it also fills the targetframework property when the appdomain is not the default domain, the check would still fail, because filling the targetframework uses "Assembly.GetEntryAssembly()" (line 629), which returns null in asp.net applications.

This seems like a bug to me. Do you agree, and what can we do avoid it and resolve our XXE vulnerability?

Edit:
As a workaround, i now added the following in the application_start:
var type = typeof(System.Xml.XmlReaderSettings;
var field = (from f in (TypeInfo)type where f.Name == "s_enableLegacyXmlSettings" select f).First();
field.SetValue(null, new Nullable<bool>(false));

Is this viable in production code as a workaround, or is legacy xml settings enabled in asp.net for a reason?

**Comment by yodasad** [comment]
I also think it is a serious bug, it would be great to get some comments from MS.

**Comment by yodasad** [comment]
It is written [here](https://docs.microsoft.com/ru-ru/dotnet/api/system.xml.xmlreadersettings.xmlresolver?view=netframework-4.8):

> An XmlResolver used to access external documents. If set to null, an XmlException is thrown when the XmlReader tries to access an external resource. The default is a new XmlUrlResolver with no credentials. Starting with the .NET Framework 4.5.2, this setting has a default value of null.

So these docs are not valid for ASP.NET application.

**Comment by StephenMolloy** [comment]
The concept of "target framework" is handled differently in ASP.NET from other applications because 1) ASP.Net is a multi-tenant application host and must consider that different tenants may target different frameworks, and 2) the mechanism by which "target framework" works in other apps is to decorate the executing assembly with an assembly attribute designating the target - but ASP.NET does not really have an executing assembly to speak of.

The correct way to "target" 4.5.2 or higher is to set the target in configuration. Visual Studio does this for you automatically when selecting a target framework for web applications.
"<system.web><httpRuntime targetFramework="4.5.2" /></system.web>"

**Comment by riverar** [comment]
I just stumbled on this myself in the middle of an enterprise-level _scramble_ and I don't think @StephenMolloy's suggestion is relevant here. Bringing in others to put eyes on this, I suspect this is a security issue. @richlander @shanselman @blowdart

Repro:
1. Spin up trusty netcat (`nc -L -vvv -p 12345`)
2. Call this in an ASP.NET app somewhere, e.g. Application_Start:
```
var xml =
@"<?xml version=""1.0"" encoding=""ISO-8859-1""?>
<!DOCTYPE foo [ <!ENTITY xxe SYSTEM ""http://127.0.0.1:12345/test.txt"">] >
<foo>&xxe;</foo>
";
var xmldoc = new XmlDocument();
xmldoc.LoadXml(xml);
```
3. Observe netcat noise.
4. Repeat steps in a .NET Console app and observe no netcat noise.

As @PaulVrugt pointed out, during XmlReader initialization, XmlReaderSettings fails `BinaryCompatibility.TargetsAtLeast_Desktop_V4_5_2` checks when run in an ASP.NET context. This results in a fallback to an unsafe configuration that's vulnerable to XXE attacks. This occurs regardless of target framework specified in web.config.

**Comment by GrabYourPitchforks** [comment]
@riverar I cannot repro the behavior you observe. The `BinaryCompatibility` settings are being properly initialized in the ASP.NET projects I'm testing. If you have a minimal self-contained repro app which exhibits this behavior, would you mind zipping it and posting it somewhere so that we can access it? Thanks!

**Comment by riverar** [comment]
@GrabYourPitchforks A colleague discovered we're missing `<httpRuntime targetFramework="4.6" />` in our `web.config` (as your edit suggests), so we were running in .NET Framework 4.0 mode. Apologies for the red alert.

**Comment by GrabYourPitchforks** [comment]
Great! Glad to hear you were able to root cause the issue. :)
