### ISSUE TITLE
Use commands to exclude files that need to be compiled in xxx.csproj.

### ISSUE THREAD

**Issue by inernoro** [microsoft/dotnet#926]
I don't find a way to exclude compiled files from [dotnet](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-remove-reference)

 For example, I want to exclude old.cs from my project, but I need to edit xxx.csproj. I think editing project files directly will slow down my development. In fact, many times I need to exclude the function of files. Like "dotnet remove [option xxx.csproj] file xxx.cs" ?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
