### ISSUE TITLE
GetWeekOfYear returns incorrect value for GregorianCalendar (.net framework 4.7.2)

### ISSUE THREAD

**Issue by MEmanuelsson** [Microsoft/dotnet#935]
Noticed a strange behavior using the GregorianCalendar and trying to fetch week number for the date 2018-12-31 (Swedish format) in our application.  The following code returns week number 53 when it should return 1:

`
var culture = new CultureInfo("sv-SE");
var calendar = culture.Calendar;
var weekNumber = calendar.GetWeekOfYear(new DateTime(2018, 12, 31), CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
`

Trying the same code for date 2019-01-01 returns week number 1.

To show you that this date should actually be connected to week number 1, here's how this exact same date is shown in my Outlook:
![calendarweek](https://user-images.githubusercontent.com/9945377/49997911-26247900-ff93-11e8-8dd9-2f03b3c25770.png)

Feels like a bug to me unless I've misunderstood this function completely?

**Comment by MEmanuelsson** [comment]
Looks like I'm not the only one who've noticed this same issue: https://blogs.msdn.microsoft.com/shawnste/2006/01/24/iso-8601-week-of-year-format-in-microsoft-net/

**Comment by dasMulli** [comment]
That's why .NET Core 3.0 and .NET Standard 2.1 are introducing the `ISOWeek` type - https://apisof.net/catalog/System.Globalization.ISOWeek

**Comment by MEmanuelsson** [comment]
OK, makes sense that I'm not the first person noticing this behaviour. Take it that this will not be implemented in .NET Framework then so I'll live with our workaround for now.
