### ISSUE TITLE
Bad naming on Path.GetDirectoryName and Path.GetFileName

### ISSUE THREAD

**Issue by scegg** [microsoft/dotnet#937]
These are well known problems:
Path.GetDirectoryName is NOT returns the directory name but the parent path of the string provided.
Path.GetFileName is NOT returns the file name but the last path node of the string provided.

Problem is when dealing with a folder path, it is very easy to be confused to choose GetDirectoryName incorrectly over GetFileName.

Why not consider to change those name?

Thanks for hearing my murmur...

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
