### ISSUE TITLE
System.EngineExecutionException in Assembly.GetTypes()

### ISSUE THREAD

**Issue by knodel12** [microsoft/dotnet#942]
Hello, I'm trying to debug an EngineExecutionException being thrown in WebAPI during debugging sessions.  For some reason, after a fresh build, we get this exception on the first request to WebApi.  The subsequent requests function as expected, but this exception crashes the site and the debugger has to be reattached.

**Background**
We have a ASP.NET application running on .NET Framework 4.7.2.  The main dll is a webforms project and WebAPI is a secondary dll deployed with the main application.  We recently installed a package called "PupeeterSharp", and this began creating these EngineExecutionExceptions.  After investigating for a while, many sources say it's related to System.Net.Http package (as this package depends on the NuGet version, but we use the framework version).

We have tried assembly redirects, removing the System.Net.Http package directly, and other potential fixes but this still occurs ONLY if that PuppeeterSharp package is installed.  I believe this is related to a .NET issue, rather than PuppeeterSharp mainly due to the exception being an EngineExecutionException.

**Debugging Information**
I have a crash dump if necessary, however it's 1.3GB, so probably too large to put on this issue.  If anything is needed, just let me know and I'll put more information into this issue.

**Comment by knodel12** [comment]
Is there anyone that can assist?  This is causing a major inconvenience for developers.  I'd like to be able to diagnose it if anyone has ideas...

**Comment by knodel12** [comment]
Please.  Can we do anything about this issue?  Can I provide something to the community to provide context???  This is STILL an issue, in VS 2019 and .NET 4.8.

**Comment by sujayvsarma** [comment]
I'd love to help. Where can I get a workable repro project for this? Can you cook one up that shows the same setup, dependencies and throws the exception.. and host it in a git repo here?

**Comment by leecow** [comment]
This repo is no longer actively monitored. Closing up old issues that have not had activity in while. If this is still an issue, please open a new issue in an appropriate repo listed in [microsoft/dotnet#1275](https://github.com/microsoft/dotnet/issues/1275)
