### ISSUE TITLE
Value 'arm64' missing for Windows.System.ProcessorArchitecture

### ISSUE THREAD

**Issue by queequac** [microsoft/dotnet#943]
It's not possible to detect a package's processor architecture in case of ARM64 (which is available as compilation target with Microsoft.NETCore.UniversalWindowsPlatform 6.2 targeting Windows 10 build 16299 and above) through `Package.Current.Id.Architecture` (see https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageid.architecture), because the enum `Windows.System.ProcessorArchitecture` does only contain values _x86_, _arm_, _x64_, _neutral_ and _unknown_.

**Comment by MagicAndre1981** [comment]
you need to target your app for [Build 18362/Version 1903, here ARM64 and X86OnArm64 was added](https://docs.microsoft.com/en-us/uwp/api/windows.system.processorarchitecture#version-history)

**Comment by queequac** [comment]
Sorry, this issue was obviously never closed.

ARM64 support was available before the enum got introduced.
Please have a look at the issue's date, it was created in 2018, while the enum got added in 2019. ;)
