### ISSUE TITLE
HttpResponseMessage RetryAfter header is unable to parse decimal values.

### ISSUE THREAD

**Issue by daverant** [Microsoft/dotnet#955]
While working with MS Graph, I've found I'm being returned decimal retry-after header values. The [HTTP spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37) says that Retry-After values as seconds in decimals are valid, but parsing with HttpResponseMessage.Add throws a FormatException. For example `new System.Net.Http.HttpResponseMessage().Headers.Add("retry-after", "2.542");` but I think it's reasonable that this should be parsed correctly as per the HTTP spec? Obviously getting the ceiling of that decimal as an int is fine, but will cause unnecessary latency in a system.

**Comment by darrelmiller** [comment]
The HTTP spec does not allow fractional values.  

> The value of this field can be either an HTTP-date or a number of
>    seconds to delay after the response is received.
> 
>      Retry-After = HTTP-date / delay-seconds
> 
>    A delay-seconds value is a non-negative decimal integer, representing
>    time in seconds.
> 
>      delay-seconds  = 1*DIGIT
> 
https://tools.ietf.org/html/rfc7231#section-7.1.3

The ABNF is 1*DIGIT which only allows digits and not the decimal point.  The term "decimal integer" indicates it is a base 10 integer.

**Comment by daverant** [comment]
Thanks for clarifying @darrelmiller, not familiar with ABNF so that makes sense now. In that case I need to go raise a bug with the Graph/Teams team.

**Comment by darrelmiller** [comment]
@daverant This issue came to my attention via a thread involving Teams PMs.  So they are aware of the issue.
