### ISSUE TITLE
Microsoft.NETCore.UniversalWindowsPlatform 6.2.8 update error from 6.1.X

### ISSUE THREAD

**Issue by jp-weber** [Microsoft/dotnet#981]
I get the error message for some projects ```Unable to find metadata of runtime.win10-arm64.Microsoft.Net.Native.Compiler.2.2.3```

If I add```runtime.win10-arm64.Microsoft.Net.Native.Compiler``` manually to the project with version 2.2.4 (only 2.2.4 and 2.2.1 is visible), the update UniversalWindowsPlatform 6.2.8 works.

**Comment by IsmailHassani** [comment]
I have the same issue.

**Comment by DkmS1953** [comment]
I have the same bullshit.

**Comment by IsmailHassani** [comment]
As soon I try to build ARM64 target it gives me the following error.
```
C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): Error : ILT0005: 'C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\runtime.win10-arm64.microsoft.net.native.compiler\2.2.4\tools\ARM64\ilc\Tools64\nutc_driver.exe @"c:\VstsAgentISynergy1\_work\4\s\src\I-Synergy.Manager.Windows\obj\ARM64\debug\ilc\intermediate\MDIL\I-Synergy.Manager.rsp"' returned exit code 255

Process 'msbuild.exe' exited with code '1'.
```

I've added the runtime.win10-arm64.Microsoft.Net.Native.Compiler 2.2.4 package manually, but seems not to solve this issue.

**Comment by IsmailHassani** [comment]
They messed up big time. Even reverting back to 6.2.3 does not work anymore because of delisted dependencies. 😢

**Comment by emiliano84** [comment]
yesterday I had same issue, now works :/

**Comment by jp-weber** [comment]
Thank you for the info. I see that ```runtime.win10-arm64.Microsoft.Net.Native.Compiler``` have now the version 2.2.3. I can confirm, that the update will works now.

**Comment by MagicAndre1981** [comment]
does the app work for you? After updating to 6.2.8 I only get this exception at app startup:

```
Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
An unhandled exception of type 'System.Exception' occurred in Unknown Module.
```

**Comment by jp-weber** [comment]
Yes, I have no problems, everything works as it should (Debug & Release).

**Comment by MagicAndre1981** [comment]
@jp-weber no only the "PackageReference Include" entry for "Microsoft.NETCore.UniversalWindowsPlatform" was updated when I used NuGet UI to update the version to 6.2.8. Next I did a rebuild and trying to debug the app stops with this error message right at start.

**Comment by MagicAndre1981** [comment]
@jp-weber does your csproj (for the UWP app) include RuntimeIdentifiers entries? Mine is not having it. After adding the win10 entries to RuntimeIdentifiers the app works with 6.2.8

**Comment by jp-weber** [comment]
@MagicAndre1981 
No, my UWP project have no RuntimeIdentifiers.

**Comment by MagicAndre1981** [comment]
@jp-weber this is confusing. But I'm happy that I found a way to get it running.

**Comment by emiliano84** [comment]
> @jp-weber does your csproj (for the UWP app) include RuntimeIdentifiers entries? Mine is not having it. After adding the win10 entries to RuntimeIdentifiers the app works with 6.2.8

Interesting, I had the opposite problem, my project had RuntimeIdentifiers and didn't work, I removed them and it worked :)

**Comment by MagicAndre1981** [comment]
@emiliano84 

this makes the issue even more confusing 🤔❓❔🤷‍♂️

**Comment by MagicAndre1981** [comment]
One question. My UWP app is just a Xamarin.Forms wrapper app without any other code. @emiliano84 @jp-weber what are you doing? real UWP only app or also Xamarin?

**Comment by emiliano84** [comment]
> One question. My UWP app is just a Xamarin.Forms wrapper app without any other code. @emiliano84 @jp-weber what are you doing? real UWP only app or also Xamarin?

mine is UWP only

**Comment by MagicAndre1981** [comment]
@emiliano84 thanks for this helpful information, now if @jp-weber is also only using UWP we might have the difference between us.

**Comment by MagicAndre1981** [comment]
ok, this explains the difference. you both @emiliano84 @jp-weber use UWP only and I have a Xamarin.Forms project.
