### ISSUE TITLE
Assemblys loaded in memory FileNotFoundException

### ISSUE THREAD

**Issue by cschuchardt88** [microsoft/dotnet#982]
```
Assembly asm = AppDomain.CurrentDomain.Load(File.ReadAllBytes(@"C:\Temp\HelloWorld.exe")); // Load Raw COFF data of "Hello World" Application .NET version

AppDomain.CurrentDomain.ExecuteAssemblyByName(asm.FullName); // Now with the above line loaded in memory. I get "FileNotFoundException"
```

Can someone please tell me why this isn't a bug? In "ExecuteAssemblyByName" function. The function is doing a search for the assembly on the local disk; which wont exists because its loaded from memory.

**Comment by cschuchardt88** [comment]
Can you please fix this!

**Comment by cschuchardt88** [comment]
Been waiting more than a decade for the reason why this works the way it does.

**Comment by cschuchardt88** [comment]
Let just brush some of the core functionally under the rug here. And lets not forget the words of `Its by design`.... is what im going to hear. Just remember the file doesn't; does; or doesn't; or maybe it does....nah!! its doesn't Exist!!! So your checks are inferring that something is there... but wait it get better... it's not checking... Now that dotnet is open source i guess your just waiting for me to put the PR in.... 💯 ?!?!?!? 😵‍💫

**Comment by cschuchardt88** [comment]
Come on guys, seriously? It looks simple and doesn't look like anything is wrong. so i'll give you more details.

```
[Exception] System.Private.CoreLib.dll!System.Reflection.RuntimeAssembly.InternalLoad(System.Reflection.AssemblyName assemblyName, ref System.Threading.StackCrawlMark stackMark, System.Runtime.Loader.AssemblyLoadContext assemblyLoadContext, System.Reflection.RuntimeAssembly requestingAssembly, bool throwOnFileNotFound) Line 388
	at /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs(388)
[Exception] System.Private.CoreLib.dll!System.Reflection.Assembly.Load(string assemblyString) Line 21
	at /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/Assembly.CoreCLR.cs(21)
[Exception] System.Private.CoreLib.dll!System.AppDomain.ExecuteAssemblyByName(string assemblyName, string[] args) Line 145
	at /_/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs(145)
[Exception] ConsoleApp1.dll!Program.<Main>$(string[] args) Line 5
	at C:\Users\Chris\source\repos\ConsoleApp1\ConsoleApp1\Program.cs(5)
[Managed to Native Transition]
System.Private.CoreLib.dll!System.Reflection.RuntimeAssembly.InternalLoad(System.Reflection.AssemblyName assemblyName, ref System.Threading.StackCrawlMark stackMark, System.Runtime.Loader.AssemblyLoadContext assemblyLoadContext, System.Reflection.RuntimeAssembly requestingAssembly, bool throwOnFileNotFound) Line 396
	at /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs(396)
System.Private.CoreLib.dll!System.Reflection.Assembly.Load(string assemblyString) Line 21
	at /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/Assembly.CoreCLR.cs(21)
System.Private.CoreLib.dll!System.AppDomain.ExecuteAssemblyByName(string assemblyName, string[] args) Line 145
	at /_/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs(145)
ConsoleApp1.dll!Program.<Main>$(string[] args) Line 5
	at C:\Users\Chris\source\repos\ConsoleApp1\ConsoleApp1\Program.cs(5)

```

It works perfectly fine if the assembly is loaded with file path. But when it from rawCoffAssembly data. For some reason it want the assembly to exists on disk in the execution path of the main `AppDomain`. But if you load it outside the AppDomain with
```csharp
AppDomain.CurrentDomain.Load(@"C:\Temp\HelloWorld.dll");
```
Like that when call `AppDomain.CurrentDomain.ExecuteAssemblyByName(asm.FullName)` it works fine. It ONLY doesn't work with memory loaded assemblies. `ExecuteAssemblyByName` tries to load the assembly again even tho this is load like the below code.

AND YOU CAN'T SAY THIS BY DESIGN!!!!! 😠

**Comment by danmoseley** [comment]
@cschuchardt88 this should be in the dotnet/runtime repo. I'll move it.
